export const devices = [
  'System (A1)',
  'System (B2)'
]

export const modes = [
  '---',
  'Data Edit',
  'Data Read',
  'Emergency 1',
  'Emergency 2',
  'Map Edit',
  'Step by Step',
  'Preset',
  'Automatic'
]

export const operations = [
  '---',
  'Alarm on',
  'Alarm off',
  'Switch function mode',
  'Card PIN code changed',
  'Stall in',
  'Stall out',
  'Shuffle in',
  'Shuffle out',
  '---',
  'Exit request',
  'Entry request',
  '---',
  '---',
  '---',
  '---'
]

export const measures = [
  'Laser V1',
  'Laser V2',
  'Encoder H',
  'Encoder R',
  'Laser V1',
  'Laser V2',
  'Encoder H',
  'Encoder R'
]

export const inputs1 = [
  { addr: 'E0.0', label: 'A', info: '' },
  { addr: 'E0.1', label: 'B', info: '' },
  { addr: 'E0.2', label: 'C', info: '' },
  { addr: 'E0.3', label: 'D', info: '' },
  { addr: 'E0.4', label: 'STR', info: '' },
  { addr: 'E0.5', label: 'OK', info: '' },
  { addr: 'E0.6', label: 'DAT', info: '' },
  { addr: 'E0.7', label: 'FE12', info: '' },
  { addr: 'E1.0', label: 'A', info: '' },
  { addr: 'E1.1', label: 'B', info: '' },
  { addr: 'E1.2', label: 'C', info: '' },
  { addr: 'E1.3', label: 'D', info: '' },
  { addr: 'E1.4', label: 'STR', info: '' },
  { addr: 'E1.5', label: 'OK', info: '' },
  { addr: 'E1.6', label: 'DAT', info: '' },
  { addr: 'E1.7', label: '', info: '' },
  { addr: 'E2.0', label: 'AF1', info: '' },
  { addr: 'E2.1', label: 'AF2', info: '' },
  { addr: 'E2.2', label: '', info: '' },
  { addr: 'E2.3', label: 'RSI', info: '' },
  { addr: 'E2.4', label: '', info: '' },
  { addr: 'E2.5', label: '', info: '' },
  { addr: 'E2.6', label: '', info: '' },
  { addr: 'E2.7', label: '', info: '' },
  { addr: 'E3.0', label: '', info: '' },
  { addr: 'E3.1', label: '', info: '' },
  { addr: 'E3.2', label: '', info: '' },
  { addr: 'E3.3', label: '', info: '' },
  { addr: 'E3.4', label: '', info: '' },
  { addr: 'E3.5', label: '', info: '' },
  { addr: 'E3.6', label: '', info: '' },
  { addr: 'E3.7', label: '', info: '' }
]
export const inputs2 = [
  { addr: 'E100.0', label: 'A', info: '' },
  { addr: 'E100.1', label: 'B', info: '' },
  { addr: 'E100.2', label: 'C', info: '' },
  { addr: 'E100.3', label: 'D', info: '' },
  { addr: 'E100.4', label: 'OK', info: '' },
  { addr: 'E100.5', label: 'S2', info: '' },
  { addr: 'E100.6', label: 'S2', info: '' },
  { addr: 'E100.7', label: 'S2', info: '' },
  { addr: 'E101.0', label: 'A', info: '' },
  { addr: 'E101.1', label: 'B', info: '' },
  { addr: 'E101.2', label: 'C', info: '' },
  { addr: 'E101.3', label: 'D', info: '' },
  { addr: 'E101.4', label: 'STR', info: '' },
  { addr: 'E101.5', label: 'OK', info: '' },
  { addr: 'E101.6', label: 'DAT', info: '' },
  { addr: 'E101.7', label: 'UC', info: '' },
  { addr: 'E102.0', label: 'HEN', info: 'Hoisting Motors' },
  { addr: 'E102.1', label: '', info: '' },
  { addr: 'E102.2', label: '', info: '' },
  { addr: 'E102.3', label: '', info: '' },
  { addr: 'E102.4', label: 'EZP', info: 'Pedestrian door closed' },
  { addr: 'E102.5', label: 'FDR2', info: '' },
  { addr: 'E102.6', label: 'FDL2', info: '' },
  { addr: 'E102.7', label: 'APE', info: '' },
  { addr: 'E103.0', label: '', info: '' },
  { addr: 'E103.1', label: '', info: '' },
  { addr: 'E103.2', label: '', info: '' },
  { addr: 'E103.3', label: 'RSI', info: '' },
  { addr: 'E103.4', label: 'DB32', info: '' },
  { addr: 'E103.5', label: 'DBHZ', info: '' },
  { addr: 'E103.6', label: 'KXPE', info: '' },
  { addr: 'E103.7', label: '', info: '' },
  { addr: 'E104.0', label: 'KBA', info: '' },
  { addr: 'E104.1', label: '', info: '' },
  { addr: 'E104.2', label: 'SA', info: '' },
  { addr: 'E104.3', label: 'IV1', info: '' },
  { addr: 'E104.4', label: 'SBK1', info: '' },
  { addr: 'E104.5', label: 'ASBK', info: '' },
  { addr: 'E104.6', label: 'RT12', info: '' },
  { addr: 'E104.7', label: 'SQA', info: '' },
  { addr: 'E105.0', label: 'FE1', info: '' },
  { addr: 'E105.1', label: 'EXHM', info: 'Half-moon position check' },
  { addr: 'E105.2', label: 'AF9', info: '' },
  { addr: 'E105.3', label: 'ASH', info: '' },
  { addr: 'E105.4', label: 'AHIV', info: '' },
  { addr: 'E105.5', label: 'S1', info: '' },
  { addr: 'E105.6', label: 'S1', info: '' },
  { addr: 'E105.7', label: 'S1', info: '' },
  { addr: 'E106.0', label: 'EZE', info: '' },
  { addr: 'E106.1', label: 'EOE', info: '' },
  { addr: 'E106.2', label: 'FBE', info: '' },
  { addr: 'E106.3', label: 'FPE', info: '' },
  { addr: 'E106.4', label: 'FDR1', info: '' },
  { addr: 'E106.5', label: 'FDL1', info: '' },
  { addr: 'E106.6', label: 'FTA1', info: '' },
  { addr: 'E106.7', label: 'FTA2', info: '' },
  { addr: 'E107.0', label: 'FTA3', info: '' },
  { addr: 'E107.1', label: 'FLP1', info: '' },
  { addr: 'E107.2', label: 'FTA4', info: '' },
  { addr: 'E107.3', label: 'FLP2', info: '' },
  { addr: 'E107.4', label: 'FLA', info: '' },
  { addr: 'E107.5', label: 'FLP3', info: '' },
  { addr: 'E107.6', label: 'RX1', info: '' },
  { addr: 'E107.7', label: 'RX2', info: '' }
]
export const inputs3 = [
  { addr: 'E110.0', label: 'RMV', info: '' },
  { addr: 'E110.1', label: 'RMH', info: '' },
  { addr: 'E110.2', label: 'RES', info: '' },
  { addr: 'E110.3', label: 'REH', info: '' },
  { addr: 'E110.4', label: 'RCV', info: '' },
  { addr: 'E110.5', label: 'REAV', info: '' },
  { addr: 'E110.6', label: 'REAH', info: '' },
  { addr: 'E110.7', label: 'RCH', info: '' },
  { addr: 'E111.0', label: 'EOM1', info: '' },
  { addr: 'E111.1', label: 'EZM1', info: '' },
  { addr: 'E111.2', label: 'AMM1', info: '' },
  { addr: 'E111.3', label: 'EOM2', info: '' },
  { addr: 'E111.4', label: 'EZM2', info: '' },
  { addr: 'E111.5', label: 'AMM2', info: '' },
  { addr: 'E111.6', label: '', info: '' },
  { addr: 'E111.7', label: 'EXD', info: '' },
  { addr: 'E112.0', label: 'AD', info: '' },
  { addr: 'E112.1', label: 'EOMD', info: '' },
  { addr: 'E112.2', label: 'EZMD', info: '' },
  { addr: 'E112.3', label: 'AMD', info: '' },
  { addr: 'E112.4', label: '', info: '' },
  { addr: 'E112.5', label: 'AKKS', info: '' },
  { addr: 'E112.6', label: 'ACR1', info: '' },
  { addr: 'E112.7', label: 'TCR1', info: '' },
  { addr: 'E113.0', label: 'FE1', info: '' },
  { addr: 'E113.1', label: 'KEXPV', info: '' },
  { addr: 'E113.2', label: 'EXPV', info: '' },
  { addr: 'E113.3', label: 'MNR', info: '' },
  { addr: 'E113.4', label: 'MNL', info: '' },
  { addr: 'E113.5', label: 'FTAC', info: '' },
  { addr: 'E113.6', label: 'EMC', info: '' },
  { addr: 'E113.7', label: '', info: '' },
  { addr: 'E114.0', label: 'FTXV', info: '' },
  { addr: 'E114.1', label: 'FTXH', info: '' },
  { addr: 'E114.2', label: 'FRE', info: '' },
  { addr: 'E114.3', label: 'ECA', info: '' },
  { addr: 'E114.4', label: 'ECB', info: '' },
  { addr: 'E114.5', label: 'EM', info: '' },
  { addr: 'E114.6', label: 'AMC', info: '' },
  { addr: 'E114.7', label: 'MTC', info: '' }
]
export const inputs4 = [
  { addr: 'E200.0', label: 'A', info: '' },
  { addr: 'E200.1', label: 'B', info: '' },
  { addr: 'E200.2', label: 'C', info: '' },
  { addr: 'E200.3', label: 'D', info: '' },
  { addr: 'E200.4', label: 'OK', info: '' },
  { addr: 'E200.5', label: 'S2', info: '' },
  { addr: 'E200.6', label: 'S2', info: '' },
  { addr: 'E200.7', label: 'S2', info: '' },
  { addr: 'E201.0', label: 'A', info: '' },
  { addr: 'E201.1', label: 'B', info: '' },
  { addr: 'E201.2', label: 'C', info: '' },
  { addr: 'E201.3', label: 'D', info: '' },
  { addr: 'E201.4', label: 'STR', info: '' },
  { addr: 'E201.5', label: 'OK', info: '' },
  { addr: 'E201.6', label: 'DAT', info: '' },
  { addr: 'E201.7', label: 'UC', info: '' },
  { addr: 'E202.0', label: 'HEN', info: 'Hoisting Motors' },
  { addr: 'E202.1', label: '', info: '' },
  { addr: 'E202.2', label: '', info: '' },
  { addr: 'E202.3', label: '', info: '' },
  { addr: 'E202.4', label: 'EZP', info: 'Pedestrian door closed' },
  { addr: 'E202.5', label: 'FDR2', info: '' },
  { addr: 'E202.6', label: 'FDL2', info: '' },
  { addr: 'E202.7', label: 'APE', info: '' },
  { addr: 'E203.0', label: '', info: '' },
  { addr: 'E203.1', label: '', info: '' },
  { addr: 'E203.2', label: '', info: '' },
  { addr: 'E203.3', label: 'RSI', info: '' },
  { addr: 'E203.4', label: 'DB32', info: '' },
  { addr: 'E203.5', label: 'DBHZ', info: '' },
  { addr: 'E203.6', label: 'KXPE', info: '' },
  { addr: 'E203.7', label: '', info: '' },
  { addr: 'E204.0', label: 'KBA', info: '' },
  { addr: 'E204.1', label: '', info: '' },
  { addr: 'E204.2', label: 'SA', info: '' },
  { addr: 'E204.3', label: 'IV1', info: '' },
  { addr: 'E204.4', label: 'SBK1', info: '' },
  { addr: 'E204.5', label: 'ASBK', info: '' },
  { addr: 'E204.6', label: 'RT12', info: '' },
  { addr: 'E204.7', label: 'SQA', info: '' },
  { addr: 'E205.0', label: 'FE1', info: '' },
  { addr: 'E205.1', label: 'EXHM', info: 'Half-moon position check' },
  { addr: 'E205.2', label: 'AF9', info: '' },
  { addr: 'E205.3', label: 'ASH', info: '' },
  { addr: 'E205.4', label: 'AHIV', info: '' },
  { addr: 'E205.5', label: 'S1', info: '' },
  { addr: 'E205.6', label: 'S1', info: '' },
  { addr: 'E205.7', label: 'S1', info: '' },
  { addr: 'E206.0', label: 'EZE', info: '' },
  { addr: 'E206.1', label: 'EOE', info: '' },
  { addr: 'E206.2', label: 'FBE', info: '' },
  { addr: 'E206.3', label: 'FPE', info: '' },
  { addr: 'E206.4', label: 'FDR1', info: '' },
  { addr: 'E206.5', label: 'FDL1', info: '' },
  { addr: 'E206.6', label: 'FTA1', info: '' },
  { addr: 'E206.7', label: 'FTA2', info: '' },
  { addr: 'E207.0', label: 'FTA3', info: '' },
  { addr: 'E207.1', label: 'FLP1', info: '' },
  { addr: 'E207.2', label: 'FTA4', info: '' },
  { addr: 'E207.3', label: 'FLP2', info: '' },
  { addr: 'E207.4', label: 'FLA', info: '' },
  { addr: 'E207.5', label: 'FLP3', info: '' },
  { addr: 'E207.6', label: 'RX1', info: '' },
  { addr: 'E207.7', label: 'RX2', info: '' }
]
export const inputs5 = [
  { addr: 'E210.0', label: 'RMV', info: '' },
  { addr: 'E210.1', label: 'RMH', info: '' },
  { addr: 'E210.2', label: 'RES', info: '' },
  { addr: 'E210.3', label: 'REH', info: '' },
  { addr: 'E210.4', label: 'RCV', info: '' },
  { addr: 'E210.5', label: 'REAV', info: '' },
  { addr: 'E210.6', label: 'REAH', info: '' },
  { addr: 'E210.7', label: 'RCH', info: '' },
  { addr: 'E211.0', label: 'EOM1', info: '' },
  { addr: 'E211.1', label: 'EZM1', info: '' },
  { addr: 'E211.2', label: 'AMM1', info: '' },
  { addr: 'E211.3', label: 'EOM2', info: '' },
  { addr: 'E211.4', label: 'EZM2', info: '' },
  { addr: 'E211.5', label: 'AMM2', info: '' },
  { addr: 'E211.6', label: '', info: '' },
  { addr: 'E211.7', label: 'EXD', info: '' },
  { addr: 'E212.0', label: 'AD', info: '' },
  { addr: 'E212.1', label: 'EOMD', info: '' },
  { addr: 'E212.2', label: 'EZMD', info: '' },
  { addr: 'E212.3', label: 'AMD', info: '' },
  { addr: 'E212.4', label: '', info: '' },
  { addr: 'E212.5', label: 'AKKS', info: '' },
  { addr: 'E212.6', label: 'ACR1', info: '' },
  { addr: 'E212.7', label: 'TCR1', info: '' },
  { addr: 'E213.0', label: 'FE1', info: '' },
  { addr: 'E213.1', label: 'KEXPV', info: '' },
  { addr: 'E213.2', label: 'EXPV', info: '' },
  { addr: 'E213.3', label: 'MNR', info: '' },
  { addr: 'E213.4', label: 'MNL', info: '' },
  { addr: 'E213.5', label: 'FTAC', info: '' },
  { addr: 'E213.6', label: 'EMC', info: '' },
  { addr: 'E213.7', label: '', info: '' },
  { addr: 'E214.0', label: 'FTXV', info: '' },
  { addr: 'E214.1', label: 'FTXH', info: '' },
  { addr: 'E214.2', label: 'FRE', info: '' },
  { addr: 'E214.3', label: 'ECA', info: '' },
  { addr: 'E214.4', label: 'ECB', info: '' },
  { addr: 'E214.5', label: 'EM', info: '' },
  { addr: 'E214.6', label: 'AMC', info: '' },
  { addr: 'E214.7', label: 'MTC', info: '' }
]
export const outputs1 = [
  { addr: 'A0.0', label: 'LKU1', info: '' },
  { addr: 'A0.1', label: 'LEU1', info: '' },
  { addr: 'A0.2', label: 'LBU1', info: '' },
  { addr: 'A0.3', label: 'RDY1', info: '' },
  { addr: 'A0.4', label: 'RST1', info: '' },
  { addr: 'A0.5', label: '', info: '' },
  { addr: 'A0.6', label: 'LA', info: '' },
  { addr: 'A0.7', label: 'RBU', info: '' },
  { addr: 'A1.0', label: 'LKU2', info: '' },
  { addr: 'A1.1', label: 'LEU2', info: '' },
  { addr: 'A1.2', label: 'LBU2', info: '' },
  { addr: 'A1.3', label: 'RDY2', info: '' },
  { addr: 'A1.4', label: 'RST2', info: '' },
  { addr: 'A1.5', label: '', info: '' },
  { addr: 'A1.6', label: 'LC-A1', info: '' },
  { addr: 'A1.7', label: 'LC-B2', info: '' }
]
export const outputs2 = [
  { addr: 'A100.0', label: 'SQA', info: '' },
  { addr: 'A100.1', label: 'KBA', info: '' },
  { addr: 'A100.2', label: 'SBK1', info: '' },
  { addr: 'A100.3', label: 'KXPE', info: '' },
  { addr: 'A100.4', label: 'SZE', info: '' },
  { addr: 'A100.5', label: 'SOE', info: '' },
  { addr: 'A100.6', label: 'LA', info: '' },
  { addr: 'A100.7', label: 'LC', info: '' },
  { addr: 'A101.0', label: 'L1', info: '' },
  { addr: 'A101.1', label: 'L2', info: '' },
  { addr: 'A101.2', label: 'L3', info: '' },
  { addr: 'A101.3', label: 'L4', info: '' },
  { addr: 'A101.4', label: 'L5', info: '' },
  { addr: 'A101.5', label: 'RFE', info: '' },
  { addr: 'A101.6', label: 'RLN', info: '' },
  { addr: 'A101.7', label: 'RBE', info: '' },
  { addr: 'A102.0', label: '', info: '' },
  { addr: 'A102.1', label: '', info: '' },
  { addr: 'A102.2', label: '', info: '' },
  { addr: 'A102.3', label: '', info: '' },
  { addr: 'A102.4', label: '', info: '' },
  { addr: 'A102.5', label: '', info: '' },
  { addr: 'A102.6', label: '', info: '' },
  { addr: 'A102.7', label: 'SPE', info: '' },
  { addr: 'A103.0', label: 'LKE', info: '' },
  { addr: 'A103.1', label: 'LEE', info: '' },
  { addr: 'A103.2', label: 'LBE', info: '' },
  { addr: 'A103.3', label: 'RDY', info: '' },
  { addr: 'A103.4', label: 'RST', info: '' },
  { addr: 'A103.5', label: 'SBK2', info: '' },
  { addr: 'A103.6', label: 'TLIV', info: '' },
  { addr: 'A103.7', label: 'KEM', info: '' },
  { addr: 'A104.0', label: 'A', info: '' },
  { addr: 'A104.1', label: 'B', info: '' },
  { addr: 'A104.2', label: 'C', info: '' },
  { addr: 'A104.3', label: 'D', info: '' },
  { addr: 'A104.4', label: 'AD1', info: '' },
  { addr: 'A104.5', label: 'AD2', info: '' },
  { addr: 'A104.6', label: 'AD3', info: '' },
  { addr: 'A104.7', label: 'STR', info: '' },
  { addr: 'A105.0', label: '', info: '' },
  { addr: 'A105.1', label: '', info: '' },
  { addr: 'A105.2', label: '', info: '' },
  { addr: 'A105.3', label: '', info: '' },
  { addr: 'A105.4', label: '', info: '' },
  { addr: 'A105.5', label: '', info: '' },
  { addr: 'A105.6', label: '', info: '' },
  { addr: 'A105.7', label: '', info: '' }
]
export const outputs3 = [
  { addr: 'A110.0', label: 'SMA1', info: '' },
  { addr: 'A110.1', label: 'SMB1', info: '' },
  { addr: 'A110.2', label: 'SMA2', info: '' },
  { addr: 'A110.3', label: 'SMB2', info: '' },
  { addr: 'A110.4', label: 'SMAD', info: '' },
  { addr: 'A110.5', label: 'SMBD', info: '' },
  { addr: 'A110.6', label: '', info: '' },
  { addr: 'A110.7', label: '', info: '' },
  { addr: 'A111.0', label: 'TD', info: '' },
  { addr: 'A111.1', label: '', info: '' },
  { addr: 'A111.2', label: 'KCS', info: '' },
  { addr: 'A111.3', label: 'KCV', info: '' },
  { addr: 'A111.4', label: 'KCH', info: '' },
  { addr: 'A111.5', label: 'TCR1', info: '' },
  { addr: 'A111.6', label: '', info: '' },
  { addr: 'A111.7', label: '', info: '' },
  { addr: 'A112.0', label: 'T10', info: '' },
  { addr: 'A112.1', label: 'T2', info: '' },
  { addr: 'A112.2', label: 'TRA', info: '' },
  { addr: 'A112.3', label: 'TRB', info: '' },
  { addr: 'A112.4', label: 'TCR', info: '' },
  { addr: 'A112.5', label: 'SCA', info: '' },
  { addr: 'A112.6', label: 'SCB', info: '' },
  { addr: 'A112.7', label: '', info: '' }
]
export const outputs4 = [
  { addr: 'A200.0', label: 'SQA', info: '' },
  { addr: 'A200.1', label: 'KBA', info: '' },
  { addr: 'A200.2', label: 'SBK1', info: '' },
  { addr: 'A200.3', label: 'KXPE', info: '' },
  { addr: 'A200.4', label: 'SZE', info: '' },
  { addr: 'A200.5', label: 'SOE', info: '' },
  { addr: 'A200.6', label: 'LA', info: '' },
  { addr: 'A200.7', label: 'LC', info: '' },
  { addr: 'A201.0', label: 'L1', info: '' },
  { addr: 'A201.1', label: 'L2', info: '' },
  { addr: 'A201.2', label: 'L3', info: '' },
  { addr: 'A201.3', label: 'L4', info: '' },
  { addr: 'A201.4', label: 'L5', info: '' },
  { addr: 'A201.5', label: 'RFE', info: '' },
  { addr: 'A201.6', label: 'RLN', info: '' },
  { addr: 'A201.7', label: 'RBE', info: '' },
  { addr: 'A202.0', label: '', info: '' },
  { addr: 'A202.1', label: '', info: '' },
  { addr: 'A202.2', label: '', info: '' },
  { addr: 'A202.3', label: '', info: '' },
  { addr: 'A202.4', label: '', info: '' },
  { addr: 'A202.5', label: '', info: '' },
  { addr: 'A202.6', label: '', info: '' },
  { addr: 'A202.7', label: 'SPE', info: '' },
  { addr: 'A203.0', label: 'LKE', info: '' },
  { addr: 'A203.1', label: 'LEE', info: '' },
  { addr: 'A203.2', label: 'LBE', info: '' },
  { addr: 'A203.3', label: 'RDY', info: '' },
  { addr: 'A203.4', label: 'RST', info: '' },
  { addr: 'A203.5', label: 'SBK2', info: '' },
  { addr: 'A203.6', label: 'TLIV', info: '' },
  { addr: 'A203.7', label: 'KEM', info: '' },
  { addr: 'A204.0', label: 'A', info: '' },
  { addr: 'A204.1', label: 'B', info: '' },
  { addr: 'A204.2', label: 'C', info: '' },
  { addr: 'A204.3', label: 'D', info: '' },
  { addr: 'A204.4', label: 'AD1', info: '' },
  { addr: 'A204.5', label: 'AD2', info: '' },
  { addr: 'A204.6', label: 'AD3', info: '' },
  { addr: 'A204.7', label: 'STR', info: '' },
  { addr: 'A205.0', label: '', info: '' },
  { addr: 'A205.1', label: '', info: '' },
  { addr: 'A205.2', label: '', info: '' },
  { addr: 'A205.3', label: '', info: '' },
  { addr: 'A205.4', label: '', info: '' },
  { addr: 'A205.5', label: '', info: '' },
  { addr: 'A205.6', label: '', info: '' },
  { addr: 'A205.7', label: '', info: '' }
]
export const outputs5 = [
  { addr: 'A210.0', label: 'SMA1', info: '' },
  { addr: 'A210.1', label: 'SMB1', info: '' },
  { addr: 'A210.2', label: 'SMA2', info: '' },
  { addr: 'A210.3', label: 'SMB2', info: '' },
  { addr: 'A210.4', label: 'SMAD', info: '' },
  { addr: 'A210.5', label: 'SMBD', info: '' },
  { addr: 'A210.6', label: '', info: '' },
  { addr: 'A210.7', label: '', info: '' },
  { addr: 'A211.0', label: 'TD', info: '' },
  { addr: 'A211.1', label: '', info: '' },
  { addr: 'A211.2', label: 'KCS', info: '' },
  { addr: 'A211.3', label: 'KCV', info: '' },
  { addr: 'A211.4', label: 'KCH', info: '' },
  { addr: 'A211.5', label: 'TCR1', info: '' },
  { addr: 'A211.6', label: '', info: '' },
  { addr: 'A211.7', label: '', info: '' },
  { addr: 'A212.0', label: 'T10', info: '' },
  { addr: 'A212.1', label: 'T2', info: '' },
  { addr: 'A212.2', label: 'TRA', info: '' },
  { addr: 'A212.3', label: 'TRB', info: '' },
  { addr: 'A212.4', label: 'TCR', info: '' },
  { addr: 'A212.5', label: 'SCA', info: '' },
  { addr: 'A212.6', label: 'SCB', info: '' },
  { addr: 'A212.7', label: '', info: '' }
]
export const merkers1 = [
  { addr: 'M0.0', label: '', info: '' },
  { addr: 'M0.1', label: '', info: '' },
  { addr: 'M0.2', label: '', info: '' },
  { addr: 'M0.3', label: '', info: '' },
  { addr: 'M0.4', label: '', info: '' },
  { addr: 'M0.5', label: '', info: '' },
  { addr: 'M0.6', label: '', info: '' },
  { addr: 'M0.7', label: '', info: '' },
  { addr: 'M1.0', label: '', info: '' },
  { addr: 'M1.1', label: '', info: '' },
  { addr: 'M1.2', label: '', info: '' },
  { addr: 'M1.3', label: '', info: '' },
  { addr: 'M1.4', label: '', info: '' },
  { addr: 'M1.5', label: '', info: '' },
  { addr: 'M1.6', label: '', info: '' },
  { addr: 'M1.7', label: '', info: '' },
  { addr: 'M2.0', label: '', info: '' },
  { addr: 'M2.1', label: '', info: '' },
  { addr: 'M2.2', label: '', info: '' },
  { addr: 'M2.3', label: '', info: '' },
  { addr: 'M2.4', label: '', info: '' },
  { addr: 'M2.5', label: '', info: '' },
  { addr: 'M2.6', label: '', info: '' },
  { addr: 'M2.7', label: '', info: '' },
  { addr: 'M3.0', label: '', info: '' },
  { addr: 'M3.1', label: '', info: '' },
  { addr: 'M3.2', label: '', info: '' },
  { addr: 'M3.3', label: '', info: '' },
  { addr: 'M3.4', label: '', info: '' },
  { addr: 'M3.5', label: '', info: '' },
  { addr: 'M3.6', label: '', info: '' },
  { addr: 'M3.7', label: '', info: '' },
  { addr: 'M4.0', label: '', info: '' },
  { addr: 'M4.1', label: '', info: '' },
  { addr: 'M4.2', label: '', info: '' },
  { addr: 'M4.3', label: '', info: '' },
  { addr: 'M4.4', label: '', info: '' },
  { addr: 'M4.5', label: '', info: '' },
  { addr: 'M4.6', label: '', info: '' },
  { addr: 'M4.7', label: '', info: '' },
  { addr: 'M5.0', label: '', info: '' },
  { addr: 'M5.1', label: '', info: '' },
  { addr: 'M5.2', label: '', info: '' },
  { addr: 'M5.3', label: '', info: '' },
  { addr: 'M5.4', label: '', info: '' },
  { addr: 'M5.5', label: '', info: '' },
  { addr: 'M5.6', label: '', info: '' },
  { addr: 'M5.7', label: '', info: '' },
  { addr: 'M6.0', label: '', info: '' },
  { addr: 'M6.1', label: '', info: '' },
  { addr: 'M6.2', label: '', info: '' },
  { addr: 'M6.3', label: '', info: '' },
  { addr: 'M6.4', label: '', info: '' },
  { addr: 'M6.5', label: '', info: '' },
  { addr: 'M6.6', label: '', info: '' },
  { addr: 'M6.7', label: '', info: '' },
  { addr: 'M7.0', label: '', info: '' },
  { addr: 'M7.1', label: '', info: '' },
  { addr: 'M7.2', label: '', info: '' },
  { addr: 'M7.3', label: '', info: '' },
  { addr: 'M7.4', label: '', info: '' },
  { addr: 'M7.5', label: '', info: '' },
  { addr: 'M7.6', label: '', info: '' },
  { addr: 'M7.7', label: '', info: '' }
]
export const alarms1 = [
  { class: 'A1', label: 'AL1', info: '' },
  { class: 'A1', label: 'AL2', info: '' },
  { class: 'A1', label: 'AL3', info: '' },
  { class: 'A1', label: 'AL4', info: '' },
  { class: 'A1', label: 'AL5', info: '' },
  { class: 'A1', label: 'AL6', info: '' },
  { class: 'A1', label: 'AL7', info: '' },
  { class: 'A1', label: 'AL8', info: '' },
  { class: 'A1', label: 'AL9', info: '' },
  { class: 'A1', label: 'AL10', info: '' },
  { class: 'A1', label: 'AL11', info: '' },
  { class: 'A1', label: 'AL12', info: '' },
  { class: 'A1', label: 'AL13', info: '' },
  { class: 'A1', label: 'AL14', info: '' },
  { class: 'A1', label: 'AL15', info: '' },
  { class: 'A1', label: 'AL16', info: '' },
  { class: 'A1', label: 'AL17', info: '' },
  { class: 'A1', label: 'AL18', info: '' },
  { class: 'A1', label: 'AL19', info: '' },
  { class: 'A1', label: 'AL20', info: '' },
  { class: 'A1', label: 'AL21', info: '' },
  { class: 'A1', label: 'AL22', info: '' },
  { class: 'A1', label: 'AL23', info: '' },
  { class: 'A1', label: 'AL24', info: '' },
  { class: 'A1', label: 'AL25', info: '' },
  { class: 'A1', label: 'AL26', info: '' },
  { class: 'A1', label: 'AL27', info: '' },
  { class: 'A1', label: 'AL28', info: '' },
  { class: 'A1', label: 'AL29', info: '' },
  { class: 'A1', label: 'AL30', info: '' },
  { class: 'A1', label: 'AL31', info: '' },
  { class: 'A1', label: 'AL32', info: '' },
  { class: 'A1', label: 'AL33', info: '' },
  { class: 'A1', label: 'AL34', info: '' },
  { class: 'A1', label: 'AL35', info: '' },
  { class: 'A1', label: 'AL36', info: '' },
  { class: 'A1', label: 'AL37', info: '' },
  { class: 'A1', label: 'AL38', info: '' },
  { class: 'A1', label: 'AL39', info: '' },
  { class: 'A1', label: 'AL40', info: '' },
  { class: 'A1', label: 'AL41', info: '' },
  { class: 'A1', label: 'AL42', info: '' },
  { class: 'A1', label: 'AL43', info: '' },
  { class: 'A1', label: 'AL44', info: '' },
  { class: 'A1', label: 'AL45', info: '' },
  { class: 'A1', label: 'AL46', info: '' },
  { class: 'A1', label: 'AL47', info: '' },
  { class: 'A1', label: 'AL48', info: '' },
  { class: 'A1', label: 'AL49', info: '' },
  { class: 'A1', label: 'AL50', info: '' },
  { class: 'A1', label: 'AL51', info: '' },
  { class: 'A1', label: 'AL52', info: '' },
  { class: 'A1', label: 'AL53', info: '' },
  { class: 'A1', label: 'AL54', info: '' },
  { class: 'A1', label: 'AL55', info: '' },
  { class: 'A1', label: 'AL56', info: '' },
  { class: 'A1', label: 'AL57', info: '' },
  { class: 'A1', label: 'AL58', info: '' },
  { class: 'A1', label: 'AL59', info: '' },
  { class: 'A1', label: 'AL60', info: '' },
  { class: 'A1', label: 'AL61', info: '' },
  { class: 'A1', label: 'AL62', info: '' },
  { class: 'A1', label: 'AL63', info: '' },
  { class: 'A1', label: 'AL64', info: '' }
]
export const alarms2 = [
  { class: 'B2', label: 'AL1', info: '' },
  { class: 'B2', label: 'AL2', info: '' },
  { class: 'B2', label: 'AL3', info: '' },
  { class: 'B2', label: 'AL4', info: '' },
  { class: 'B2', label: 'AL5', info: '' },
  { class: 'B2', label: 'AL6', info: '' },
  { class: 'B2', label: 'AL7', info: '' },
  { class: 'B2', label: 'AL8', info: '' },
  { class: 'B2', label: 'AL9', info: '' },
  { class: 'B2', label: 'AL10', info: '' },
  { class: 'B2', label: 'AL11', info: '' },
  { class: 'B2', label: 'AL12', info: '' },
  { class: 'B2', label: 'AL13', info: '' },
  { class: 'B2', label: 'AL14', info: '' },
  { class: 'B2', label: 'AL15', info: '' },
  { class: 'B2', label: 'AL16', info: '' },
  { class: 'B2', label: 'AL17', info: '' },
  { class: 'B2', label: 'AL18', info: '' },
  { class: 'B2', label: 'AL19', info: '' },
  { class: 'B2', label: 'AL20', info: '' },
  { class: 'B2', label: 'AL21', info: '' },
  { class: 'B2', label: 'AL22', info: '' },
  { class: 'B2', label: 'AL23', info: '' },
  { class: 'B2', label: 'AL24', info: '' },
  { class: 'B2', label: 'AL25', info: '' },
  { class: 'B2', label: 'AL26', info: '' },
  { class: 'B2', label: 'AL27', info: '' },
  { class: 'B2', label: 'AL28', info: '' },
  { class: 'B2', label: 'AL29', info: '' },
  { class: 'B2', label: 'AL30', info: '' },
  { class: 'B2', label: 'AL31', info: '' },
  { class: 'B2', label: 'AL32', info: '' },
  { class: 'B2', label: 'AL33', info: '' },
  { class: 'B2', label: 'AL34', info: '' },
  { class: 'B2', label: 'AL35', info: '' },
  { class: 'B2', label: 'AL36', info: '' },
  { class: 'B2', label: 'AL37', info: '' },
  { class: 'B2', label: 'AL38', info: '' },
  { class: 'B2', label: 'AL39', info: '' },
  { class: 'B2', label: 'AL40', info: '' },
  { class: 'B2', label: 'AL41', info: '' },
  { class: 'B2', label: 'AL42', info: '' },
  { class: 'B2', label: 'AL43', info: '' },
  { class: 'B2', label: 'AL44', info: '' },
  { class: 'B2', label: 'AL45', info: '' },
  { class: 'B2', label: 'AL46', info: '' },
  { class: 'B2', label: 'AL47', info: '' },
  { class: 'B2', label: 'AL48', info: '' },
  { class: 'B2', label: 'AL49', info: '' },
  { class: 'B2', label: 'AL50', info: '' },
  { class: 'B2', label: 'AL51', info: '' },
  { class: 'B2', label: 'AL52', info: '' },
  { class: 'B2', label: 'AL53', info: '' },
  { class: 'B2', label: 'AL54', info: '' },
  { class: 'B2', label: 'AL55', info: '' },
  { class: 'B2', label: 'AL56', info: '' },
  { class: 'B2', label: 'AL57', info: '' },
  { class: 'B2', label: 'AL58', info: '' },
  { class: 'B2', label: 'AL59', info: '' },
  { class: 'B2', label: 'AL60', info: '' },
  { class: 'B2', label: 'AL61', info: '' },
  { class: 'B2', label: 'AL62', info: '' },
  { class: 'B2', label: 'AL63', info: '' },
  { class: 'B2', label: 'AL64', info: '' }
]
