export const devices = [
  'System (EL)'
]

export const modes = [
  '---',
  'Data Edit',
  'Data Read',
  'Emergency 1',
  'Emergency 2',
  'Map Edit',
  'Step by Step',
  'Preset',
  'Automatic'
]

export const operations = [
  '---',
  'Alarm on',
  'Alarm off',
  'Switch function mode',
  'Card PIN code changed',
  'Stall in',
  'Stall out',
  'Shuffle in',
  'Shuffle out',
  '---',
  'Exit request',
  'Entry request',
  '---',
  '---',
  '---',
  '---'
]

export const measures = [
  'Laser V1',
  'Laser V2',
  'Encoder H',
  'Encoder R'
]

export const inputs1 = [
  { addr: 'E4.0', label: 'A', info: '' },
  { addr: 'E4.1', label: 'B', info: '' },
  { addr: 'E4.2', label: 'C', info: '' },
  { addr: 'E4.3', label: 'D', info: '' },
  { addr: 'E4.4', label: 'OK', info: '' },
  { addr: 'E4.5', label: 'S2', info: '' },
  { addr: 'E4.6', label: 'S2', info: '' },
  { addr: 'E4.7', label: 'S2', info: '' },
  { addr: 'E5.0', label: 'A', info: '' },
  { addr: 'E5.1', label: 'B', info: '' },
  { addr: 'E5.2', label: 'C', info: '' },
  { addr: 'E5.3', label: 'D', info: '' },
  { addr: 'E5.4', label: 'STR', info: '' },
  { addr: 'E5.5', label: 'OK', info: '' },
  { addr: 'E5.6', label: 'DAT', info: '' },
  { addr: 'E5.7', label: 'UC', info: '' },
  { addr: 'E6.0', label: 'EOM1', info: '' },
  { addr: 'E6.1', label: 'EZM1', info: '' },
  { addr: 'E6.2', label: 'EOM2', info: '' },
  { addr: 'E6.3', label: 'EZM2', info: '' },
  { addr: 'E6.4', label: 'EOM3', info: '' },
  { addr: 'E6.5', label: 'EZM3', info: '' },
  { addr: 'E6.6', label: 'EOM4', info: '' },
  { addr: 'E6.7', label: 'EZM4', info: '' },
  { addr: 'E7.0', label: 'AMM', info: '' },
  { addr: 'E7.1', label: '', info: '' },
  { addr: 'E7.2', label: '', info: '' },
  { addr: 'E7.3', label: 'RSI', info: '' },
  { addr: 'E7.4', label: 'DB32', info: '' },
  { addr: 'E7.5', label: 'DBHZ', info: '' },
  { addr: 'E7.6', label: '', info: '' },
  { addr: 'E7.7', label: '', info: '' },
  { addr: 'E8.0', label: 'KBA', info: '' },
  { addr: 'E8.1', label: 'KXPE', info: '' },
  { addr: 'E8.2', label: 'SA', info: '' },
  { addr: 'E8.3', label: 'IV1', info: '' },
  { addr: 'E8.4', label: 'KEZE', info: '' },
  { addr: 'E8.5', label: 'IV2', info: '' },
  { addr: 'E8.6', label: 'RT12', info: '' },
  { addr: 'E8.7', label: '', info: '' },
  { addr: 'E9.0', label: 'FE1', info: '' },
  { addr: 'E9.1', label: 'APE', info: '' },
  { addr: 'E9.2', label: 'AF9', info: '' },
  { addr: 'E9.3', label: 'ASH', info: '' },
  { addr: 'E9.4', label: 'AHIV', info: '' },
  { addr: 'E9.5', label: 'S1', info: '' },
  { addr: 'E9.6', label: 'S1', info: '' },
  { addr: 'E9.7', label: 'S1', info: '' },
  { addr: 'E10.0', label: 'EZE', info: '' },
  { addr: 'E10.1', label: 'EOE', info: '' },
  { addr: 'E10.2', label: 'FBE', info: '' },
  { addr: 'E10.3', label: 'FPE', info: '' },
  { addr: 'E10.4', label: 'FDR1', info: '' },
  { addr: 'E10.5', label: 'FDL1', info: '' },
  { addr: 'E10.6', label: 'FTA1', info: '' },
  { addr: 'E10.7', label: 'FTA2', info: '' },
  { addr: 'E11.0', label: 'FLP', info: '' },
  { addr: 'E11.1', label: 'FLA', info: '' },
  { addr: 'E11.2', label: '', info: '' },
  { addr: 'E11.3', label: '', info: '' },
  { addr: 'E11.4', label: 'POD', info: '' },
  { addr: 'E11.5', label: 'RXE', info: '' },
  { addr: 'E11.6', label: '', info: '' },
  { addr: 'E11.7', label: 'FAL', info: 'Fire Alarm' },
  { addr: 'E12.0', label: 'A', info: '' },
  { addr: 'E12.1', label: 'B', info: '' },
  { addr: 'E12.2', label: 'C', info: '' },
  { addr: 'E12.3', label: 'D', info: '' },
  { addr: 'E12.4', label: 'STR', info: '' },
  { addr: 'E12.5', label: 'OK', info: '' },
  { addr: 'E12.6', label: 'DAT', info: '' },
  { addr: 'E12.7', label: '', info: '' },
  { addr: 'E13.0', label: 'A', info: '' },
  { addr: 'E13.1', label: 'B', info: '' },
  { addr: 'E13.2', label: 'C', info: '' },
  { addr: 'E13.3', label: 'D', info: '' },
  { addr: 'E13.4', label: 'STR', info: '' },
  { addr: 'E13.5', label: 'OK', info: '' },
  { addr: 'E13.6', label: 'DAT', info: '' },
  { addr: 'E13.7', label: '', info: '' }
]
export const inputs2 = [
  { addr: 'E14.0', label: 'RMV', info: '' },
  { addr: 'E14.1', label: 'RMH', info: '' },
  { addr: 'E14.2', label: 'RES', info: '' },
  { addr: 'E14.3', label: 'REH', info: '' },
  { addr: 'E14.4', label: 'RCV', info: '' },
  { addr: 'E14.5', label: 'REAV', info: '' },
  { addr: 'E14.6', label: 'REAH', info: '' },
  { addr: 'E14.7', label: 'RCH', info: '' },
  { addr: 'E15.0', label: 'ASBK', info: '' },
  { addr: 'E15.1', label: 'FSBK', info: '' },
  { addr: 'E15.2', label: 'MTC', info: '' },
  { addr: 'E15.3', label: 'ACR', info: '' },
  { addr: 'E15.4', label: 'ASDK', info: '' },
  { addr: 'E15.5', label: '', info: '' },
  { addr: 'E15.6', label: 'F24', info: '' },
  { addr: 'E15.7', label: 'TCR', info: '' },
  { addr: 'E16.0', label: 'FTXV', info: '' },
  { addr: 'E16.1', label: 'FTXH', info: '' },
  { addr: 'E16.2', label: 'EPZ', info: '' },
  { addr: 'E16.3', label: 'EM', info: '' },
  { addr: 'E16.4', label: 'ECA', info: '' },
  { addr: 'E16.5', label: 'ECB', info: '' },
  { addr: 'E16.6', label: 'AMC', info: '' },
  { addr: 'E16.7', label: 'AD', info: '' },
  { addr: 'E17.0', label: 'EXD', info: '' },
  { addr: 'E17.1', label: 'EMC', info: '' },
  { addr: 'E17.2', label: 'KEXPV', info: '' },
  { addr: 'E17.3', label: 'EXPV', info: '' },
  { addr: 'E17.4', label: 'AKKS', info: '' },
  { addr: 'E17.5', label: '', info: '' },
  { addr: 'E17.6', label: 'MNR', info: '' },
  { addr: 'E17.7', label: 'MNL', info: '' }
]
export const outputs1 = [
  { addr: 'A4.0', label: 'KBA1', info: '' },
  { addr: 'A4.1', label: 'LE', info: '' },
  { addr: 'A4.2', label: 'LB', info: '' },
  { addr: 'A4.3', label: 'RDY', info: '' },
  { addr: 'A4.4', label: 'RST', info: '' },
  { addr: 'A4.5', label: 'KXPE', info: '' },
  { addr: 'A4.6', label: 'LA', info: '' },
  { addr: 'A4.7', label: 'LC', info: '' },
  { addr: 'A5.0', label: 'L1', info: '' },
  { addr: 'A5.1', label: 'L2', info: '' },
  { addr: 'A5.2', label: 'L3', info: '' },
  { addr: 'A5.3', label: 'L4', info: '' },
  { addr: 'A5.4', label: 'L5', info: '' },
  { addr: 'A5.5', label: 'RFE', info: '' },
  { addr: 'A5.6', label: 'RLN', info: '' },
  { addr: 'A5.7', label: 'RBE', info: '' },
  { addr: 'A6.0', label: 'A', info: '' },
  { addr: 'A6.1', label: 'B', info: '' },
  { addr: 'A6.2', label: 'C', info: '' },
  { addr: 'A6.3', label: 'D', info: '' },
  { addr: 'A6.4', label: 'AD1', info: '' },
  { addr: 'A6.5', label: 'AD2', info: '' },
  { addr: 'A6.6', label: 'AD3', info: '' },
  { addr: 'A6.7', label: 'STR', info: '' },
  { addr: 'A7.0', label: 'LK', info: '' },
  { addr: 'A7.1', label: 'LE', info: '' },
  { addr: 'A7.2', label: 'LB', info: '' },
  { addr: 'A7.3', label: 'RDY', info: '' },
  { addr: 'A7.4', label: 'RST', info: '' },
  { addr: 'A7.5', label: '', info: '' },
  { addr: 'A7.6', label: 'TLIV', info: '' },
  { addr: 'A7.7', label: 'KEM', info: '' },
  { addr: 'A8.0', label: 'SMA1', info: '' },
  { addr: 'A8.1', label: 'SMB1', info: '' },
  { addr: 'A8.2', label: 'SMA2', info: '' },
  { addr: 'A8.3', label: 'SMB2', info: '' },
  { addr: 'A8.4', label: 'SMA3', info: '' },
  { addr: 'A8.5', label: 'SMB3', info: '' },
  { addr: 'A8.6', label: 'SMA4', info: '' },
  { addr: 'A8.7', label: 'SMB4', info: '' },
  { addr: 'A9.0', label: 'LK', info: '' },
  { addr: 'A9.1', label: 'LE', info: '' },
  { addr: 'A9.2', label: 'LB', info: '' },
  { addr: 'A9.3', label: 'RDY', info: '' },
  { addr: 'A9.4', label: 'RST', info: '' },
  { addr: 'A9.5', label: 'KBA2', info: '' },
  { addr: 'A9.6', label: '', info: '' },
  { addr: 'A9.7', label: '', info: '' }
]
export const outputs2 = [
  { addr: 'A14.0', label: 'TD', info: '' },
  { addr: 'A14.1', label: 'TCR', info: '' },
  { addr: 'A14.2', label: '', info: '' },
  { addr: 'A14.3', label: '', info: '' },
  { addr: 'A14.4', label: 'KCS', info: '' },
  { addr: 'A14.5', label: 'KCV', info: '' },
  { addr: 'A14.6', label: 'KCH', info: '' },
  { addr: 'A14.7', label: 'SBK2', info: '' },
  { addr: 'A15.0', label: 'T10', info: '' },
  { addr: 'A15.1', label: 'T2', info: '' },
  { addr: 'A15.2', label: 'TRA', info: '' },
  { addr: 'A15.3', label: 'TRB', info: '' },
  { addr: 'A15.4', label: 'TCR1', info: '' },
  { addr: 'A15.5', label: 'SCA', info: '' },
  { addr: 'A15.6', label: 'SCB', info: '' },
  { addr: 'A15.7', label: 'SBK1', info: '' }
]
export const merkers1 = [
  { addr: 'M0.0', label: '', info: '' },
  { addr: 'M0.1', label: '', info: '' },
  { addr: 'M0.2', label: '', info: '' },
  { addr: 'M0.3', label: '', info: '' },
  { addr: 'M0.4', label: '', info: '' },
  { addr: 'M0.5', label: '', info: '' },
  { addr: 'M0.6', label: '', info: '' },
  { addr: 'M0.7', label: '', info: '' },
  { addr: 'M1.0', label: '', info: '' },
  { addr: 'M1.1', label: '', info: '' },
  { addr: 'M1.2', label: '', info: '' },
  { addr: 'M1.3', label: '', info: '' },
  { addr: 'M1.4', label: '', info: '' },
  { addr: 'M1.5', label: '', info: '' },
  { addr: 'M1.6', label: '', info: '' },
  { addr: 'M1.7', label: '', info: '' },
  { addr: 'M2.0', label: '', info: '' },
  { addr: 'M2.1', label: '', info: '' },
  { addr: 'M2.2', label: '', info: '' },
  { addr: 'M2.3', label: '', info: '' },
  { addr: 'M2.4', label: '', info: '' },
  { addr: 'M2.5', label: '', info: '' },
  { addr: 'M2.6', label: '', info: '' },
  { addr: 'M2.7', label: '', info: '' },
  { addr: 'M3.0', label: '', info: '' },
  { addr: 'M3.1', label: '', info: '' },
  { addr: 'M3.2', label: '', info: '' },
  { addr: 'M3.3', label: '', info: '' },
  { addr: 'M3.4', label: '', info: '' },
  { addr: 'M3.5', label: '', info: '' },
  { addr: 'M3.6', label: '', info: '' },
  { addr: 'M3.7', label: '', info: '' },
  { addr: 'M4.0', label: '', info: '' },
  { addr: 'M4.1', label: '', info: '' },
  { addr: 'M4.2', label: '', info: '' },
  { addr: 'M4.3', label: '', info: '' },
  { addr: 'M4.4', label: '', info: '' },
  { addr: 'M4.5', label: '', info: '' },
  { addr: 'M4.6', label: '', info: '' },
  { addr: 'M4.7', label: '', info: '' },
  { addr: 'M5.0', label: '', info: '' },
  { addr: 'M5.1', label: '', info: '' },
  { addr: 'M5.2', label: '', info: '' },
  { addr: 'M5.3', label: '', info: '' },
  { addr: 'M5.4', label: '', info: '' },
  { addr: 'M5.5', label: '', info: '' },
  { addr: 'M5.6', label: '', info: '' },
  { addr: 'M5.7', label: '', info: '' },
  { addr: 'M6.0', label: '', info: '' },
  { addr: 'M6.1', label: '', info: '' },
  { addr: 'M6.2', label: '', info: '' },
  { addr: 'M6.3', label: '', info: '' },
  { addr: 'M6.4', label: '', info: '' },
  { addr: 'M6.5', label: '', info: '' },
  { addr: 'M6.6', label: '', info: '' },
  { addr: 'M6.7', label: '', info: '' },
  { addr: 'M7.0', label: '', info: '' },
  { addr: 'M7.1', label: '', info: '' },
  { addr: 'M7.2', label: '', info: '' },
  { addr: 'M7.3', label: '', info: '' },
  { addr: 'M7.4', label: '', info: '' },
  { addr: 'M7.5', label: '', info: '' },
  { addr: 'M7.6', label: '', info: '' },
  { addr: 'M7.7', label: '', info: '' }
]
export const alarms1 = [
  { class: 'EL', label: 'AL1', info: 'Hoisting motor time out' },
  { class: 'EL', label: 'AL2', info: 'Travelling motors time out' },
  { class: 'EL', label: 'AL3', info: 'Silomat travelling 1° bay time out' },
  { class: 'EL', label: 'AL4', info: 'Silomat travelling 2° bay time out' },
  { class: 'EL', label: 'AL5', info: 'Silomat hoisting motor time out' },
  { class: 'EL', label: 'AL6', info: 'Silomat front centering motor time out' },
  { class: 'EL', label: 'AL7', info: 'Silomat back centering motor time out' },
  { class: 'EL', label: 'AL8', info: 'Rotation motor time out' },
  { class: 'EL', label: 'AL9', info: 'Flap motor time out' },
  { class: 'EL', label: 'AL10', info: 'Locking device motor 1 time out' },
  { class: 'EL', label: 'AL11', info: 'Locking device motor 2 time out' },
  { class: 'EL', label: 'AL12', info: 'Locking device motor 3 time out' },
  { class: 'EL', label: 'AL13', info: 'Locking device motor 4 time out' },
  { class: 'EL', label: 'AL14', info: 'Door motor time out' },
  { class: 'EL', label: 'AL15', info: 'Door motor time out' },
  { class: 'EL', label: 'AL16', info: 'AL16' },
  { class: 'EL', label: 'AL17', info: 'AMM Locking device motors thermic' },
  { class: 'EL', label: 'AL18', info: 'Hoisting motors thermic' },
  { class: 'EL', label: 'AL19', info: 'Fuse 24VDC' },
  { class: 'EL', label: 'AL20', info: 'APE Door motor thermic' },
  { class: 'EL', label: 'AL21', info: 'AF9 thermic' },
  { class: 'EL', label: 'AL22', info: 'ASH thermic' },
  { class: 'EL', label: 'AL23', info: 'AHIV thermic' },
  { class: 'EL', label: 'AL24', info: 'ASBK1 thermic' },
  { class: 'EL', label: 'AL25', info: 'Silomat motors thermic' },
  { class: 'EL', label: 'AL26', info: 'ACR thermic' },
  { class: 'EL', label: 'AL27', info: 'ASBK2 thermic' },
  { class: 'EL', label: 'AL28', info: 'F24 fuse' },
  { class: 'EL', label: 'AL29', info: 'AMC Flap motor thermic' },
  { class: 'EL', label: 'AL30', info: 'AD Rotation motor thermic' },
  { class: 'EL', label: 'AL31', info: 'AKKS thermic' },
  { class: 'EL', label: 'AL32', info: 'AL32' },
  { class: 'EL', label: 'AL33', info: 'Locking device EOM/EZM limitswitches' },
  { class: 'EL', label: 'AL34', info: 'Door EZE/EOE limitswitches' },
  { class: 'EL', label: 'AL35', info: 'Flap ECA/ECB limitswitches' },
  { class: 'EL', label: 'AL36', info: 'Silomat centering REAV/REAH sensors' },
  { class: 'EL', label: 'AL37', info: 'AL37' },
  { class: 'EL', label: 'AL38', info: 'AL38' },
  { class: 'EL', label: 'AL39', info: 'AL39' },
  { class: 'EL', label: 'AL40', info: 'AL40' },
  { class: 'EL', label: 'AL41', info: 'AL41' },
  { class: 'EL', label: 'AL42', info: 'AL42' },
  { class: 'EL', label: 'AL43', info: 'AL43' },
  { class: 'EL', label: 'AL44', info: 'AL43' },
  { class: 'EL', label: 'AL45', info: 'AL45' },
  { class: 'EL', label: 'AL46', info: 'AL46' },
  { class: 'EL', label: 'AL47', info: 'AL47' },
  { class: 'EL', label: 'AL48', info: 'AL48' },
  { class: 'EL', label: 'AL49', info: 'AL49' },
  { class: 'EL', label: 'AL50', info: 'AL50' },
  { class: 'EL', label: 'AL51', info: 'AL51' },
  { class: 'EL', label: 'AL52', info: 'AL52' },
  { class: 'EL', label: 'AL53', info: 'AL53' },
  { class: 'EL', label: 'AL54', info: 'AL54' },
  { class: 'EL', label: 'AL55', info: 'AL55' },
  { class: 'EL', label: 'AL56', info: 'AL56' },
  { class: 'EL', label: 'AL57', info: 'AL57' },
  { class: 'EL', label: 'AL58', info: 'AL58' },
  { class: 'EL', label: 'AL59', info: 'AL59' },
  { class: 'EL', label: 'AL60', info: 'AL60' },
  { class: 'EL', label: 'AL61', info: 'AL61' },
  { class: 'EL', label: 'AL62', info: 'AL62' },
  { class: 'EL', label: 'AL63', info: 'AL63' },
  { class: 'EL', label: 'AL64', info: 'AL64' }
]
