export const devices = [
  'Operator',
  'Elevator 1 (S)',
  'Elevator 2 (N)',
  'Elevator 3 (E)',
  'Elevator 4 (W)'
]

export const modes = [
  '---',
  'Data Edit',
  'Data Read',
  'Emergency 1',
  'Emergency 2',
  'Map Edit',
  'Step by Step',
  'Preset',
  'Automatic'
]

export const operations = [
  '---',
  'Alarm On',
  'Alarm Off',
  'Switch Function Mode',
  'Card PIN code changed',
  'Stall In',
  'Stall Out',
  'Shuffle In',
  'Shuffle Out'
]

export const measures = [
  'Laser V1',
  'Laser V2',
  'Encoder H',
  'Encoder R',
  'Laser V1',
  'Laser V2',
  'Encoder H',
  'Encoder R',
  'Laser V1',
  'Laser V2',
  'Laser H1',
  'Laser H2',
  'Laser V1',
  'Laser V2',
  'Laser H1',
  'Laser H2'
]

export const inputs1 = [
  { addr: 'E0.0', label: 'A', info: 'Hex keyboard (A)' },
  { addr: 'E0.1', label: 'B', info: 'Hex keyboard (B)' },
  { addr: 'E0.2', label: '', info: '' },
  { addr: 'E0.3', label: '', info: '' },
  { addr: 'E0.4', label: '', info: '' },
  { addr: 'E0.5', label: '', info: '' },
  { addr: 'E0.6', label: '', info: '' },
  { addr: 'E0.7', label: '', info: '' },
  { addr: 'E1.0', label: '', info: '' },
  { addr: 'E1.1', label: '', info: '' },
  { addr: 'E1.2', label: '', info: '' },
  { addr: 'E1.3', label: '', info: '' },
  { addr: 'E1.4', label: '', info: '' },
  { addr: 'E1.5', label: '', info: '' },
  { addr: 'E1.6', label: '', info: '' },
  { addr: 'E1.7', label: '', info: '' },
  { addr: 'E2.0', label: '', info: '' },
  { addr: 'E2.1', label: '', info: '' },
  { addr: 'E2.2', label: '', info: '' },
  { addr: 'E2.3', label: '', info: '' },
  { addr: 'E2.4', label: '', info: '' },
  { addr: 'E2.5', label: '', info: '' },
  { addr: 'E2.6', label: '', info: '' },
  { addr: 'E2.7', label: '', info: '' },
  { addr: 'E3.0', label: '', info: '' },
  { addr: 'E3.1', label: '', info: '' },
  { addr: 'E3.2', label: '', info: '' },
  { addr: 'E3.3', label: '', info: '' },
  { addr: 'E3.4', label: '', info: '' },
  { addr: 'E3.5', label: '', info: '' },
  { addr: 'E3.6', label: '', info: '' },
  { addr: 'E3.7', label: '', info: '' },
  { addr: 'E4.0', label: '', info: '' },
  { addr: 'E4.1', label: '', info: '' },
  { addr: 'E4.2', label: '', info: '' },
  { addr: 'E4.3', label: '', info: '' },
  { addr: 'E4.4', label: '', info: '' },
  { addr: 'E4.5', label: '', info: '' },
  { addr: 'E4.6', label: '', info: '' },
  { addr: 'E4.7', label: '', info: '' },
  { addr: 'E5.0', label: '', info: '' },
  { addr: 'E5.1', label: '', info: '' },
  { addr: 'E5.2', label: '', info: '' },
  { addr: 'E5.3', label: '', info: '' },
  { addr: 'E5.4', label: '', info: '' },
  { addr: 'E5.5', label: '', info: '' },
  { addr: 'E5.6', label: '', info: '' },
  { addr: 'E5.7', label: '', info: '' }
]
export const inputs2 = [
  { addr: 'E100.0', label: '', info: '' },
  { addr: 'E100.1', label: 'B', info: 'Hex keyboard (B)' },
  { addr: 'E100.2', label: '', info: '' },
  { addr: 'E100.3', label: '', info: '' },
  { addr: 'E100.4', label: '', info: '' },
  { addr: 'E100.5', label: '', info: '' },
  { addr: 'E100.6', label: '', info: '' },
  { addr: 'E100.7', label: '', info: '' },
  { addr: 'E101.0', label: '', info: '' },
  { addr: 'E101.1', label: '', info: '' },
  { addr: 'E101.2', label: '', info: '' },
  { addr: 'E101.3', label: '', info: '' },
  { addr: 'E101.4', label: '', info: '' },
  { addr: 'E101.5', label: '', info: '' },
  { addr: 'E101.6', label: '', info: '' },
  { addr: 'E101.7', label: '', info: '' },
  { addr: 'E102.0', label: '', info: '' },
  { addr: 'E102.1', label: '', info: '' },
  { addr: 'E102.2', label: '', info: '' },
  { addr: 'E102.3', label: '', info: '' },
  { addr: 'E102.4', label: '', info: '' },
  { addr: 'E102.5', label: '', info: '' },
  { addr: 'E102.6', label: '', info: '' },
  { addr: 'E102.7', label: '', info: '' },
  { addr: 'E103.0', label: '', info: '' },
  { addr: 'E103.1', label: '', info: '' },
  { addr: 'E103.2', label: '', info: '' },
  { addr: 'E103.3', label: '', info: '' },
  { addr: 'E103.4', label: '', info: '' },
  { addr: 'E103.5', label: '', info: '' },
  { addr: 'E103.6', label: '', info: '' },
  { addr: 'E103.7', label: '', info: '' },
  { addr: 'E104.0', label: '', info: '' },
  { addr: 'E104.1', label: '', info: '' },
  { addr: 'E104.2', label: '', info: '' },
  { addr: 'E104.3', label: '', info: '' },
  { addr: 'E104.4', label: '', info: '' },
  { addr: 'E104.5', label: '', info: '' },
  { addr: 'E104.6', label: '', info: '' },
  { addr: 'E104.7', label: '', info: '' },
  { addr: 'E105.0', label: '', info: '' },
  { addr: 'E105.1', label: '', info: '' },
  { addr: 'E105.2', label: '', info: '' },
  { addr: 'E105.3', label: '', info: '' },
  { addr: 'E105.4', label: '', info: '' },
  { addr: 'E105.5', label: '', info: '' },
  { addr: 'E105.6', label: '', info: '' },
  { addr: 'E105.7', label: '', info: '' },
  { addr: 'E106.0', label: '', info: '' },
  { addr: 'E106.1', label: '', info: '' },
  { addr: 'E106.2', label: '', info: '' },
  { addr: 'E106.3', label: '', info: '' },
  { addr: 'E106.4', label: '', info: '' },
  { addr: 'E106.5', label: '', info: '' },
  { addr: 'E106.6', label: '', info: '' },
  { addr: 'E106.7', label: '', info: '' },
  { addr: 'E107.0', label: '', info: '' },
  { addr: 'E107.1', label: '', info: '' },
  { addr: 'E107.2', label: '', info: '' },
  { addr: 'E107.3', label: '', info: '' },
  { addr: 'E107.4', label: '', info: '' },
  { addr: 'E107.5', label: '', info: '' },
  { addr: 'E107.6', label: '', info: '' },
  { addr: 'E107.7', label: '', info: '' }
]
export const inputs3 = [
  { addr: 'E110.0', label: '', info: '' },
  { addr: 'E110.1', label: '', info: '' },
  { addr: 'E110.2', label: '', info: '' },
  { addr: 'E110.3', label: '', info: '' },
  { addr: 'E110.4', label: '', info: '' },
  { addr: 'E110.5', label: '', info: '' },
  { addr: 'E110.6', label: '', info: '' },
  { addr: 'E110.7', label: '', info: '' },
  { addr: 'E111.0', label: '', info: '' },
  { addr: 'E111.1', label: '', info: '' },
  { addr: 'E111.2', label: '', info: '' },
  { addr: 'E111.3', label: '', info: '' },
  { addr: 'E111.4', label: '', info: '' },
  { addr: 'E111.5', label: '', info: '' },
  { addr: 'E111.6', label: '', info: '' },
  { addr: 'E111.7', label: '', info: '' }
]
export const inputs4 = [
  { addr: 'E200.0', label: '', info: '' },
  { addr: 'E200.1', label: '', info: '' },
  { addr: 'E200.2', label: '', info: '' },
  { addr: 'E200.3', label: '', info: '' },
  { addr: 'E200.4', label: '', info: '' },
  { addr: 'E200.5', label: '', info: '' },
  { addr: 'E200.6', label: '', info: '' },
  { addr: 'E200.7', label: '', info: '' },
  { addr: 'E201.0', label: '', info: '' },
  { addr: 'E201.1', label: '', info: '' },
  { addr: 'E201.2', label: '', info: '' },
  { addr: 'E201.3', label: '', info: '' },
  { addr: 'E201.4', label: '', info: '' },
  { addr: 'E201.5', label: '', info: '' },
  { addr: 'E201.6', label: '', info: '' },
  { addr: 'E201.7', label: '', info: '' },
  { addr: 'E202.0', label: '', info: '' },
  { addr: 'E202.1', label: '', info: '' },
  { addr: 'E202.2', label: '', info: '' },
  { addr: 'E202.3', label: '', info: '' },
  { addr: 'E202.4', label: '', info: '' },
  { addr: 'E202.5', label: '', info: '' },
  { addr: 'E202.6', label: '', info: '' },
  { addr: 'E202.7', label: '', info: '' },
  { addr: 'E203.0', label: '', info: '' },
  { addr: 'E203.1', label: '', info: '' },
  { addr: 'E203.2', label: '', info: '' },
  { addr: 'E203.3', label: '', info: '' },
  { addr: 'E203.4', label: '', info: '' },
  { addr: 'E203.5', label: '', info: '' },
  { addr: 'E203.6', label: '', info: '' },
  { addr: 'E203.7', label: '', info: '' },
  { addr: 'E204.0', label: '', info: '' },
  { addr: 'E204.1', label: '', info: '' },
  { addr: 'E204.2', label: '', info: '' },
  { addr: 'E204.3', label: '', info: '' },
  { addr: 'E204.4', label: '', info: '' },
  { addr: 'E204.5', label: '', info: '' },
  { addr: 'E204.6', label: '', info: '' },
  { addr: 'E204.7', label: '', info: '' },
  { addr: 'E205.0', label: '', info: '' },
  { addr: 'E205.1', label: '', info: '' },
  { addr: 'E205.2', label: '', info: '' },
  { addr: 'E205.3', label: '', info: '' },
  { addr: 'E205.4', label: '', info: '' },
  { addr: 'E205.5', label: '', info: '' },
  { addr: 'E205.6', label: '', info: '' },
  { addr: 'E205.7', label: '', info: '' },
  { addr: 'E206.0', label: '', info: '' },
  { addr: 'E206.1', label: '', info: '' },
  { addr: 'E206.2', label: '', info: '' },
  { addr: 'E206.3', label: '', info: '' },
  { addr: 'E206.4', label: '', info: '' },
  { addr: 'E206.5', label: '', info: '' },
  { addr: 'E206.6', label: '', info: '' },
  { addr: 'E206.7', label: '', info: '' },
  { addr: 'E207.0', label: '', info: '' },
  { addr: 'E207.1', label: '', info: '' },
  { addr: 'E207.2', label: '', info: '' },
  { addr: 'E207.3', label: '', info: '' },
  { addr: 'E207.4', label: '', info: '' },
  { addr: 'E207.5', label: '', info: '' },
  { addr: 'E207.6', label: '', info: '' },
  { addr: 'E207.7', label: '', info: '' }
]
export const inputs5 = [
  { addr: 'E210.0', label: '', info: '' },
  { addr: 'E210.1', label: '', info: '' },
  { addr: 'E210.2', label: '', info: '' },
  { addr: 'E210.3', label: '', info: '' },
  { addr: 'E210.4', label: '', info: '' },
  { addr: 'E210.5', label: '', info: '' },
  { addr: 'E210.6', label: '', info: '' },
  { addr: 'E210.7', label: '', info: '' },
  { addr: 'E211.0', label: '', info: '' },
  { addr: 'E211.1', label: '', info: '' },
  { addr: 'E211.2', label: '', info: '' },
  { addr: 'E211.3', label: '', info: '' },
  { addr: 'E211.4', label: '', info: '' },
  { addr: 'E211.5', label: '', info: '' },
  { addr: 'E211.6', label: '', info: '' },
  { addr: 'E211.7', label: '', info: '' }
]
export const inputs6 = [
  { addr: 'E300.0', label: '', info: '' },
  { addr: 'E300.1', label: '', info: '' },
  { addr: 'E300.2', label: '', info: '' },
  { addr: 'E300.3', label: '', info: '' },
  { addr: 'E300.4', label: '', info: '' },
  { addr: 'E300.5', label: '', info: '' },
  { addr: 'E300.6', label: '', info: '' },
  { addr: 'E300.7', label: '', info: '' },
  { addr: 'E301.0', label: '', info: '' },
  { addr: 'E301.1', label: '', info: '' },
  { addr: 'E301.2', label: '', info: '' },
  { addr: 'E301.3', label: '', info: '' },
  { addr: 'E301.4', label: '', info: '' },
  { addr: 'E301.5', label: '', info: '' },
  { addr: 'E301.6', label: '', info: '' },
  { addr: 'E301.7', label: '', info: '' },
  { addr: 'E302.0', label: '', info: '' },
  { addr: 'E302.1', label: '', info: '' },
  { addr: 'E302.2', label: '', info: '' },
  { addr: 'E302.3', label: '', info: '' },
  { addr: 'E302.4', label: '', info: '' },
  { addr: 'E302.5', label: '', info: '' },
  { addr: 'E302.6', label: '', info: '' },
  { addr: 'E302.7', label: '', info: '' },
  { addr: 'E303.0', label: '', info: '' },
  { addr: 'E303.1', label: '', info: '' },
  { addr: 'E303.2', label: '', info: '' },
  { addr: 'E303.3', label: '', info: '' },
  { addr: 'E303.4', label: '', info: '' },
  { addr: 'E303.5', label: '', info: '' },
  { addr: 'E303.6', label: '', info: '' },
  { addr: 'E303.7', label: '', info: '' },
  { addr: 'E304.0', label: '', info: '' },
  { addr: 'E304.1', label: '', info: '' },
  { addr: 'E304.2', label: '', info: '' },
  { addr: 'E304.3', label: '', info: '' },
  { addr: 'E304.4', label: '', info: '' },
  { addr: 'E304.5', label: '', info: '' },
  { addr: 'E304.6', label: '', info: '' },
  { addr: 'E304.7', label: '', info: '' },
  { addr: 'E305.0', label: '', info: '' },
  { addr: 'E305.1', label: '', info: '' },
  { addr: 'E305.2', label: '', info: '' },
  { addr: 'E305.3', label: '', info: '' },
  { addr: 'E305.4', label: '', info: '' },
  { addr: 'E305.5', label: '', info: '' },
  { addr: 'E305.6', label: '', info: '' },
  { addr: 'E305.7', label: '', info: '' }
]
export const inputs7 = [
  { addr: 'E310.0', label: '', info: '' },
  { addr: 'E310.1', label: '', info: '' },
  { addr: 'E310.2', label: '', info: '' },
  { addr: 'E310.3', label: '', info: '' },
  { addr: 'E310.4', label: '', info: '' },
  { addr: 'E310.5', label: '', info: '' },
  { addr: 'E310.6', label: '', info: '' },
  { addr: 'E310.7', label: '', info: '' },
  { addr: 'E311.0', label: '', info: '' },
  { addr: 'E311.1', label: '', info: '' },
  { addr: 'E311.2', label: '', info: '' },
  { addr: 'E311.3', label: '', info: '' },
  { addr: 'E311.4', label: '', info: '' },
  { addr: 'E311.5', label: '', info: '' },
  { addr: 'E311.6', label: '', info: '' },
  { addr: 'E311.7', label: '', info: '' },
  { addr: 'E312.0', label: '', info: '' },
  { addr: 'E312.1', label: '', info: '' },
  { addr: 'E312.2', label: '', info: '' },
  { addr: 'E312.3', label: '', info: '' },
  { addr: 'E312.4', label: '', info: '' },
  { addr: 'E312.5', label: '', info: '' },
  { addr: 'E312.6', label: '', info: '' },
  { addr: 'E312.7', label: '', info: '' },
  { addr: 'E313.0', label: '', info: '' },
  { addr: 'E313.1', label: '', info: '' },
  { addr: 'E313.2', label: '', info: '' },
  { addr: 'E313.3', label: '', info: '' },
  { addr: 'E313.4', label: '', info: '' },
  { addr: 'E313.5', label: '', info: '' },
  { addr: 'E313.6', label: '', info: '' },
  { addr: 'E313.7', label: '', info: '' },
  { addr: 'E314.0', label: '', info: '' },
  { addr: 'E314.1', label: '', info: '' },
  { addr: 'E314.2', label: '', info: '' },
  { addr: 'E314.3', label: '', info: '' },
  { addr: 'E314.4', label: '', info: '' },
  { addr: 'E314.5', label: '', info: '' },
  { addr: 'E314.6', label: '', info: '' },
  { addr: 'E314.7', label: '', info: '' }
]
export const inputs8 = [
  { addr: 'E400.0', label: '', info: '' },
  { addr: 'E400.1', label: '', info: '' },
  { addr: 'E400.2', label: '', info: '' },
  { addr: 'E400.3', label: '', info: '' },
  { addr: 'E400.4', label: '', info: '' },
  { addr: 'E400.5', label: '', info: '' },
  { addr: 'E400.6', label: '', info: '' },
  { addr: 'E400.7', label: '', info: '' },
  { addr: 'E401.0', label: '', info: '' },
  { addr: 'E401.1', label: '', info: '' },
  { addr: 'E401.2', label: '', info: '' },
  { addr: 'E401.3', label: '', info: '' },
  { addr: 'E401.4', label: '', info: '' },
  { addr: 'E401.5', label: '', info: '' },
  { addr: 'E401.6', label: '', info: '' },
  { addr: 'E401.7', label: '', info: '' },
  { addr: 'E402.0', label: '', info: '' },
  { addr: 'E402.1', label: '', info: '' },
  { addr: 'E402.2', label: '', info: '' },
  { addr: 'E402.3', label: '', info: '' },
  { addr: 'E402.4', label: '', info: '' },
  { addr: 'E402.5', label: '', info: '' },
  { addr: 'E402.6', label: '', info: '' },
  { addr: 'E402.7', label: '', info: '' },
  { addr: 'E403.0', label: '', info: '' },
  { addr: 'E403.1', label: '', info: '' },
  { addr: 'E403.2', label: '', info: '' },
  { addr: 'E403.3', label: '', info: '' },
  { addr: 'E403.4', label: '', info: '' },
  { addr: 'E403.5', label: '', info: '' },
  { addr: 'E403.6', label: '', info: '' },
  { addr: 'E403.7', label: '', info: '' },
  { addr: 'E404.0', label: '', info: '' },
  { addr: 'E404.1', label: '', info: '' },
  { addr: 'E404.2', label: '', info: '' },
  { addr: 'E404.3', label: '', info: '' },
  { addr: 'E404.4', label: '', info: '' },
  { addr: 'E404.5', label: '', info: '' },
  { addr: 'E404.6', label: '', info: '' },
  { addr: 'E404.7', label: '', info: '' },
  { addr: 'E405.0', label: '', info: '' },
  { addr: 'E405.1', label: '', info: '' },
  { addr: 'E405.2', label: '', info: '' },
  { addr: 'E405.3', label: '', info: '' },
  { addr: 'E405.4', label: '', info: '' },
  { addr: 'E405.5', label: '', info: '' },
  { addr: 'E405.6', label: '', info: '' },
  { addr: 'E405.7', label: '', info: '' }
]
export const inputs9 = [
  { addr: 'E410.0', label: '', info: '' },
  { addr: 'E410.1', label: '', info: '' },
  { addr: 'E410.2', label: '', info: '' },
  { addr: 'E410.3', label: '', info: '' },
  { addr: 'E410.4', label: '', info: '' },
  { addr: 'E410.5', label: '', info: '' },
  { addr: 'E410.6', label: '', info: '' },
  { addr: 'E410.7', label: '', info: '' },
  { addr: 'E411.0', label: '', info: '' },
  { addr: 'E411.1', label: '', info: '' },
  { addr: 'E411.2', label: '', info: '' },
  { addr: 'E411.3', label: '', info: '' },
  { addr: 'E411.4', label: '', info: '' },
  { addr: 'E411.5', label: '', info: '' },
  { addr: 'E411.6', label: '', info: '' },
  { addr: 'E411.7', label: '', info: '' },
  { addr: 'E412.0', label: '', info: '' },
  { addr: 'E412.1', label: '', info: '' },
  { addr: 'E412.2', label: '', info: '' },
  { addr: 'E412.3', label: '', info: '' },
  { addr: 'E412.4', label: '', info: '' },
  { addr: 'E412.5', label: '', info: '' },
  { addr: 'E412.6', label: '', info: '' },
  { addr: 'E412.7', label: '', info: '' },
  { addr: 'E413.0', label: '', info: '' },
  { addr: 'E413.1', label: '', info: '' },
  { addr: 'E413.2', label: '', info: '' },
  { addr: 'E413.3', label: '', info: '' },
  { addr: 'E413.4', label: '', info: '' },
  { addr: 'E413.5', label: '', info: '' },
  { addr: 'E413.6', label: '', info: '' },
  { addr: 'E413.7', label: '', info: '' },
  { addr: 'E414.0', label: '', info: '' },
  { addr: 'E414.1', label: '', info: '' },
  { addr: 'E414.2', label: '', info: '' },
  { addr: 'E414.3', label: '', info: '' },
  { addr: 'E414.4', label: '', info: '' },
  { addr: 'E414.5', label: '', info: '' },
  { addr: 'E414.6', label: '', info: '' },
  { addr: 'E414.7', label: '', info: '' }
]
export const outputs1 = [
  { addr: 'E0.0', label: '', info: '' },
  { addr: 'E0.1', label: '', info: '' },
  { addr: 'E0.2', label: '', info: '' },
  { addr: 'E0.3', label: '', info: '' },
  { addr: 'E0.4', label: '', info: '' },
  { addr: 'E0.5', label: '', info: '' },
  { addr: 'E0.6', label: '', info: '' },
  { addr: 'E0.7', label: '', info: '' },
  { addr: 'E1.0', label: '', info: '' },
  { addr: 'E1.1', label: '', info: '' },
  { addr: 'E1.2', label: '', info: '' },
  { addr: 'E1.3', label: '', info: '' },
  { addr: 'E1.4', label: '', info: '' },
  { addr: 'E1.5', label: '', info: '' },
  { addr: 'E1.6', label: '', info: '' },
  { addr: 'E1.7', label: '', info: '' },
  { addr: 'E2.0', label: '', info: '' },
  { addr: 'E2.1', label: '', info: '' },
  { addr: 'E2.2', label: '', info: '' },
  { addr: 'E2.3', label: '', info: '' },
  { addr: 'E2.4', label: '', info: '' },
  { addr: 'E2.5', label: '', info: '' },
  { addr: 'E2.6', label: '', info: '' },
  { addr: 'E2.7', label: '', info: '' },
  { addr: 'E3.0', label: '', info: '' },
  { addr: 'E3.1', label: '', info: '' },
  { addr: 'E3.2', label: '', info: '' },
  { addr: 'E3.3', label: '', info: '' },
  { addr: 'E3.4', label: '', info: '' },
  { addr: 'E3.5', label: '', info: '' },
  { addr: 'E3.6', label: '', info: '' },
  { addr: 'E3.7', label: '', info: '' }
]
export const outputs2 = [
  { addr: 'E100.0', label: '', info: '' },
  { addr: 'E100.1', label: '', info: '' },
  { addr: 'E100.2', label: '', info: '' },
  { addr: 'E100.3', label: '', info: '' },
  { addr: 'E100.4', label: '', info: '' },
  { addr: 'E100.5', label: '', info: '' },
  { addr: 'E100.6', label: '', info: '' },
  { addr: 'E100.7', label: '', info: '' },
  { addr: 'E101.0', label: '', info: '' },
  { addr: 'E101.1', label: '', info: '' },
  { addr: 'E101.2', label: '', info: '' },
  { addr: 'E101.3', label: '', info: '' },
  { addr: 'E101.4', label: '', info: '' },
  { addr: 'E101.5', label: '', info: '' },
  { addr: 'E101.6', label: '', info: '' },
  { addr: 'E101.7', label: '', info: '' },
  { addr: 'E102.0', label: '', info: '' },
  { addr: 'E102.1', label: '', info: '' },
  { addr: 'E102.2', label: '', info: '' },
  { addr: 'E102.3', label: '', info: '' },
  { addr: 'E102.4', label: '', info: '' },
  { addr: 'E102.5', label: '', info: '' },
  { addr: 'E102.6', label: '', info: '' },
  { addr: 'E102.7', label: '', info: '' },
  { addr: 'E103.0', label: '', info: '' },
  { addr: 'E103.1', label: '', info: '' },
  { addr: 'E103.2', label: '', info: '' },
  { addr: 'E103.3', label: '', info: '' },
  { addr: 'E103.4', label: '', info: '' },
  { addr: 'E103.5', label: '', info: '' },
  { addr: 'E103.6', label: '', info: '' },
  { addr: 'E103.7', label: '', info: '' },
  { addr: 'E104.0', label: '', info: '' },
  { addr: 'E104.1', label: '', info: '' },
  { addr: 'E104.2', label: '', info: '' },
  { addr: 'E104.3', label: '', info: '' },
  { addr: 'E104.4', label: '', info: '' },
  { addr: 'E104.5', label: '', info: '' },
  { addr: 'E104.6', label: '', info: '' },
  { addr: 'E104.7', label: '', info: '' },
  { addr: 'E105.0', label: '', info: '' },
  { addr: 'E105.1', label: '', info: '' },
  { addr: 'E105.2', label: '', info: '' },
  { addr: 'E105.3', label: '', info: '' },
  { addr: 'E105.4', label: '', info: '' },
  { addr: 'E105.5', label: '', info: '' },
  { addr: 'E105.6', label: '', info: '' },
  { addr: 'E105.7', label: '', info: '' }
]
export const outputs3 = [
  { addr: 'E110.0', label: '', info: '' },
  { addr: 'E110.1', label: '', info: '' },
  { addr: 'E110.2', label: '', info: '' },
  { addr: 'E110.3', label: '', info: '' },
  { addr: 'E110.4', label: '', info: '' },
  { addr: 'E110.5', label: '', info: '' },
  { addr: 'E110.6', label: '', info: '' },
  { addr: 'E110.7', label: '', info: '' }
]
export const outputs4 = [
  { addr: 'E200.0', label: '', info: '' },
  { addr: 'E200.1', label: '', info: '' },
  { addr: 'E200.2', label: '', info: '' },
  { addr: 'E200.3', label: '', info: '' },
  { addr: 'E200.4', label: '', info: '' },
  { addr: 'E200.5', label: '', info: '' },
  { addr: 'E200.6', label: '', info: '' },
  { addr: 'E200.7', label: '', info: '' },
  { addr: 'E201.0', label: '', info: '' },
  { addr: 'E201.1', label: '', info: '' },
  { addr: 'E201.2', label: '', info: '' },
  { addr: 'E201.3', label: '', info: '' },
  { addr: 'E201.4', label: '', info: '' },
  { addr: 'E201.5', label: '', info: '' },
  { addr: 'E201.6', label: '', info: '' },
  { addr: 'E201.7', label: '', info: '' },
  { addr: 'E202.0', label: '', info: '' },
  { addr: 'E202.1', label: '', info: '' },
  { addr: 'E202.2', label: '', info: '' },
  { addr: 'E202.3', label: '', info: '' },
  { addr: 'E202.4', label: '', info: '' },
  { addr: 'E202.5', label: '', info: '' },
  { addr: 'E202.6', label: '', info: '' },
  { addr: 'E202.7', label: '', info: '' },
  { addr: 'E203.0', label: '', info: '' },
  { addr: 'E203.1', label: '', info: '' },
  { addr: 'E203.2', label: '', info: '' },
  { addr: 'E203.3', label: '', info: '' },
  { addr: 'E203.4', label: '', info: '' },
  { addr: 'E203.5', label: '', info: '' },
  { addr: 'E203.6', label: '', info: '' },
  { addr: 'E203.7', label: '', info: '' },
  { addr: 'E204.0', label: '', info: '' },
  { addr: 'E204.1', label: '', info: '' },
  { addr: 'E204.2', label: '', info: '' },
  { addr: 'E204.3', label: '', info: '' },
  { addr: 'E204.4', label: '', info: '' },
  { addr: 'E204.5', label: '', info: '' },
  { addr: 'E204.6', label: '', info: '' },
  { addr: 'E204.7', label: '', info: '' },
  { addr: 'E205.0', label: '', info: '' },
  { addr: 'E205.1', label: '', info: '' },
  { addr: 'E205.2', label: '', info: '' },
  { addr: 'E205.3', label: '', info: '' },
  { addr: 'E205.4', label: '', info: '' },
  { addr: 'E205.5', label: '', info: '' },
  { addr: 'E205.6', label: '', info: '' },
  { addr: 'E205.7', label: '', info: '' }
]
export const outputs5 = [
  { addr: 'E210.0', label: '', info: '' },
  { addr: 'E210.1', label: '', info: '' },
  { addr: 'E210.2', label: '', info: '' },
  { addr: 'E210.3', label: '', info: '' },
  { addr: 'E210.4', label: '', info: '' },
  { addr: 'E210.5', label: '', info: '' },
  { addr: 'E210.6', label: '', info: '' },
  { addr: 'E210.7', label: '', info: '' }
]
export const outputs6 = [
  { addr: 'A300.0', label: '', info: '' },
  { addr: 'A300.1', label: '', info: '' },
  { addr: 'A300.2', label: '', info: '' },
  { addr: 'A300.3', label: '', info: '' },
  { addr: 'A300.4', label: '', info: '' },
  { addr: 'A300.5', label: '', info: '' },
  { addr: 'A300.6', label: '', info: '' },
  { addr: 'A300.7', label: '', info: '' },
  { addr: 'A301.0', label: '', info: '' },
  { addr: 'A301.1', label: '', info: '' },
  { addr: 'A301.2', label: '', info: '' },
  { addr: 'A301.3', label: '', info: '' },
  { addr: 'A301.4', label: '', info: '' },
  { addr: 'A301.5', label: '', info: '' },
  { addr: 'A301.6', label: '', info: '' },
  { addr: 'A301.7', label: '', info: '' }
]
export const outputs7 = [
  { addr: 'A304.0', label: '', info: '' },
  { addr: 'A304.1', label: '', info: '' },
  { addr: 'A304.2', label: '', info: '' },
  { addr: 'A304.3', label: '', info: '' },
  { addr: 'A304.4', label: '', info: '' },
  { addr: 'A304.5', label: '', info: '' },
  { addr: 'A304.6', label: '', info: '' },
  { addr: 'A304.7', label: '', info: '' }
]
export const outputs8 = [
  { addr: 'A310.0', label: '', info: '' },
  { addr: 'A310.1', label: '', info: '' },
  { addr: 'A310.2', label: '', info: '' },
  { addr: 'A310.3', label: '', info: '' },
  { addr: 'A310.4', label: '', info: '' },
  { addr: 'A310.5', label: '', info: '' },
  { addr: 'A310.6', label: '', info: '' },
  { addr: 'A310.7', label: '', info: '' },
  { addr: 'A311.0', label: '', info: '' },
  { addr: 'A311.1', label: '', info: '' },
  { addr: 'A311.2', label: '', info: '' },
  { addr: 'A311.3', label: '', info: '' },
  { addr: 'A311.4', label: '', info: '' },
  { addr: 'A311.5', label: '', info: '' },
  { addr: 'A311.6', label: '', info: '' },
  { addr: 'A311.7', label: '', info: '' },
  { addr: 'A312.0', label: '', info: '' },
  { addr: 'A312.1', label: '', info: '' },
  { addr: 'A312.2', label: '', info: '' },
  { addr: 'A312.3', label: '', info: '' },
  { addr: 'A312.4', label: '', info: '' },
  { addr: 'A312.5', label: '', info: '' },
  { addr: 'A312.6', label: '', info: '' },
  { addr: 'A312.7', label: '', info: '' }
]
export const outputs9 = [
  { addr: 'A400.0', label: '', info: '' },
  { addr: 'A400.1', label: '', info: '' },
  { addr: 'A400.2', label: '', info: '' },
  { addr: 'A400.3', label: '', info: '' },
  { addr: 'A400.4', label: '', info: '' },
  { addr: 'A400.5', label: '', info: '' },
  { addr: 'A400.6', label: '', info: '' },
  { addr: 'A400.7', label: '', info: '' },
  { addr: 'A401.0', label: '', info: '' },
  { addr: 'A401.1', label: '', info: '' },
  { addr: 'A401.2', label: '', info: '' },
  { addr: 'A401.3', label: '', info: '' },
  { addr: 'A401.4', label: '', info: '' },
  { addr: 'A401.5', label: '', info: '' },
  { addr: 'A401.6', label: '', info: '' },
  { addr: 'A401.7', label: '', info: '' }
]
export const outputs10 = [
  { addr: 'A404.0', label: '', info: '' },
  { addr: 'A404.1', label: '', info: '' },
  { addr: 'A404.2', label: '', info: '' },
  { addr: 'A404.3', label: '', info: '' },
  { addr: 'A404.4', label: '', info: '' },
  { addr: 'A404.5', label: '', info: '' },
  { addr: 'A404.6', label: '', info: '' },
  { addr: 'A404.7', label: '', info: '' }
]
export const outputs11 = [
  { addr: 'A410.0', label: '', info: '' },
  { addr: 'A410.1', label: '', info: '' },
  { addr: 'A410.2', label: '', info: '' },
  { addr: 'A410.3', label: '', info: '' },
  { addr: 'A410.4', label: '', info: '' },
  { addr: 'A410.5', label: '', info: '' },
  { addr: 'A410.6', label: '', info: '' },
  { addr: 'A410.7', label: '', info: '' },
  { addr: 'A411.0', label: '', info: '' },
  { addr: 'A411.1', label: '', info: '' },
  { addr: 'A411.2', label: '', info: '' },
  { addr: 'A411.3', label: '', info: '' },
  { addr: 'A411.4', label: '', info: '' },
  { addr: 'A411.5', label: '', info: '' },
  { addr: 'A411.6', label: '', info: '' },
  { addr: 'A411.7', label: '', info: '' },
  { addr: 'A412.0', label: '', info: '' },
  { addr: 'A412.1', label: '', info: '' },
  { addr: 'A412.2', label: '', info: '' },
  { addr: 'A412.3', label: '', info: '' },
  { addr: 'A412.4', label: '', info: '' },
  { addr: 'A412.5', label: '', info: '' },
  { addr: 'A412.6', label: '', info: '' },
  { addr: 'A412.7', label: '', info: '' }
]
export const merkers1 = [
  { addr: 'M0.0', label: '', info: '' },
  { addr: 'M0.1', label: '', info: '' },
  { addr: 'M0.2', label: '', info: '' },
  { addr: 'M0.3', label: '', info: '' },
  { addr: 'M0.4', label: '', info: '' },
  { addr: 'M0.5', label: '', info: '' },
  { addr: 'M0.6', label: '', info: '' },
  { addr: 'M0.7', label: '', info: '' },
  { addr: 'M1.0', label: '', info: '' },
  { addr: 'M1.1', label: '', info: '' },
  { addr: 'M1.2', label: '', info: '' },
  { addr: 'M1.3', label: '', info: '' },
  { addr: 'M1.4', label: '', info: '' },
  { addr: 'M1.5', label: '', info: '' },
  { addr: 'M1.6', label: '', info: '' },
  { addr: 'M1.7', label: '', info: '' },
  { addr: 'M2.0', label: '', info: '' },
  { addr: 'M2.1', label: '', info: '' },
  { addr: 'M2.2', label: '', info: '' },
  { addr: 'M2.3', label: '', info: '' },
  { addr: 'M2.4', label: '', info: '' },
  { addr: 'M2.5', label: '', info: '' },
  { addr: 'M2.6', label: '', info: '' },
  { addr: 'M2.7', label: '', info: '' },
  { addr: 'M3.0', label: '', info: '' },
  { addr: 'M3.1', label: '', info: '' },
  { addr: 'M3.2', label: '', info: '' },
  { addr: 'M3.3', label: '', info: '' },
  { addr: 'M3.4', label: '', info: '' },
  { addr: 'M3.5', label: '', info: '' },
  { addr: 'M3.6', label: '', info: '' },
  { addr: 'M3.7', label: '', info: '' },
  { addr: 'M4.0', label: '', info: '' },
  { addr: 'M4.1', label: '', info: '' },
  { addr: 'M4.2', label: '', info: '' },
  { addr: 'M4.3', label: '', info: '' },
  { addr: 'M4.4', label: '', info: '' },
  { addr: 'M4.5', label: '', info: '' },
  { addr: 'M4.6', label: '', info: '' },
  { addr: 'M4.7', label: '', info: '' },
  { addr: 'M5.0', label: '', info: '' },
  { addr: 'M5.1', label: '', info: '' },
  { addr: 'M5.2', label: '', info: '' },
  { addr: 'M5.3', label: '', info: '' },
  { addr: 'M5.4', label: '', info: '' },
  { addr: 'M5.5', label: '', info: '' },
  { addr: 'M5.6', label: '', info: '' },
  { addr: 'M5.7', label: '', info: '' },
  { addr: 'M6.0', label: '', info: '' },
  { addr: 'M6.1', label: '', info: '' },
  { addr: 'M6.2', label: '', info: '' },
  { addr: 'M6.3', label: '', info: '' },
  { addr: 'M6.4', label: '', info: '' },
  { addr: 'M6.5', label: '', info: '' },
  { addr: 'M6.6', label: '', info: '' },
  { addr: 'M6.7', label: '', info: '' },
  { addr: 'M7.0', label: '', info: '' },
  { addr: 'M7.1', label: '', info: '' },
  { addr: 'M7.2', label: '', info: '' },
  { addr: 'M7.3', label: '', info: '' },
  { addr: 'M7.4', label: '', info: '' },
  { addr: 'M7.5', label: '', info: '' },
  { addr: 'M7.6', label: '', info: '' },
  { addr: 'M7.7', label: '', info: '' }
]
export const alarms1 = [
  { class: 'EU', label: 'AL1', info: 'Hoisting motor time out' },
  { class: 'EU', label: 'AL2', info: 'AL2' },
  { class: 'EU', label: 'AL3', info: '' },
  { class: 'EU', label: 'AL4', info: '' },
  { class: 'EU', label: 'AL5', info: '' },
  { class: 'EU', label: 'AL6', info: '' },
  { class: 'EU', label: 'AL7', info: '' },
  { class: 'EU', label: 'AL8', info: '' },
  { class: 'EU', label: 'AL9', info: '' },
  { class: 'EU', label: 'AL10', info: '' },
  { class: 'EU', label: 'AL11', info: '' },
  { class: 'EU', label: 'AL12', info: '' },
  { class: 'EU', label: 'AL13', info: '' },
  { class: 'EU', label: 'AL14', info: '' },
  { class: 'EU', label: 'AL15', info: '' },
  { class: 'EU', label: 'AL16', info: '' },
  { class: 'EU', label: 'AL17', info: '' },
  { class: 'EU', label: 'AL18', info: '' },
  { class: 'EU', label: 'AL19', info: '' },
  { class: 'EU', label: 'AL20', info: '' },
  { class: 'EU', label: 'AL21', info: '' },
  { class: 'EU', label: 'AL22', info: '' },
  { class: 'EU', label: 'AL23', info: '' },
  { class: 'EU', label: 'AL24', info: '' },
  { class: 'EU', label: 'AL25', info: '' },
  { class: 'EU', label: 'AL26', info: '' },
  { class: 'EU', label: 'AL27', info: '' },
  { class: 'EU', label: 'AL28', info: '' },
  { class: 'EU', label: 'AL29', info: '' },
  { class: 'EU', label: 'AL30', info: '' },
  { class: 'EU', label: 'AL31', info: '' },
  { class: 'EU', label: 'AL32', info: '' },
  { class: 'EU', label: 'AL33', info: '' },
  { class: 'EU', label: 'AL34', info: '' },
  { class: 'EU', label: 'AL35', info: '' },
  { class: 'EU', label: 'AL36', info: '' },
  { class: 'EU', label: 'AL37', info: '' },
  { class: 'EU', label: 'AL38', info: '' },
  { class: 'EU', label: 'AL39', info: '' },
  { class: 'EU', label: 'AL40', info: '' },
  { class: 'EU', label: 'AL41', info: '' },
  { class: 'EU', label: 'AL42', info: '' },
  { class: 'EU', label: 'AL43', info: '' },
  { class: 'EU', label: 'AL44', info: '' },
  { class: 'EU', label: 'AL45', info: '' },
  { class: 'EU', label: 'AL46', info: '' },
  { class: 'EU', label: 'AL47', info: '' },
  { class: 'EU', label: 'AL48', info: '' },
  { class: 'EU', label: 'AL49', info: '' },
  { class: 'EU', label: 'AL50', info: '' },
  { class: 'EU', label: 'AL51', info: '' },
  { class: 'EU', label: 'AL52', info: '' },
  { class: 'EU', label: 'AL53', info: '' },
  { class: 'EU', label: 'AL54', info: '' },
  { class: 'EU', label: 'AL55', info: '' },
  { class: 'EU', label: 'AL56', info: '' },
  { class: 'EU', label: 'AL57', info: '' },
  { class: 'EU', label: 'AL58', info: '' },
  { class: 'EU', label: 'AL59', info: '' },
  { class: 'EU', label: 'AL60', info: '' },
  { class: 'EU', label: 'AL61', info: '' },
  { class: 'EU', label: 'AL62', info: '' },
  { class: 'EU', label: 'AL63', info: '' },
  { class: 'EU', label: 'AL64', info: 'AL64' }
]
