export const devices = [
  'Operator',
  'Elevator 1 (S)',
  'Elevator 2 (N)',
  'Elevator 3 (E)',
  'Elevator 4 (W)'
]

export const modes = [
  '---',
  'Data Edit',
  'Data Read',
  'Emergency 1',
  'Emergency 2',
  'Map Edit',
  'Step by Step',
  'Preset',
  'Automatic'
]

export const operations = [
  '---',
  'Alarm on',
  'Alarm off',
  'Switch function mode',
  'Card PIN code changed',
  'Stall in',
  'Stall out',
  'Shuffle in',
  'Shuffle out',
  '---',
  'Exit request',
  'Entry request'
]

export const measures = [
  'Laser V1',
  'Laser V2',
  'Encoder H',
  'Encoder R',
  'Laser V1',
  'Laser V2',
  'Encoder H',
  'Encoder R',
  'Laser V1',
  'Laser V2',
  'Laser H1',
  'Laser H2',
  'Laser V1',
  'Laser V2',
  'Laser H1',
  'Laser H2'
]

export const inputs1 = [
  { addr: 'E0.0', label: 'A', info: '' },
  { addr: 'E0.1', label: 'B', info: '' },
  { addr: 'E0.2', label: 'C', info: '' },
  { addr: 'E0.3', label: 'D', info: '' },
  { addr: 'E0.4', label: 'STR', info: '' },
  { addr: 'E0.5', label: 'OK', info: '' },
  { addr: 'E0.6', label: 'DAT', info: '' },
  { addr: 'E0.7', label: 'SPR', info: '' },
  { addr: 'E1.0', label: 'A', info: '' },
  { addr: 'E1.1', label: 'B', info: '' },
  { addr: 'E1.2', label: 'C', info: '' },
  { addr: 'E1.3', label: 'D', info: '' },
  { addr: 'E1.4', label: 'STR', info: '' },
  { addr: 'E1.5', label: 'OK', info: '' },
  { addr: 'E1.6', label: 'DAT', info: '' },
  { addr: 'E1.7', label: 'SPR', info: '' },
  { addr: 'E2.0', label: 'A', info: '' },
  { addr: 'E2.1', label: 'B', info: '' },
  { addr: 'E2.2', label: 'C', info: '' },
  { addr: 'E2.3', label: 'D', info: '' },
  { addr: 'E2.4', label: 'STR', info: '' },
  { addr: 'E2.5', label: 'OK', info: '' },
  { addr: 'E2.6', label: 'DAT', info: '' },
  { addr: 'E2.7', label: 'RSI', info: '' },
  { addr: 'E3.0', label: 'A', info: '' },
  { addr: 'E3.1', label: 'B', info: '' },
  { addr: 'E3.2', label: 'C', info: '' },
  { addr: 'E3.3', label: 'D', info: '' },
  { addr: 'E3.4', label: 'STR', info: '' },
  { addr: 'E3.5', label: 'OK', info: '' },
  { addr: 'E3.6', label: 'DAT', info: '' },
  { addr: 'E3.7', label: '', info: '' },
  { addr: 'E4.0', label: 'SFA', info: '' },
  { addr: 'E4.1', label: 'SFB', info: '' },
  { addr: 'E4.2', label: 'SFT1', info: '' },
  { addr: 'E4.3', label: 'SFT2', info: '' },
  { addr: 'E4.4', label: 'STC', info: '' },
  { addr: 'E4.5', label: 'STC', info: '' },
  { addr: 'E4.6', label: '', info: '' },
  { addr: 'E4.7', label: 'FE3', info: '' },
  { addr: 'E5.0', label: '', info: '' },
  { addr: 'E5.1', label: '', info: '' },
  { addr: 'E5.2', label: '', info: '' },
  { addr: 'E5.3', label: '', info: '' },
  { addr: 'E5.4', label: '', info: '' },
  { addr: 'E5.5', label: '', info: '' },
  { addr: 'E5.6', label: '', info: '' },
  { addr: 'E5.7', label: '', info: '' }
]
export const inputs2 = [
  { addr: 'E100.0', label: 'A', info: 'Hex keyboard (A)' },
  { addr: 'E100.1', label: 'B', info: 'Hex keyboard (B)' },
  { addr: 'E100.2', label: 'C', info: 'Hex keyboard (C)' },
  { addr: 'E100.3', label: 'D', info: 'Hex keyboard (D)' },
  { addr: 'E100.4', label: 'OK', info: 'Hex keyboard (OK)' },
  { addr: 'E100.5', label: 'S2', info: 'Function mode switch' },
  { addr: 'E100.6', label: 'S2', info: 'Function mode switch' },
  { addr: 'E100.7', label: 'S2', info: 'Function mode switch' },
  { addr: 'E101.0', label: 'AMM1', info: '' },
  { addr: 'E101.1', label: 'EOM1', info: '' },
  { addr: 'E101.2', label: 'EZM1', info: '' },
  { addr: 'E101.3', label: 'AMM2', info: '' },
  { addr: 'E101.4', label: 'EOM2', info: '' },
  { addr: 'E101.5', label: 'EZM2', info: '' },
  { addr: 'E101.6', label: '', info: '' },
  { addr: 'E101.7', label: 'UC', info: '' },
  { addr: 'E102.0', label: 'AX1', info: '' },
  { addr: 'E102.1', label: 'FLDX', info: '' },
  { addr: 'E102.2', label: 'FLSX', info: '' },
  { addr: 'E102.3', label: '', info: '' },
  { addr: 'E102.4', label: 'FBDX', info: '' },
  { addr: 'E102.5', label: '', info: '' },
  { addr: 'E102.6', label: 'SFA0', info: '' },
  { addr: 'E102.7', label: 'SFA1', info: '' },
  { addr: 'E103.0', label: 'IV1', info: '' },
  { addr: 'E103.1', label: 'IV2', info: '' },
  { addr: 'E103.2', label: 'KXA', info: '' },
  { addr: 'E103.3', label: 'RSI', info: '' },
  { addr: 'E103.4', label: 'DB32', info: '' },
  { addr: 'E103.5', label: 'DBHZ', info: '' },
  { addr: 'E103.6', label: 'APE', info: '' },
  { addr: 'E103.7', label: 'FE1', info: '' },
  { addr: 'E104.0', label: 'ASH', info: '' },
  { addr: 'E104.1', label: 'AH', info: '' },
  { addr: 'E104.2', label: 'KXPE', info: '' },
  { addr: 'E104.3', label: '', info: '' },
  { addr: 'E104.4', label: 'SBK1', info: '' },
  { addr: 'E104.5', label: 'ASBK', info: '' },
  { addr: 'E104.6', label: 'RTA', info: '' },
  { addr: 'E104.7', label: 'KBA1', info: '' },
  { addr: 'E105.0', label: 'AMM3', info: '' },
  { addr: 'E105.1', label: 'EOM3', info: '' },
  { addr: 'E105.2', label: 'EZM3', info: '' },
  { addr: 'E105.3', label: 'AMM4', info: '' },
  { addr: 'E105.4', label: 'EOM4', info: '' },
  { addr: 'E105.5', label: 'EZM4', info: '' },
  { addr: 'E105.6', label: '', info: '' },
  { addr: 'E105.7', label: '', info: '' },
  { addr: 'E106.0', label: 'EZE', info: '' },
  { addr: 'E106.1', label: 'EOE', info: '' },
  { addr: 'E106.2', label: 'FBE', info: '' },
  { addr: 'E106.3', label: 'FPE', info: '' },
  { addr: 'E106.4', label: 'FDR1', info: '' },
  { addr: 'E106.5', label: 'FDL1', info: '' },
  { addr: 'E106.6', label: 'FTA1', info: '' },
  { addr: 'E106.7', label: 'FTA2', info: '' },
  { addr: 'E107.0', label: 'FTA2G0', info: '' },
  { addr: 'E107.1', label: 'FLP', info: '' },
  { addr: 'E107.2', label: 'FLA', info: '' },
  { addr: 'E107.3', label: 'FDRG0', info: '' },
  { addr: 'E107.4', label: 'FDLG0', info: '' },
  { addr: 'E107.5', label: '', info: '' },
  { addr: 'E107.6', label: 'RXL', info: '' },
  { addr: 'E107.7', label: 'RXR', info: '' }
]
export const inputs3 = [
  { addr: 'E110.0', label: 'ECA', info: '' },
  { addr: 'E110.1', label: 'ECB', info: '' },
  { addr: 'E110.2', label: 'AMC', info: '' },
  { addr: 'E110.3', label: 'EXD', info: '' },
  { addr: 'E110.4', label: 'EXH', info: '' },
  { addr: 'E110.5', label: 'ASKD', info: '' },
  { addr: 'E110.6', label: '', info: '' },
  { addr: 'E110.7', label: 'KEXPV', info: '' },
  { addr: 'E111.0', label: 'FE3', info: '' },
  { addr: 'E111.1', label: '', info: '' },
  { addr: 'E111.2', label: 'FTC', info: '' },
  { addr: 'E111.3', label: 'EFA', info: '' },
  { addr: 'E111.4', label: 'FREL', info: '' },
  { addr: 'E111.5', label: 'FRER', info: '' },
  { addr: 'E111.6', label: 'FTXV', info: '' },
  { addr: 'E111.7', label: 'FTXH', info: '' }
]
export const inputs4 = [
  { addr: 'E200.0', label: 'A', info: 'Hex keyboard (A)' },
  { addr: 'E200.1', label: 'B', info: 'Hex keyboard (B)' },
  { addr: 'E200.2', label: 'C', info: 'Hex keyboard (C)' },
  { addr: 'E200.3', label: 'D', info: 'Hex keyboard (D)' },
  { addr: 'E200.4', label: 'OK', info: 'Hex keyboard (OK)' },
  { addr: 'E200.5', label: 'S2', info: 'Function mode switch' },
  { addr: 'E200.6', label: 'S2', info: 'Function mode switch' },
  { addr: 'E200.7', label: 'S2', info: 'Function mode switch' },
  { addr: 'E201.0', label: 'AMM1', info: '' },
  { addr: 'E201.1', label: 'EOM1', info: '' },
  { addr: 'E201.2', label: 'EZM1', info: '' },
  { addr: 'E201.3', label: 'AMM2', info: '' },
  { addr: 'E201.4', label: 'EOM2', info: '' },
  { addr: 'E201.5', label: 'EZM2', info: '' },
  { addr: 'E201.6', label: '', info: '' },
  { addr: 'E201.7', label: 'UC', info: '' },
  { addr: 'E202.0', label: 'AX1', info: '' },
  { addr: 'E202.1', label: 'FLDX', info: '' },
  { addr: 'E202.2', label: 'FLSX', info: '' },
  { addr: 'E202.3', label: '', info: '' },
  { addr: 'E202.4', label: 'FBDX', info: '' },
  { addr: 'E202.5', label: '', info: '' },
  { addr: 'E202.6', label: 'SFA0', info: '' },
  { addr: 'E202.7', label: 'SFA1', info: '' },
  { addr: 'E203.0', label: 'IV1', info: '' },
  { addr: 'E203.1', label: 'IV2', info: '' },
  { addr: 'E203.2', label: 'KXA', info: '' },
  { addr: 'E203.3', label: 'RSI', info: '' },
  { addr: 'E203.4', label: 'DB32', info: '' },
  { addr: 'E203.5', label: 'DBHZ', info: '' },
  { addr: 'E203.6', label: 'APE', info: '' },
  { addr: 'E203.7', label: 'FE1', info: '' },
  { addr: 'E204.0', label: 'ASH', info: '' },
  { addr: 'E204.1', label: 'AH', info: '' },
  { addr: 'E204.2', label: 'KXPE', info: '' },
  { addr: 'E204.3', label: '', info: '' },
  { addr: 'E204.4', label: 'SBK1', info: '' },
  { addr: 'E204.5', label: 'ASBK', info: '' },
  { addr: 'E204.6', label: 'RTA', info: '' },
  { addr: 'E204.7', label: 'KBA1', info: '' },
  { addr: 'E205.0', label: 'AMM3', info: '' },
  { addr: 'E205.1', label: 'EOM3', info: '' },
  { addr: 'E205.2', label: 'EZM3', info: '' },
  { addr: 'E205.3', label: 'AMM4', info: '' },
  { addr: 'E205.4', label: 'EOM4', info: '' },
  { addr: 'E205.5', label: 'EZM4', info: '' },
  { addr: 'E205.6', label: '', info: '' },
  { addr: 'E205.7', label: '', info: '' },
  { addr: 'E206.0', label: 'EZE', info: '' },
  { addr: 'E206.1', label: 'EOE', info: '' },
  { addr: 'E206.2', label: 'FBE', info: '' },
  { addr: 'E206.3', label: 'FPE', info: '' },
  { addr: 'E206.4', label: 'FDR1', info: '' },
  { addr: 'E206.5', label: 'FDL1', info: '' },
  { addr: 'E206.6', label: 'FTA1', info: '' },
  { addr: 'E206.7', label: 'FTA2', info: '' },
  { addr: 'E207.0', label: 'FTA2G0', info: '' },
  { addr: 'E207.1', label: 'FLP', info: '' },
  { addr: 'E207.2', label: 'FLA', info: '' },
  { addr: 'E207.3', label: 'FDRG0', info: '' },
  { addr: 'E207.4', label: 'FDLG0', info: '' },
  { addr: 'E207.5', label: '', info: '' },
  { addr: 'E207.6', label: 'RXL', info: '' },
  { addr: 'E207.7', label: 'RXR', info: '' }
]
export const inputs5 = [
  { addr: 'E210.0', label: 'ECA', info: '' },
  { addr: 'E210.1', label: 'ECB', info: '' },
  { addr: 'E210.2', label: 'AMC', info: '' },
  { addr: 'E210.3', label: 'EXD', info: '' },
  { addr: 'E210.4', label: 'EXH', info: '' },
  { addr: 'E210.5', label: 'ASKD', info: '' },
  { addr: 'E210.6', label: '', info: '' },
  { addr: 'E210.7', label: 'KEXPV', info: '' },
  { addr: 'E211.0', label: 'FE3', info: '' },
  { addr: 'E211.1', label: '', info: '' },
  { addr: 'E211.2', label: 'FTC', info: '' },
  { addr: 'E211.3', label: 'EFA', info: '' },
  { addr: 'E211.4', label: 'FREL', info: '' },
  { addr: 'E211.5', label: 'FRER', info: '' },
  { addr: 'E211.6', label: 'FTXV', info: '' },
  { addr: 'E211.7', label: 'FTXH', info: '' }
]
export const inputs6 = [
  { addr: 'E300.0', label: 'A', info: 'Hex keyboard (A)' },
  { addr: 'E300.1', label: 'B', info: 'Hex keyboard (B)' },
  { addr: 'E300.2', label: 'C', info: 'Hex keyboard (C)' },
  { addr: 'E300.3', label: 'D', info: 'Hex keyboard (D)' },
  { addr: 'E300.4', label: 'OK', info: 'Hex keyboard (OK)' },
  { addr: 'E300.5', label: 'S2', info: 'Function mode switch' },
  { addr: 'E300.6', label: 'S2', info: 'Function mode switch' },
  { addr: 'E300.7', label: 'S2', info: 'Function mode switch' },
  { addr: 'E301.0', label: 'FE1', info: '' },
  { addr: 'E301.1', label: 'IV1', info: '' },
  { addr: 'E301.2', label: 'TJ1', info: '' },
  { addr: 'E301.3', label: 'RSI', info: '' },
  { addr: 'E301.4', label: 'SA', info: '' },
  { addr: 'E301.5', label: '', info: '' },
  { addr: 'E301.6', label: '', info: '' },
  { addr: 'E301.7', label: 'UC', info: '' },
  { addr: 'E302.0', label: '', info: '' },
  { addr: 'E302.1', label: '', info: '' },
  { addr: 'E302.2', label: '', info: '' },
  { addr: 'E302.3', label: '', info: '' },
  { addr: 'E302.4', label: 'FDBK', info: '' },
  { addr: 'E302.5', label: 'ASBK', info: '' },
  { addr: 'E302.6', label: 'RTA', info: '' },
  { addr: 'E302.7', label: '', info: '' },
  { addr: 'E303.0', label: '', info: '' },
  { addr: 'E303.1', label: '', info: '' },
  { addr: 'E303.2', label: '', info: '' },
  { addr: 'E303.3', label: '', info: '' },
  { addr: 'E303.4', label: '', info: '' },
  { addr: 'E303.5', label: '', info: '' },
  { addr: 'E303.6', label: '', info: '' },
  { addr: 'E303.7', label: '', info: '' },
  { addr: 'E304.0', label: 'AGK', info: '' },
  { addr: 'E304.1', label: 'ACR', info: '' },
  { addr: 'E304.2', label: 'TCR', info: '' },
  { addr: 'E304.3', label: 'FE3', info: '' },
  { addr: 'E304.4', label: 'DB32', info: '' },
  { addr: 'E304.5', label: 'DBHZ', info: '' },
  { addr: 'E304.6', label: 'KLK', info: '' },
  { addr: 'E304.7', label: '', info: '' },
  { addr: 'E305.0', label: '', info: '' },
  { addr: 'E305.1', label: '', info: '' },
  { addr: 'E305.2', label: 'AMM', info: '' },
  { addr: 'E305.3', label: 'EOM', info: '' },
  { addr: 'E305.4', label: 'EZM', info: '' },
  { addr: 'E305.5', label: 'EMC', info: '' },
  { addr: 'E305.6', label: '', info: '' },
  { addr: 'E305.7', label: '', info: '' }
]
export const inputs7 = [
  { addr: 'E310.0', label: 'A', info: 'Hex keyboard (A)' },
  { addr: 'E310.1', label: 'B', info: 'Hex keyboard (B)' },
  { addr: 'E310.2', label: 'C', info: 'Hex keyboard (C)' },
  { addr: 'E310.3', label: 'D', info: 'Hex keyboard (D)' },
  { addr: 'E310.4', label: 'OK', info: 'Hex keyboard (OK)' },
  { addr: 'E310.5', label: 'S2', info: 'Function mode switch' },
  { addr: 'E310.6', label: 'S2', info: 'Function mode switch' },
  { addr: 'E310.7', label: 'S2', info: 'Function mode switch' },
  { addr: 'E311.0', label: 'FE4', info: '' },
  { addr: 'E311.1', label: '', info: '' },
  { addr: 'E311.2', label: '', info: '' },
  { addr: 'E311.3', label: 'EM', info: '' },
  { addr: 'E311.4', label: '', info: '' },
  { addr: 'E311.5', label: '', info: '' },
  { addr: 'E311.6', label: 'FTXV', info: '' },
  { addr: 'E311.7', label: 'FTXH', info: '' },
  { addr: 'E312.0', label: 'RMV', info: '' },
  { addr: 'E312.1', label: 'RMH', info: '' },
  { addr: 'E312.2', label: 'RES', info: '' },
  { addr: 'E312.3', label: 'REH', info: '' },
  { addr: 'E312.4', label: 'RCV', info: '' },
  { addr: 'E312.5', label: 'REAV', info: '' },
  { addr: 'E312.6', label: 'REAH', info: '' },
  { addr: 'E312.7', label: 'RCH', info: '' },
  { addr: 'E313.0', label: 'IV', info: '' },
  { addr: 'E313.1', label: 'TJ', info: '' },
  { addr: 'E313.2', label: 'SA', info: '' },
  { addr: 'E313.3', label: 'RSI', info: '' },
  { addr: 'E313.4', label: 'DB32', info: '' },
  { addr: 'E313.5', label: 'DBHZ', info: '' },
  { addr: 'E313.6', label: 'FTAC', info: '' },
  { addr: 'E313.7', label: 'UC', info: '' },
  { addr: 'E314.0', label: 'AF7', info: '' },
  { addr: 'E314.1', label: '', info: '' },
  { addr: 'E314.2', label: 'FTM1', info: '' },
  { addr: 'E314.3', label: 'FTM2', info: '' },
  { addr: 'E314.4', label: '', info: '' },
  { addr: 'E314.5', label: 'TCR', info: '' },
  { addr: 'E314.6', label: 'AH', info: '' },
  { addr: 'E314.7', label: 'MTC', info: '' }
]
export const inputs8 = [
  { addr: 'E400.0', label: 'A', info: 'Hex keyboard (A)' },
  { addr: 'E400.1', label: 'B', info: 'Hex keyboard (B)' },
  { addr: 'E400.2', label: 'C', info: 'Hex keyboard (C)' },
  { addr: 'E400.3', label: 'D', info: 'Hex keyboard (D)' },
  { addr: 'E400.4', label: 'OK', info: 'Hex keyboard (OK)' },
  { addr: 'E400.5', label: 'S2', info: 'Function mode switch' },
  { addr: 'E400.6', label: 'S2', info: 'Function mode switch' },
  { addr: 'E400.7', label: 'S2', info: 'Function mode switch' },
  { addr: 'E401.0', label: 'FE1', info: '' },
  { addr: 'E401.1', label: 'IV1', info: '' },
  { addr: 'E401.2', label: 'TJ1', info: '' },
  { addr: 'E401.3', label: 'RSI', info: '' },
  { addr: 'E401.4', label: 'SA', info: '' },
  { addr: 'E401.5', label: '', info: '' },
  { addr: 'E401.6', label: '', info: '' },
  { addr: 'E401.7', label: 'UC', info: '' },
  { addr: 'E402.0', label: '', info: '' },
  { addr: 'E402.1', label: '', info: '' },
  { addr: 'E402.2', label: '', info: '' },
  { addr: 'E402.3', label: '', info: '' },
  { addr: 'E402.4', label: 'FDBK', info: '' },
  { addr: 'E402.5', label: 'ASBK', info: '' },
  { addr: 'E402.6', label: 'RTA', info: '' },
  { addr: 'E402.7', label: '', info: '' },
  { addr: 'E403.0', label: '', info: '' },
  { addr: 'E403.1', label: '', info: '' },
  { addr: 'E403.2', label: '', info: '' },
  { addr: 'E403.3', label: '', info: '' },
  { addr: 'E403.4', label: '', info: '' },
  { addr: 'E403.5', label: '', info: '' },
  { addr: 'E403.6', label: '', info: '' },
  { addr: 'E403.7', label: '', info: '' },
  { addr: 'E404.0', label: 'AGK', info: '' },
  { addr: 'E404.1', label: 'ACR', info: '' },
  { addr: 'E404.2', label: 'TCR', info: '' },
  { addr: 'E404.3', label: 'FE3', info: '' },
  { addr: 'E404.4', label: 'DB32', info: '' },
  { addr: 'E404.5', label: 'DBHZ', info: '' },
  { addr: 'E404.6', label: 'KLK', info: '' },
  { addr: 'E404.7', label: '', info: '' },
  { addr: 'E405.0', label: '', info: '' },
  { addr: 'E405.1', label: '', info: '' },
  { addr: 'E405.2', label: 'AMM', info: '' },
  { addr: 'E405.3', label: 'EOM', info: '' },
  { addr: 'E405.4', label: 'EZM', info: '' },
  { addr: 'E405.5', label: 'EMC', info: '' },
  { addr: 'E405.6', label: '', info: '' },
  { addr: 'E405.7', label: '', info: '' }
]
export const inputs9 = [
  { addr: 'E410.0', label: 'A', info: 'Hex keyboard (A)' },
  { addr: 'E410.1', label: 'B', info: 'Hex keyboard (B)' },
  { addr: 'E410.2', label: 'C', info: 'Hex keyboard (C)' },
  { addr: 'E410.3', label: 'D', info: 'Hex keyboard (D)' },
  { addr: 'E410.4', label: 'OK', info: 'Hex keyboard (OK)' },
  { addr: 'E410.5', label: 'S2', info: 'Function mode switch' },
  { addr: 'E410.6', label: 'S2', info: 'Function mode switch' },
  { addr: 'E410.7', label: 'S2', info: 'Function mode switch' },
  { addr: 'E411.0', label: 'FE4', info: '' },
  { addr: 'E411.1', label: '', info: '' },
  { addr: 'E411.2', label: '', info: '' },
  { addr: 'E411.3', label: 'EM', info: '' },
  { addr: 'E411.4', label: '', info: '' },
  { addr: 'E411.5', label: '', info: '' },
  { addr: 'E411.6', label: 'FTXV', info: '' },
  { addr: 'E411.7', label: 'FTXH', info: '' },
  { addr: 'E412.0', label: 'RMV', info: '' },
  { addr: 'E412.1', label: 'RMH', info: '' },
  { addr: 'E412.2', label: 'RES', info: '' },
  { addr: 'E412.3', label: 'REH', info: '' },
  { addr: 'E412.4', label: 'RCV', info: '' },
  { addr: 'E412.5', label: 'REAV', info: '' },
  { addr: 'E412.6', label: 'REAH', info: '' },
  { addr: 'E412.7', label: 'RCH', info: '' },
  { addr: 'E413.0', label: 'IV', info: '' },
  { addr: 'E413.1', label: 'TJ', info: '' },
  { addr: 'E413.2', label: 'SA', info: '' },
  { addr: 'E413.3', label: 'RSI', info: '' },
  { addr: 'E413.4', label: 'DB32', info: '' },
  { addr: 'E413.5', label: 'DBHZ', info: '' },
  { addr: 'E413.6', label: 'FTAC', info: '' },
  { addr: 'E413.7', label: 'UC', info: '' },
  { addr: 'E414.0', label: 'AF7', info: '' },
  { addr: 'E414.1', label: '', info: '' },
  { addr: 'E414.2', label: 'FTM1', info: '' },
  { addr: 'E414.3', label: 'FTM2', info: '' },
  { addr: 'E414.4', label: '', info: '' },
  { addr: 'E414.5', label: 'TCR', info: '' },
  { addr: 'E414.6', label: 'AH', info: '' },
  { addr: 'E414.7', label: 'MTC', info: '' }
]
export const outputs1 = [
  { addr: 'E0.0', label: 'LK', info: '' },
  { addr: 'E0.1', label: 'LE', info: '' },
  { addr: 'E0.2', label: 'LB', info: '' },
  { addr: 'E0.3', label: 'RDY', info: '' },
  { addr: 'E0.4', label: 'RST', info: '' },
  { addr: 'E0.5', label: '', info: '' },
  { addr: 'E0.6', label: 'LA', info: '' },
  { addr: 'E0.7', label: 'RB', info: '' },
  { addr: 'E1.0', label: 'LK', info: '' },
  { addr: 'E1.1', label: 'LE', info: '' },
  { addr: 'E1.2', label: 'LB', info: '' },
  { addr: 'E1.3', label: 'RDY', info: '' },
  { addr: 'E1.4', label: 'RST', info: '' },
  { addr: 'E1.5', label: '', info: '' },
  { addr: 'E1.6', label: 'LA', info: '' },
  { addr: 'E1.7', label: 'LB', info: '' },
  { addr: 'E2.0', label: 'LK', info: '' },
  { addr: 'E2.1', label: 'LE', info: '' },
  { addr: 'E2.2', label: 'LB', info: '' },
  { addr: 'E2.3', label: 'RDY', info: '' },
  { addr: 'E2.4', label: 'RST', info: '' },
  { addr: 'E2.5', label: '', info: '' },
  { addr: 'E2.6', label: 'LT1', info: '' },
  { addr: 'E2.7', label: 'LT2', info: '' },
  { addr: 'E3.0', label: 'LK', info: '' },
  { addr: 'E3.1', label: 'LE', info: '' },
  { addr: 'E3.2', label: 'LB', info: '' },
  { addr: 'E3.3', label: 'RDY', info: '' },
  { addr: 'E3.4', label: 'RST', info: '' },
  { addr: 'E3.5', label: '', info: '' },
  { addr: 'E3.6', label: '', info: '' },
  { addr: 'E3.7', label: '', info: '' }
]
export const outputs2 = [
  { addr: 'E100.0', label: 'SBK1', info: '' },
  { addr: 'E100.1', label: 'KBA1', info: '' },
  { addr: 'E100.2', label: 'KBA2', info: '' },
  { addr: 'E100.3', label: 'KXPE', info: '' },
  { addr: 'E100.4', label: 'KQA', info: '' },
  { addr: 'E100.5', label: 'TD', info: '' },
  { addr: 'E100.6', label: 'T10', info: '' },
  { addr: 'E100.7', label: 'KEM', info: '' },
  { addr: 'E101.0', label: 'L1', info: '' },
  { addr: 'E101.1', label: 'L2', info: '' },
  { addr: 'E101.2', label: 'L3', info: '' },
  { addr: 'E101.3', label: 'L4', info: '' },
  { addr: 'E101.4', label: 'L5', info: '' },
  { addr: 'E101.5', label: 'RFE', info: '' },
  { addr: 'E101.6', label: 'RLN', info: '' },
  { addr: 'E101.7', label: '', info: '' },
  { addr: 'E102.0', label: 'SMA1', info: '' },
  { addr: 'E102.1', label: 'SMB1', info: '' },
  { addr: 'E102.2', label: 'SMA2', info: '' },
  { addr: 'E102.3', label: 'SMB2', info: '' },
  { addr: 'E102.4', label: 'SMA3', info: '' },
  { addr: 'E102.5', label: 'SMB3', info: '' },
  { addr: 'E102.6', label: 'SMA4', info: '' },
  { addr: 'E102.7', label: 'SMB4', info: '' },
  { addr: 'E103.0', label: 'SXU1', info: '' },
  { addr: 'E103.1', label: 'SXD1', info: '' },
  { addr: 'E103.2', label: '', info: '' },
  { addr: 'E103.3', label: '', info: '' },
  { addr: 'E103.4', label: '', info: '' },
  { addr: 'E103.5', label: 'LC1', info: '' },
  { addr: 'E103.6', label: 'LA', info: '' },
  { addr: 'E103.7', label: 'LC', info: '' },
  { addr: 'E104.0', label: 'A', info: '' },
  { addr: 'E104.1', label: 'B', info: '' },
  { addr: 'E104.2', label: 'C', info: '' },
  { addr: 'E104.3', label: 'D', info: '' },
  { addr: 'E104.4', label: 'AD1', info: '' },
  { addr: 'E104.5', label: 'AD2', info: '' },
  { addr: 'E104.6', label: 'AD3', info: '' },
  { addr: 'E104.7', label: 'STR', info: '' },
  { addr: 'E105.0', label: 'SPE', info: '' },
  { addr: 'E105.1', label: '', info: '' },
  { addr: 'E105.2', label: '', info: '' },
  { addr: 'E105.3', label: '', info: '' },
  { addr: 'E105.4', label: '', info: '' },
  { addr: 'E105.5', label: 'SBK2', info: '' },
  { addr: 'E105.6', label: 'SZE', info: '' },
  { addr: 'E105.7', label: 'SOE', info: '' }
]
export const outputs3 = [
  { addr: 'E110.0', label: 'SCA', info: '' },
  { addr: 'E110.1', label: 'SCB', info: '' },
  { addr: 'E110.2', label: 'T10F', info: '' },
  { addr: 'E110.3', label: 'TDF', info: '' },
  { addr: 'E110.4', label: '', info: '' },
  { addr: 'E110.5', label: '', info: '' },
  { addr: 'E110.6', label: '', info: '' },
  { addr: 'E110.7', label: '', info: '' }
]
export const outputs4 = [
  { addr: 'E200.0', label: 'SBK1', info: '' },
  { addr: 'E200.1', label: 'KBA1', info: '' },
  { addr: 'E200.2', label: 'KBA2', info: '' },
  { addr: 'E200.3', label: 'KXPE', info: '' },
  { addr: 'E200.4', label: 'KQA', info: '' },
  { addr: 'E200.5', label: 'TD', info: '' },
  { addr: 'E200.6', label: 'T10', info: '' },
  { addr: 'E200.7', label: 'KEM', info: '' },
  { addr: 'E201.0', label: 'L1', info: '' },
  { addr: 'E201.1', label: 'L2', info: '' },
  { addr: 'E201.2', label: 'L3', info: '' },
  { addr: 'E201.3', label: 'L4', info: '' },
  { addr: 'E201.4', label: 'L5', info: '' },
  { addr: 'E201.5', label: 'RFE', info: '' },
  { addr: 'E201.6', label: 'RLN', info: '' },
  { addr: 'E201.7', label: '', info: '' },
  { addr: 'E202.0', label: 'SMA1', info: '' },
  { addr: 'E202.1', label: 'SMB1', info: '' },
  { addr: 'E202.2', label: 'SMA2', info: '' },
  { addr: 'E202.3', label: 'SMB2', info: '' },
  { addr: 'E202.4', label: 'SMA3', info: '' },
  { addr: 'E202.5', label: 'SMB3', info: '' },
  { addr: 'E202.6', label: 'SMA4', info: '' },
  { addr: 'E202.7', label: 'SMB4', info: '' },
  { addr: 'E203.0', label: 'SXU1', info: '' },
  { addr: 'E203.1', label: 'SXD1', info: '' },
  { addr: 'E203.2', label: '', info: '' },
  { addr: 'E203.3', label: '', info: '' },
  { addr: 'E203.4', label: '', info: '' },
  { addr: 'E203.5', label: 'LC1', info: '' },
  { addr: 'E203.6', label: 'LA', info: '' },
  { addr: 'E203.7', label: 'LC', info: '' },
  { addr: 'E204.0', label: 'A', info: '' },
  { addr: 'E204.1', label: 'B', info: '' },
  { addr: 'E204.2', label: 'C', info: '' },
  { addr: 'E204.3', label: 'D', info: '' },
  { addr: 'E204.4', label: 'AD1', info: '' },
  { addr: 'E204.5', label: 'AD2', info: '' },
  { addr: 'E204.6', label: 'AD3', info: '' },
  { addr: 'E204.7', label: 'STR', info: '' },
  { addr: 'E205.0', label: 'SPE', info: '' },
  { addr: 'E205.1', label: '', info: '' },
  { addr: 'E205.2', label: '', info: '' },
  { addr: 'E205.3', label: '', info: '' },
  { addr: 'E205.4', label: '', info: '' },
  { addr: 'E205.5', label: 'SBK2', info: '' },
  { addr: 'E205.6', label: 'SZE', info: '' },
  { addr: 'E205.7', label: 'SOE', info: '' }
]
export const outputs5 = [
  { addr: 'E210.0', label: 'SCA', info: '' },
  { addr: 'E210.1', label: 'SCB', info: '' },
  { addr: 'E210.2', label: 'T10F', info: '' },
  { addr: 'E210.3', label: 'TDF', info: '' },
  { addr: 'E210.4', label: '', info: '' },
  { addr: 'E210.5', label: '', info: '' },
  { addr: 'E210.6', label: '', info: '' },
  { addr: 'E210.7', label: '', info: '' }
]
export const outputs6 = [
  { addr: 'A300.0', label: 'SBK1', info: '' },
  { addr: 'A300.1', label: 'KBA', info: '' },
  { addr: 'A300.2', label: '', info: '' },
  { addr: 'A300.3', label: '', info: '' },
  { addr: 'A300.4', label: 'SBK2', info: '' },
  { addr: 'A300.5', label: 'KBA', info: '' },
  { addr: 'A300.6', label: 'LA', info: '' },
  { addr: 'A300.7', label: 'LC', info: '' },
  { addr: 'A301.0', label: 'A', info: '' },
  { addr: 'A301.1', label: 'B', info: '' },
  { addr: 'A301.2', label: 'C', info: '' },
  { addr: 'A301.3', label: 'D', info: '' },
  { addr: 'A301.4', label: 'AD1', info: '' },
  { addr: 'A301.5', label: 'AD2', info: '' },
  { addr: 'A301.6', label: 'AD3', info: '' },
  { addr: 'A301.7', label: 'STR', info: '' }
]
export const outputs7 = [
  { addr: 'A304.0', label: 'SMA', info: '' },
  { addr: 'A304.1', label: 'SMB', info: '' },
  { addr: 'A304.2', label: 'TCR', info: '' },
  { addr: 'A304.3', label: 'KSH', info: '' },
  { addr: 'A304.4', label: '', info: '' },
  { addr: 'A304.5', label: '', info: '' },
  { addr: 'A304.6', label: 'LA', info: '' },
  { addr: 'A304.7', label: '', info: '' }
]
export const outputs8 = [
  { addr: 'A310.0', label: 'A', info: '' },
  { addr: 'A310.1', label: 'B', info: '' },
  { addr: 'A310.2', label: 'C', info: '' },
  { addr: 'A310.3', label: 'D', info: '' },
  { addr: 'A310.4', label: 'AD1', info: '' },
  { addr: 'A310.5', label: 'AD2', info: '' },
  { addr: 'A310.6', label: 'AD3', info: '' },
  { addr: 'A310.7', label: 'STR', info: '' },
  { addr: 'A311.0', label: 'T10-1', info: '' },
  { addr: 'A311.1', label: 'T2', info: '' },
  { addr: 'A311.2', label: 'TRA', info: '' },
  { addr: 'A311.3', label: 'TRB', info: '' },
  { addr: 'A311.4', label: 'KCS', info: '' },
  { addr: 'A311.5', label: 'KCV', info: '' },
  { addr: 'A311.6', label: 'KCH', info: '' },
  { addr: 'A311.7', label: 'TCR', info: '' },
  { addr: 'A312.0', label: 'KBA', info: '' },
  { addr: 'A312.1', label: '', info: '' },
  { addr: 'A312.2', label: '', info: '' },
  { addr: 'A312.3', label: '', info: '' },
  { addr: 'A312.4', label: 'T10-2', info: '' },
  { addr: 'A312.5', label: 'T10-F', info: '' },
  { addr: 'A312.6', label: 'LA', info: '' },
  { addr: 'A312.7', label: 'LC', info: '' }
]
export const outputs9 = [
  { addr: 'A400.0', label: 'SBK1', info: '' },
  { addr: 'A400.1', label: 'KBA', info: '' },
  { addr: 'A400.2', label: '', info: '' },
  { addr: 'A400.3', label: '', info: '' },
  { addr: 'A400.4', label: 'SBK2', info: '' },
  { addr: 'A400.5', label: 'KBA', info: '' },
  { addr: 'A400.6', label: 'LA', info: '' },
  { addr: 'A400.7', label: 'LC', info: '' },
  { addr: 'A401.0', label: 'A', info: '' },
  { addr: 'A401.1', label: 'B', info: '' },
  { addr: 'A401.2', label: 'C', info: '' },
  { addr: 'A401.3', label: 'D', info: '' },
  { addr: 'A401.4', label: 'AD1', info: '' },
  { addr: 'A401.5', label: 'AD2', info: '' },
  { addr: 'A401.6', label: 'AD3', info: '' },
  { addr: 'A401.7', label: 'STR', info: '' }
]
export const outputs10 = [
  { addr: 'A404.0', label: 'SMA', info: '' },
  { addr: 'A404.1', label: 'SMB', info: '' },
  { addr: 'A404.2', label: 'TCR', info: '' },
  { addr: 'A404.3', label: 'KSH', info: '' },
  { addr: 'A404.4', label: '', info: '' },
  { addr: 'A404.5', label: '', info: '' },
  { addr: 'A404.6', label: 'LA', info: '' },
  { addr: 'A404.7', label: '', info: '' }
]
export const outputs11 = [
  { addr: 'A410.0', label: 'A', info: '' },
  { addr: 'A410.1', label: 'B', info: '' },
  { addr: 'A410.2', label: 'C', info: '' },
  { addr: 'A410.3', label: 'D', info: '' },
  { addr: 'A410.4', label: 'AD1', info: '' },
  { addr: 'A410.5', label: 'AD2', info: '' },
  { addr: 'A410.6', label: 'AD3', info: '' },
  { addr: 'A410.7', label: 'STR', info: '' },
  { addr: 'A411.0', label: 'T10-1', info: '' },
  { addr: 'A411.1', label: 'T2', info: '' },
  { addr: 'A411.2', label: 'TRA', info: '' },
  { addr: 'A411.3', label: 'TRB', info: '' },
  { addr: 'A411.4', label: 'KCS', info: '' },
  { addr: 'A411.5', label: 'KCV', info: '' },
  { addr: 'A411.6', label: 'KCH', info: '' },
  { addr: 'A411.7', label: 'TCR', info: '' },
  { addr: 'A412.0', label: 'KBA', info: '' },
  { addr: 'A412.1', label: '', info: '' },
  { addr: 'A412.2', label: '', info: '' },
  { addr: 'A412.3', label: '', info: '' },
  { addr: 'A412.4', label: 'T10-2', info: '' },
  { addr: 'A412.5', label: 'T10-F', info: '' },
  { addr: 'A412.6', label: 'LA', info: '' },
  { addr: 'A412.7', label: 'LC', info: '' }
]
export const merkers1 = [
  { addr: 'M0.0', label: '', info: '' },
  { addr: 'M0.1', label: '', info: '' },
  { addr: 'M0.2', label: '', info: '' },
  { addr: 'M0.3', label: '', info: '' },
  { addr: 'M0.4', label: '', info: '' },
  { addr: 'M0.5', label: '', info: '' },
  { addr: 'M0.6', label: '', info: '' },
  { addr: 'M0.7', label: '', info: '' },
  { addr: 'M1.0', label: '', info: '' },
  { addr: 'M1.1', label: '', info: '' },
  { addr: 'M1.2', label: '', info: '' },
  { addr: 'M1.3', label: '', info: '' },
  { addr: 'M1.4', label: '', info: '' },
  { addr: 'M1.5', label: '', info: '' },
  { addr: 'M1.6', label: '', info: '' },
  { addr: 'M1.7', label: '', info: '' },
  { addr: 'M2.0', label: '', info: '' },
  { addr: 'M2.1', label: '', info: '' },
  { addr: 'M2.2', label: '', info: '' },
  { addr: 'M2.3', label: '', info: '' },
  { addr: 'M2.4', label: '', info: '' },
  { addr: 'M2.5', label: '', info: '' },
  { addr: 'M2.6', label: '', info: '' },
  { addr: 'M2.7', label: '', info: '' },
  { addr: 'M3.0', label: '', info: '' },
  { addr: 'M3.1', label: '', info: '' },
  { addr: 'M3.2', label: '', info: '' },
  { addr: 'M3.3', label: '', info: '' },
  { addr: 'M3.4', label: '', info: '' },
  { addr: 'M3.5', label: '', info: '' },
  { addr: 'M3.6', label: '', info: '' },
  { addr: 'M3.7', label: '', info: '' },
  { addr: 'M4.0', label: '', info: '' },
  { addr: 'M4.1', label: '', info: '' },
  { addr: 'M4.2', label: '', info: '' },
  { addr: 'M4.3', label: '', info: '' },
  { addr: 'M4.4', label: '', info: '' },
  { addr: 'M4.5', label: '', info: '' },
  { addr: 'M4.6', label: '', info: '' },
  { addr: 'M4.7', label: '', info: '' },
  { addr: 'M5.0', label: '', info: '' },
  { addr: 'M5.1', label: '', info: '' },
  { addr: 'M5.2', label: '', info: '' },
  { addr: 'M5.3', label: '', info: '' },
  { addr: 'M5.4', label: '', info: '' },
  { addr: 'M5.5', label: '', info: '' },
  { addr: 'M5.6', label: '', info: '' },
  { addr: 'M5.7', label: '', info: '' },
  { addr: 'M6.0', label: '', info: '' },
  { addr: 'M6.1', label: '', info: '' },
  { addr: 'M6.2', label: '', info: '' },
  { addr: 'M6.3', label: '', info: '' },
  { addr: 'M6.4', label: '', info: '' },
  { addr: 'M6.5', label: '', info: '' },
  { addr: 'M6.6', label: '', info: '' },
  { addr: 'M6.7', label: '', info: '' },
  { addr: 'M7.0', label: '', info: '' },
  { addr: 'M7.1', label: '', info: '' },
  { addr: 'M7.2', label: '', info: '' },
  { addr: 'M7.3', label: '', info: '' },
  { addr: 'M7.4', label: '', info: '' },
  { addr: 'M7.5', label: '', info: '' },
  { addr: 'M7.6', label: '', info: '' },
  { addr: 'M7.7', label: '', info: '' }
]
export const alarms1 = [
  { class: 'EL1', label: 'AL1', info: 'Hoisting motor time out' },
  { class: 'EL1', label: 'AL2', info: 'Travelling motors time out' },
  { class: 'EL1', label: 'AL3', info: 'Rotation motor time out' },
  { class: 'EL1', label: 'AL4', info: 'Locking device motor 1 time out' },
  { class: 'EL1', label: 'AL5', info: 'Locking device motor 2 time out' },
  { class: 'EL1', label: 'AL6', info: 'Locking device motor 3 time out' },
  { class: 'EL1', label: 'AL7', info: 'Locking device motor 4 time out' },
  { class: 'EL1', label: 'AL8', info: 'Safety device motor time out' },
  { class: 'EL1', label: 'AL9', info: 'AL9' },
  { class: 'EL1', label: 'AL10', info: 'Flap motor time out' },
  { class: 'EL1', label: 'AL11', info: 'Door motor time out' },
  { class: 'EL1', label: 'AL12', info: 'AL12' },
  { class: 'EL1', label: 'AL13', info: 'AL13' },
  { class: 'EL1', label: 'AL14', info: 'Hoisting feedback safety check (1)' },
  { class: 'EL1', label: 'AL15', info: 'Hoisting feedback safety check (2)' },
  { class: 'EL1', label: 'AL16', info: 'AL16' },
  { class: 'EL1', label: 'AL17', info: 'Locking device motor 1 thermic protection' },
  { class: 'EL1', label: 'AL18', info: 'Locking device motor 2 thermic protection' },
  { class: 'EL1', label: 'AL19', info: 'Safety device motor thermic protection' },
  { class: 'EL1', label: 'AL20', info: 'AL20' },
  { class: 'EL1', label: 'AL21', info: 'Inverter 1 not ready' },
  { class: 'EL1', label: 'AL22', info: 'Inverter 2 not ready' },
  { class: 'EL1', label: 'AL23', info: 'Door motor thermic' },
  { class: 'EL1', label: 'AL24', info: 'Fuse 24VDC' },
  { class: 'EL1', label: 'AL25', info: 'KKP feeding line thermic protection (ASH)' },
  { class: 'EL1', label: 'AL26', info: 'Travelling motors thermic' },
  { class: 'EL1', label: 'AL27', info: 'Hoisting motors brake thermic' },
  { class: 'EL1', label: 'AL28', info: 'Hoisting motors thermic' },
  { class: 'EL1', label: 'AL29', info: 'Locking device motor 3 thermic protection' },
  { class: 'EL1', label: 'AL30', info: 'Locking device motor 4 thermic protection' },
  { class: 'EL1', label: 'AL31', info: 'Flap motor thermic' },
  { class: 'EL1', label: 'AL32', info: 'Rotation motor brake thermic protection' },
  { class: 'EL1', label: 'AL33', info: 'Locking device 1 EOM/EZM limitswitches' },
  { class: 'EL1', label: 'AL34', info: 'Locking device 2 EOM/EZM limitswitches' },
  { class: 'EL1', label: 'AL35', info: 'Locking device 3 EOM/EZM limitswitches' },
  { class: 'EL1', label: 'AL36', info: 'Locking device 4 EOM/EZM limitswitches' },
  { class: 'EL1', label: 'AL37', info: 'Safety device FLDX/FLSX sensors' },
  { class: 'EL1', label: 'AL38', info: 'AL38' },
  { class: 'EL1', label: 'AL39', info: 'Flap ECA/ECB limitswitches' },
  { class: 'EL1', label: 'AL40', info: 'Hoisting EXPV/EFA sensors' },
  { class: 'EL1', label: 'AL41', info: 'Door EZE/EOE limitswitches' },
  { class: 'EL1', label: 'AL42', info: 'AL42' },
  { class: 'EL1', label: 'AL43', info: 'AL43' },
  { class: 'EL1', label: 'AL44', info: 'AL44' },
  { class: 'EL1', label: 'AL45', info: 'AL45' },
  { class: 'EL1', label: 'AL46', info: 'AL46' },
  { class: 'EL1', label: 'AL47', info: 'AL47' },
  { class: 'EL1', label: 'AL48', info: 'AL48' },
  { class: 'EL1', label: 'AL49', info: 'Vertical laser 1 value is out of range' },
  { class: 'EL1', label: 'AL50', info: 'Vertical laser 2 value is out of range' },
  { class: 'EL1', label: 'AL51', info: 'Horizontal encoder value is out of range' },
  { class: 'EL1', label: 'AL52', info: 'Rotation encoder value is out of range' },
  { class: 'EL1', label: 'AL53', info: 'Vertical laser diversity tolerance check' },
  { class: 'EL1', label: 'AL54', info: 'AL54' },
  { class: 'EL1', label: 'AL55', info: 'PN Diag: IM155' },
  { class: 'EL1', label: 'AL56', info: 'PN Diag: KKP' },
  { class: 'EL1', label: 'AL57', info: 'PN Diag: IV1' },
  { class: 'EL1', label: 'AL58', info: 'PN Diag: IV2' },
  { class: 'EL1', label: 'AL59', info: 'PN Diag: LV1' },
  { class: 'EL1', label: 'AL60', info: 'PN Diag: LV2' },
  { class: 'EL1', label: 'AL61', info: 'PN Diag: ENCH' },
  { class: 'EL1', label: 'AL62', info: 'PN Diag: ENCR' },
  { class: 'EL1', label: 'AL63', info: 'AL63' },
  { class: 'EL1', label: 'AL64', info: 'AL64' }
]

export const alarms2 = [
  { class: 'EL2', label: 'AL1', info: 'Hoisting motor time out' },
  { class: 'EL2', label: 'AL2', info: 'Travelling motors time out' },
  { class: 'EL2', label: 'AL3', info: 'Rotation motor time out' },
  { class: 'EL2', label: 'AL4', info: 'Locking device motor 1 time out' },
  { class: 'EL2', label: 'AL5', info: 'Locking device motor 2 time out' },
  { class: 'EL2', label: 'AL6', info: 'Locking device motor 3 time out' },
  { class: 'EL2', label: 'AL7', info: 'Locking device motor 4 time out' },
  { class: 'EL2', label: 'AL8', info: 'Safety device motor time out' },
  { class: 'EL2', label: 'AL9', info: 'AL9' },
  { class: 'EL2', label: 'AL10', info: 'Flap motor time out' },
  { class: 'EL2', label: 'AL11', info: 'Door motor time out' },
  { class: 'EL2', label: 'AL12', info: 'AL12' },
  { class: 'EL2', label: 'AL13', info: 'AL13' },
  { class: 'EL2', label: 'AL14', info: 'Hoisting feedback safety check (1)' },
  { class: 'EL2', label: 'AL15', info: 'Hoisting feedback safety check (2)' },
  { class: 'EL2', label: 'AL16', info: 'AL16' },
  { class: 'EL2', label: 'AL17', info: 'Locking device motor 1 thermic protection' },
  { class: 'EL2', label: 'AL18', info: 'Locking device motor 2 thermic protection' },
  { class: 'EL2', label: 'AL19', info: 'Safety device motor thermic protection' },
  { class: 'EL2', label: 'AL20', info: 'AL20' },
  { class: 'EL2', label: 'AL21', info: 'Inverter 1 not ready' },
  { class: 'EL2', label: 'AL22', info: 'Inverter 2 not ready' },
  { class: 'EL2', label: 'AL23', info: 'Door motor thermic' },
  { class: 'EL2', label: 'AL24', info: 'Fuse 24VDC' },
  { class: 'EL2', label: 'AL25', info: 'KKP feeding line thermic protection (ASH)' },
  { class: 'EL2', label: 'AL26', info: 'Travelling motors thermic' },
  { class: 'EL2', label: 'AL27', info: 'Hoisting motors brake thermic' },
  { class: 'EL2', label: 'AL28', info: 'Hoisting motors thermic' },
  { class: 'EL2', label: 'AL29', info: 'Locking device motor 3 thermic protection' },
  { class: 'EL2', label: 'AL30', info: 'Locking device motor 4 thermic protection' },
  { class: 'EL2', label: 'AL31', info: 'Flap motor thermic' },
  { class: 'EL2', label: 'AL32', info: 'Rotation motor brake thermic protection' },
  { class: 'EL2', label: 'AL33', info: 'Locking device 1 EOM/EZM limitswitches' },
  { class: 'EL2', label: 'AL34', info: 'Locking device 2 EOM/EZM limitswitches' },
  { class: 'EL2', label: 'AL35', info: 'Locking device 3 EOM/EZM limitswitches' },
  { class: 'EL2', label: 'AL36', info: 'Locking device 4 EOM/EZM limitswitches' },
  { class: 'EL2', label: 'AL37', info: 'Safety device FLDX/FLSX sensors' },
  { class: 'EL2', label: 'AL38', info: 'AL38' },
  { class: 'EL2', label: 'AL39', info: 'Flap ECA/ECB limitswitches' },
  { class: 'EL2', label: 'AL40', info: 'Hoisting EXPV/EFA sensors' },
  { class: 'EL2', label: 'AL41', info: 'Door EZE/EOE limitswitches' },
  { class: 'EL2', label: 'AL42', info: 'AL42' },
  { class: 'EL2', label: 'AL43', info: 'AL43' },
  { class: 'EL2', label: 'AL44', info: 'AL44' },
  { class: 'EL2', label: 'AL45', info: 'AL45' },
  { class: 'EL2', label: 'AL46', info: 'AL46' },
  { class: 'EL2', label: 'AL47', info: 'AL47' },
  { class: 'EL2', label: 'AL48', info: 'AL48' },
  { class: 'EL2', label: 'AL49', info: 'Vertical laser 1 value is out of range' },
  { class: 'EL2', label: 'AL50', info: 'Vertical laser 2 value is out of range' },
  { class: 'EL2', label: 'AL51', info: 'Horizontal encoder value is out of range' },
  { class: 'EL2', label: 'AL52', info: 'Rotation encoder value is out of range' },
  { class: 'EL2', label: 'AL53', info: 'Vertical laser diversity tolerance check' },
  { class: 'EL2', label: 'AL54', info: 'AL54' },
  { class: 'EL2', label: 'AL55', info: 'PN Diag: IM155' },
  { class: 'EL2', label: 'AL56', info: 'PN Diag: KKP' },
  { class: 'EL2', label: 'AL57', info: 'PN Diag: IV1' },
  { class: 'EL2', label: 'AL58', info: 'PN Diag: IV2' },
  { class: 'EL2', label: 'AL59', info: 'PN Diag: LV1' },
  { class: 'EL2', label: 'AL60', info: 'PN Diag: LV2' },
  { class: 'EL2', label: 'AL61', info: 'PN Diag: ENCH' },
  { class: 'EL2', label: 'AL62', info: 'PN Diag: ENCR' },
  { class: 'EL2', label: 'AL63', info: 'AL63' },
  { class: 'EL2', label: 'AL64', info: 'AL64' }
]

export const alarms3 = [
  { class: 'EL3', label: 'AL1', info: 'Silomat travelling 1° bay time out' },
  { class: 'EL3', label: 'AL2', info: 'Silomat travelling 2° bay time out' },
  { class: 'EL3', label: 'AL3', info: 'Silomat travelling 3° bay time out' },
  { class: 'EL3', label: 'AL4', info: 'Silomat hoisting motor time out' },
  { class: 'EL3', label: 'AL5', info: 'Silomat front centering motor time out' },
  { class: 'EL3', label: 'AL6', info: 'Silomat back centering motor time out' },
  { class: 'EL3', label: 'AL7', info: 'Hoisting motors time out' },
  { class: 'EL3', label: 'AL8', info: 'Shuttle travelling motors time out' },
  { class: 'EL3', label: 'AL9', info: 'AL9' },
  { class: 'EL3', label: 'AL10', info: 'Hoisting feedback safety check (1)' },
  { class: 'EL3', label: 'AL11', info: 'Hoisting feedback safety check (2)' },
  { class: 'EL3', label: 'AL12', info: 'Locking device motor time out' },
  { class: 'EL3', label: 'AL13', info: 'AL13' },
  { class: 'EL3', label: 'AL14', info: 'AL14' },
  { class: 'EL3', label: 'AL15', info: 'AL15' },
  { class: 'EL3', label: 'AL16', info: 'AL16' },
  { class: 'EL3', label: 'AL17', info: 'FE1 fuses 24Vdc' },
  { class: 'EL3', label: 'AL18', info: 'Inverter 1 not ready' },
  { class: 'EL3', label: 'AL19', info: 'Inverter power off' },
  { class: 'EL3', label: 'AL20', info: 'Hoisting motors brake thermic' },
  { class: 'EL3', label: 'AL21', info: 'Hoisting motors thermic' },
  { class: 'EL3', label: 'AL22', info: 'KKP feeding line circuit breaker protection' },
  { class: 'EL3', label: 'AL23', info: 'Cable-reel motor thermic' },
  { class: 'EL3', label: 'AL24', info: 'FE3 fuses 24VDC' },
  { class: 'EL3', label: 'AL25', info: 'Locking device motor thermic' },
  { class: 'EL3', label: 'AL26', info: 'FE4 fuses 24VDc' },
  { class: 'EL3', label: 'AL27', info: 'Inverter 2 not ready' },
  { class: 'EL3', label: 'AL28', info: 'Inverter 2 power off' },
  { class: 'EL3', label: 'AL29', info: 'Silomat circut breaker protection' },
  { class: 'EL3', label: 'AL30', info: 'Shuttle motors thermic' },
  { class: 'EL3', label: 'AL31', info: 'Silomat motors thermic' },
  { class: 'EL3', label: 'AL32', info: 'AL32' },
  { class: 'EL3', label: 'AL33', info: 'Locking device EOM/EZM limitswitches' },
  { class: 'EL3', label: 'AL34', info: 'Silomat hoisting ES/EH limitswitches' },
  { class: 'EL3', label: 'AL35', info: 'Silomat transfer cycle check' },
  { class: 'EL3', label: 'AL36', info: 'Silomat FTXV/FTXH sensors safety check' },
  { class: 'EL3', label: 'AL37', info: 'Silomat overwidth detection FDR/FDL sensors (G0)' },
  { class: 'EL3', label: 'AL38', info: 'Silomat centering REAV/REAH sensors (G0)' },
  { class: 'EL3', label: 'AL39', info: 'AL39' },
  { class: 'EL3', label: 'AL40', info: 'AL40' },
  { class: 'EL3', label: 'AL41', info: 'AL41' },
  { class: 'EL3', label: 'AL42', info: 'AL42' },
  { class: 'EL3', label: 'AL43', info: 'AL43' },
  { class: 'EL3', label: 'AL44', info: 'AL44' },
  { class: 'EL3', label: 'AL45', info: 'AL45' },
  { class: 'EL3', label: 'AL46', info: 'AL46' },
  { class: 'EL3', label: 'AL47', info: 'AL47' },
  { class: 'EL3', label: 'AL48', info: 'AL48' },
  { class: 'EL3', label: 'AL49', info: 'Vertical laser 1 value is out of range' },
  { class: 'EL3', label: 'AL50', info: 'Vertical laser 2 value is out of range' },
  { class: 'EL3', label: 'AL51', info: 'Horizontal laser 1 value is out of range' },
  { class: 'EL3', label: 'AL52', info: 'Horizontal laser 2 value is out of range' },
  { class: 'EL3', label: 'AL53', info: 'Vertical laser diversity tolerance check' },
  { class: 'EL3', label: 'AL54', info: 'Horizontal laser diversity tolerance check' },
  { class: 'EL3', label: 'AL55', info: 'PN Diag: IM155' },
  { class: 'EL3', label: 'AL56', info: 'PN Diag: KKP' },
  { class: 'EL3', label: 'AL57', info: 'PN Diag: IV1' },
  { class: 'EL3', label: 'AL58', info: 'PN Diag: IV2' },
  { class: 'EL3', label: 'AL59', info: 'PN Diag: LV1' },
  { class: 'EL3', label: 'AL60', info: 'PN Diag: LV2' },
  { class: 'EL3', label: 'AL61', info: 'PN Diag: LH1' },
  { class: 'EL3', label: 'AL62', info: 'PN Diag: LH2' },
  { class: 'EL3', label: 'AL63', info: 'PN Diag: KKS' },
  { class: 'EL3', label: 'AL64', info: 'AL64' }
]

export const alarms4 = [
  { class: 'EL4', label: 'AL1', info: 'Silomat travelling 1° bay time out' },
  { class: 'EL4', label: 'AL2', info: 'Silomat travelling 2° bay time out' },
  { class: 'EL4', label: 'AL3', info: 'Silomat travelling 3° bay time out' },
  { class: 'EL4', label: 'AL4', info: 'Silomat hoisting motor time out' },
  { class: 'EL4', label: 'AL5', info: 'Silomat front centering motor time out' },
  { class: 'EL4', label: 'AL6', info: 'Silomat back centering motor time out' },
  { class: 'EL4', label: 'AL7', info: 'Hoisting motors time out' },
  { class: 'EL4', label: 'AL8', info: 'Shuttle travelling motors time out' },
  { class: 'EL4', label: 'AL9', info: 'AL9' },
  { class: 'EL4', label: 'AL10', info: 'Hoisting feedback safety check (1)' },
  { class: 'EL4', label: 'AL11', info: 'Hoisting feedback safety check (2)' },
  { class: 'EL4', label: 'AL12', info: 'Locking device motor time out' },
  { class: 'EL4', label: 'AL13', info: 'AL13' },
  { class: 'EL4', label: 'AL14', info: 'AL14' },
  { class: 'EL4', label: 'AL15', info: 'AL15' },
  { class: 'EL4', label: 'AL16', info: 'AL16' },
  { class: 'EL4', label: 'AL17', info: 'FE1 fuses 24Vdc' },
  { class: 'EL4', label: 'AL18', info: 'Inverter 1 not ready' },
  { class: 'EL4', label: 'AL19', info: 'Inverter power off' },
  { class: 'EL4', label: 'AL20', info: 'Hoisting motors brake thermic' },
  { class: 'EL4', label: 'AL21', info: 'Hoisting motors thermic' },
  { class: 'EL4', label: 'AL22', info: 'KKP feeding line circuit breaker protection' },
  { class: 'EL4', label: 'AL23', info: 'Cable-reel motor thermic' },
  { class: 'EL4', label: 'AL24', info: 'FE3 fuses 24VDC' },
  { class: 'EL4', label: 'AL25', info: 'Locking device motor thermic' },
  { class: 'EL4', label: 'AL26', info: 'FE4 fuses 24VDc' },
  { class: 'EL4', label: 'AL27', info: 'Inverter 2 not ready' },
  { class: 'EL4', label: 'AL28', info: 'Inverter 2 power off' },
  { class: 'EL4', label: 'AL29', info: 'Silomat circut breaker protection' },
  { class: 'EL4', label: 'AL30', info: 'Shuttle motors thermic' },
  { class: 'EL4', label: 'AL31', info: 'Silomat motors thermic' },
  { class: 'EL4', label: 'AL32', info: 'AL32' },
  { class: 'EL4', label: 'AL33', info: 'Locking device EOM/EZM limitswitches' },
  { class: 'EL4', label: 'AL34', info: 'Silomat hoisting ES/EH limitswitches' },
  { class: 'EL4', label: 'AL35', info: 'Silomat transfer cycle check' },
  { class: 'EL4', label: 'AL36', info: 'Silomat FTXV/FTXH sensors safety check' },
  { class: 'EL4', label: 'AL37', info: 'Silomat overwidth detection FDR/FDL sensors (G0)' },
  { class: 'EL4', label: 'AL38', info: 'Silomat centering REAV/REAH sensors (G0)' },
  { class: 'EL4', label: 'AL39', info: 'AL39' },
  { class: 'EL4', label: 'AL40', info: 'AL40' },
  { class: 'EL4', label: 'AL41', info: 'AL41' },
  { class: 'EL4', label: 'AL42', info: 'AL42' },
  { class: 'EL4', label: 'AL43', info: 'AL43' },
  { class: 'EL4', label: 'AL44', info: 'AL44' },
  { class: 'EL4', label: 'AL45', info: 'AL45' },
  { class: 'EL4', label: 'AL46', info: 'AL46' },
  { class: 'EL4', label: 'AL47', info: 'AL47' },
  { class: 'EL4', label: 'AL48', info: 'AL48' },
  { class: 'EL4', label: 'AL49', info: 'Vertical laser 1 value is out of range' },
  { class: 'EL4', label: 'AL50', info: 'Vertical laser 2 value is out of range' },
  { class: 'EL4', label: 'AL51', info: 'Horizontal laser 1 value is out of range' },
  { class: 'EL4', label: 'AL52', info: 'Horizontal laser 2 value is out of range' },
  { class: 'EL4', label: 'AL53', info: 'Vertical laser diversity tolerance check' },
  { class: 'EL4', label: 'AL54', info: 'Horizontal laser diversity tolerance check' },
  { class: 'EL4', label: 'AL55', info: 'PN Diag: IM155' },
  { class: 'EL4', label: 'AL56', info: 'PN Diag: KKP' },
  { class: 'EL4', label: 'AL57', info: 'PN Diag: IV1' },
  { class: 'EL4', label: 'AL58', info: 'PN Diag: IV2' },
  { class: 'EL4', label: 'AL59', info: 'PN Diag: LV1' },
  { class: 'EL4', label: 'AL60', info: 'PN Diag: LV2' },
  { class: 'EL4', label: 'AL61', info: 'PN Diag: LH1' },
  { class: 'EL4', label: 'AL62', info: 'PN Diag: LH2' },
  { class: 'EL4', label: 'AL63', info: 'PN Diag: KKS' },
  { class: 'EL4', label: 'AL64', info: 'AL64' }
]
