export const devices = [
  'EL1', 'EL2', 'EL3', 'EL4'
]

export const modes = [
  '---',
  'Data Edit',
  'Data Read',
  'Emergency 1',
  'Emergency 2',
  'Map Edit',
  'Step by Step',
  'Preset',
  'Automatic'
]

export const operations = [
  '---',
  'Alarm on',
  'Alarm off',
  'Switch function mode',
  'Card PIN code changed',
  'Stall in',
  'Stall out',
  'Shuffle in',
  'Shuffle out',
  '---',
  'Exit request',
  'Entry request',
  '---',
  '---',
  '---',
  '---'
]

export const measures = [
  'Laser V',
  'Laser H',
  'Encoder',
  'Laser V',
  'Laser H',
  'Encoder',
  'Laser V',
  'Laser H',
  'Encoder',
  'Laser V',
  'Laser H',
  'Encoder'
]

export const inputs0 = [
  { addr: 'E0.0', label: 'A', info: '' },
  { addr: 'E0.1', label: 'B', info: '' },
  { addr: 'E0.2', label: 'C', info: '' },
  { addr: 'E0.3', label: 'D', info: '' },
  { addr: 'E0.4', label: 'STR', info: '' },
  { addr: 'E0.5', label: 'OK', info: '' },
  { addr: 'E0.6', label: 'DAT', info: '' },
  { addr: 'E0.7', label: 'FE1', info: '' },
  { addr: 'E1.0', label: 'A', info: '' },
  { addr: 'E1.1', label: 'B', info: '' },
  { addr: 'E1.2', label: 'C', info: '' },
  { addr: 'E1.3', label: 'D', info: '' },
  { addr: 'E1.4', label: 'STR', info: '' },
  { addr: 'E1.5', label: 'OK', info: '' },
  { addr: 'E1.6', label: 'DAT', info: '' },
  { addr: 'E1.7', label: '', info: '' },
  { addr: 'E2.0', label: '', info: '' },
  { addr: 'E2.1', label: '', info: '' },
  { addr: 'E2.2', label: '', info: '' },
  { addr: 'E2.3', label: 'RSI', info: '' },
  { addr: 'E2.4', label: 'SFT1', info: '' },
  { addr: 'E2.5', label: 'SFT2', info: '' },
  { addr: 'E2.6', label: 'SFT3', info: '' },
  { addr: 'E2.7', label: 'SFT4', info: '' },
  { addr: 'E3.0', label: '', info: '' },
  { addr: 'E3.1', label: '', info: '' },
  { addr: 'E3.2', label: '', info: '' },
  { addr: 'E3.3', label: '', info: '' },
  { addr: 'E3.4', label: '', info: '' },
  { addr: 'E3.5', label: '', info: '' },
  { addr: 'E3.6', label: '', info: '' },
  { addr: 'E3.7', label: '', info: '' },
]
export const inputs1 = [
  { addr: 'E100.0', label: 'A', info: '' },
  { addr: 'E100.1', label: 'B', info: '' },
  { addr: 'E100.2', label: 'C', info: '' },
  { addr: 'E100.3', label: 'D', info: '' },
  { addr: 'E100.4', label: 'OK', info: '' },
  { addr: 'E100.5', label: 'S2', info: '' },
  { addr: 'E100.6', label: 'S2', info: '' },
  { addr: 'E100.7', label: 'S2', info: '' },
  { addr: 'E101.0', label: 'A', info: '' },
  { addr: 'E101.1', label: 'B', info: '' },
  { addr: 'E101.2', label: 'C', info: '' },
  { addr: 'E101.3', label: 'D', info: '' },
  { addr: 'E101.4', label: 'STR', info: '' },
  { addr: 'E101.5', label: 'OK', info: '' },
  { addr: 'E101.6', label: 'DAT', info: '' },
  { addr: 'E101.7', label: 'UC', info: '' },
  { addr: 'E102.0', label: 'ECA', info: '' },
  { addr: 'E102.1', label: 'ECB', info: '' },
  { addr: 'E102.2', label: 'AMC', info: '' },
  { addr: 'E102.3', label: 'FDBK', info: '' },
  { addr: 'E102.4', label: 'ASBK', info: '' },
  { addr: 'E102.5', label: 'RTA', info: '' },
  { addr: 'E102.6', label: 'SQA', info: '' },
  { addr: 'E102.7', label: '', info: '' },
  { addr: 'E103.0', label: 'EOM', info: '' },
  { addr: 'E103.1', label: 'EZM', info: '' },
  { addr: 'E103.2', label: 'AMM', info: '' },
  { addr: 'E103.3', label: 'FE1', info: '' },
  { addr: 'E103.4', label: 'RS3', info: '' },
  { addr: 'E103.5', label: 'RSI', info: '' },
  { addr: 'E103.6', label: 'IV1', info: '' },
  { addr: 'E103.7', label: '', info: '' },
  { addr: 'E104.0', label: 'EZE', info: '' },
  { addr: 'E104.1', label: 'EOE', info: '' },
  { addr: 'E104.2', label: 'FBE', info: '' },
  { addr: 'E104.3', label: 'APE', info: '' },
  { addr: 'E104.4', label: 'RXE', info: '' },
  { addr: 'E104.5', label: 'FRE', info: '' },
  { addr: 'E104.6', label: 'EPZV', info: '' },
  { addr: 'E104.7', label: 'EPZH', info: '' },
  { addr: 'E105.0', label: 'EXZE', info: '' },
  { addr: 'E105.1', label: 'EXZA', info: '' },
  { addr: 'E105.2', label: 'KEXPV', info: '' },
  { addr: 'E105.3', label: 'IV2', info: '' },
  { addr: 'E105.4', label: 'ASH', info: '' },
  { addr: 'E105.5', label: 'SFT1', info: '' },
  { addr: 'E105.6', label: '', info: '' },
  { addr: 'E105.7', label: '', info: '' },
  { addr: 'E106.0', label: 'FPE', info: '' },
  { addr: 'E106.1', label: 'FLA1', info: '' },
  { addr: 'E106.2', label: 'FLP2', info: '' },
  { addr: 'E106.3', label: 'FLP1', info: '' },
  { addr: 'E106.4', label: 'FDR1', info: '' },
  { addr: 'E106.5', label: 'FDL1', info: '' },
  { addr: 'E106.6', label: 'FTA1', info: '' },
  { addr: 'E106.7', label: 'FTA2', info: '' },
  { addr: 'E107.0', label: 'EXV', info: '' },
  { addr: 'E107.1', label: 'EXPV', info: '' },
  { addr: 'E107.2', label: 'EFB', info: '' },
  { addr: 'E107.3', label: 'AIVA', info: '' },
  { addr: 'E107.4', label: 'EMC', info: '' },
  { addr: 'E107.5', label: 'FDR2', info: '' },
  { addr: 'E107.6', label: 'FDL2', info: '' },
  { addr: 'E107.7', label: 'AIVB', info: '' },
  { addr: 'E108.0', label: 'EBZE', info: '' },
  { addr: 'E108.1', label: 'EBOE', info: '' },
  { addr: 'E108.2', label: 'FBBE', info: '' },
  { addr: 'E108.3', label: 'APBE', info: '' },
  { addr: 'E108.4', label: 'EBZA', info: '' },
  { addr: 'E108.5', label: 'EBOA', info: '' },
  { addr: 'E108.6', label: 'FBBA', info: '' },
  { addr: 'E108.7', label: 'APBA', info: '' },
  { addr: 'E109.0', label: 'EZA', info: '' },
  { addr: 'E109.1', label: 'EOA', info: '' },
  { addr: 'E109.2', label: 'FBA', info: '' },
  { addr: 'E109.3', label: 'APA', info: '' },
  { addr: 'E109.4', label: 'FPA', info: '' },
  { addr: 'E109.5', label: 'RXA', info: '' },
  { addr: 'E109.6', label: '', info: '' },
  { addr: 'E109.7', label: '', info: '' },
]
export const inputs2 = [
  { addr: 'E160.0', label: 'A', info: '' },
  { addr: 'E160.1', label: 'B', info: '' },
  { addr: 'E160.2', label: 'C', info: '' },
  { addr: 'E160.3', label: 'D', info: '' },
  { addr: 'E160.4', label: 'OK', info: '' },
  { addr: 'E160.5', label: 'S2', info: '' },
  { addr: 'E160.6', label: 'S2', info: '' },
  { addr: 'E160.7', label: 'S2', info: '' },
  { addr: 'E161.0', label: '', info: '' },
  { addr: 'E161.1', label: 'UC', info: '' },
  { addr: 'E161.2', label: 'FE1', info: '' },
  { addr: 'E161.3', label: '', info: '' },
  { addr: 'E161.4', label: 'FTV1', info: '' },
  { addr: 'E161.5', label: 'FTH1', info: '' },
  { addr: 'E161.6', label: 'FTXV', info: '' },
  { addr: 'E161.7', label: 'FTXH', info: '' },
  { addr: 'E162.0', label: 'AF8A', info: '' },
  { addr: 'E162.1', label: 'EMA', info: '' },
  { addr: 'E162.2', label: 'RESA', info: '' },
  { addr: 'E162.3', label: 'REHA', info: '' },
  { addr: 'E162.4', label: 'RBVA', info: '' },
  { addr: 'E162.5', label: 'RBHA', info: '' },
  { addr: 'E162.6', label: 'RCLA', info: '' },
  { addr: 'E162.7', label: 'RPLA', info: '' },
  { addr: 'E163.0', label: 'AF8B', info: '' },
  { addr: 'E163.1', label: 'EMB', info: '' },
  { addr: 'E163.2', label: 'RESB', info: '' },
  { addr: 'E163.3', label: 'REHB', info: '' },
  { addr: 'E163.4', label: 'RBVB', info: '' },
  { addr: 'E163.5', label: 'RBHB', info: '' },
  { addr: 'E163.6', label: 'RCLB', info: '' },
  { addr: 'E163.7', label: 'RPLB', info: '' },
  { addr: 'E164.0', label: '', info: '' },
  { addr: 'E164.1', label: '', info: '' },
  { addr: 'E164.2', label: '', info: '' },
  { addr: 'E164.3', label: '', info: '' },
  { addr: 'E164.4', label: 'FTH2', info: '' },
  { addr: 'E164.5', label: 'ASBK2', info: '' },
  { addr: 'E164.6', label: 'AH', info: '' },
  { addr: 'E164.7', label: 'MTCA', info: '' },
  { addr: 'E165.0', label: 'MTCB', info: '' },
  { addr: 'E165.1', label: '', info: '' },
  { addr: 'E165.2', label: 'SFT', info: '' },
  { addr: 'E165.3', label: 'RSI', info: '' },
  { addr: 'E165.4', label: 'DB32', info: '' },
  { addr: 'E165.5', label: 'DBHZ', info: '' },
  { addr: 'E165.6', label: 'FTAC', info: '' },
  { addr: 'E165.7', label: '', info: '' },
]
export const inputs3 = [
  { addr: 'E200.0', label: 'A', info: '' },
  { addr: 'E200.1', label: 'B', info: '' },
  { addr: 'E200.2', label: 'C', info: '' },
  { addr: 'E200.3', label: 'D', info: '' },
  { addr: 'E200.4', label: 'OK', info: '' },
  { addr: 'E200.5', label: 'S2', info: '' },
  { addr: 'E200.6', label: 'S2', info: '' },
  { addr: 'E200.7', label: 'S2', info: '' },
  { addr: 'E201.0', label: 'A', info: '' },
  { addr: 'E201.1', label: 'B', info: '' },
  { addr: 'E201.2', label: 'C', info: '' },
  { addr: 'E201.3', label: 'D', info: '' },
  { addr: 'E201.4', label: 'STR', info: '' },
  { addr: 'E201.5', label: 'OK', info: '' },
  { addr: 'E201.6', label: 'DAT', info: '' },
  { addr: 'E201.7', label: 'UC', info: '' },
  { addr: 'E202.0', label: 'ECA', info: '' },
  { addr: 'E202.1', label: 'ECB', info: '' },
  { addr: 'E202.2', label: 'AMC', info: '' },
  { addr: 'E202.3', label: 'FDBK', info: '' },
  { addr: 'E202.4', label: 'ASBK', info: '' },
  { addr: 'E202.5', label: 'RTA', info: '' },
  { addr: 'E202.6', label: 'SQA', info: '' },
  { addr: 'E202.7', label: '', info: '' },
  { addr: 'E203.0', label: 'EOM', info: '' },
  { addr: 'E203.1', label: 'EZM', info: '' },
  { addr: 'E203.2', label: 'AMM', info: '' },
  { addr: 'E203.3', label: 'FE1', info: '' },
  { addr: 'E203.4', label: 'RS3', info: '' },
  { addr: 'E203.5', label: 'RSI', info: '' },
  { addr: 'E203.6', label: 'IV1', info: '' },
  { addr: 'E203.7', label: '', info: '' },
  { addr: 'E204.0', label: 'EZE', info: '' },
  { addr: 'E204.1', label: 'EOE', info: '' },
  { addr: 'E204.2', label: 'FBE', info: '' },
  { addr: 'E204.3', label: 'APE', info: '' },
  { addr: 'E204.4', label: 'RXE', info: '' },
  { addr: 'E204.5', label: 'FRE', info: '' },
  { addr: 'E204.6', label: 'EPZV', info: '' },
  { addr: 'E204.7', label: 'EPZH', info: '' },
  { addr: 'E205.0', label: 'EXZE', info: '' },
  { addr: 'E205.1', label: 'EXZA', info: '' },
  { addr: 'E205.2', label: 'KEXPV', info: '' },
  { addr: 'E205.3', label: 'IV2', info: '' },
  { addr: 'E205.4', label: 'ASH', info: '' },
  { addr: 'E205.5', label: 'SFT1', info: '' },
  { addr: 'E205.6', label: '', info: '' },
  { addr: 'E205.7', label: '', info: '' },
  { addr: 'E206.0', label: 'FPE', info: '' },
  { addr: 'E206.1', label: 'FLA1', info: '' },
  { addr: 'E206.2', label: 'FLP2', info: '' },
  { addr: 'E206.3', label: 'FLP1', info: '' },
  { addr: 'E206.4', label: 'FDR1', info: '' },
  { addr: 'E206.5', label: 'FDL1', info: '' },
  { addr: 'E206.6', label: 'FTA1', info: '' },
  { addr: 'E206.7', label: 'FTA2', info: '' },
  { addr: 'E207.0', label: 'EXV', info: '' },
  { addr: 'E207.1', label: 'EXPV', info: '' },
  { addr: 'E207.2', label: 'EFB', info: '' },
  { addr: 'E207.3', label: 'AIVA', info: '' },
  { addr: 'E207.4', label: 'EMC', info: '' },
  { addr: 'E207.5', label: 'FDR2', info: '' },
  { addr: 'E207.6', label: 'FDL2', info: '' },
  { addr: 'E207.7', label: 'AIVB', info: '' },
  { addr: 'E208.0', label: 'EBZE', info: '' },
  { addr: 'E208.1', label: 'EBOE', info: '' },
  { addr: 'E208.2', label: 'FBBE', info: '' },
  { addr: 'E208.3', label: 'APBE', info: '' },
  { addr: 'E208.4', label: 'EBZA', info: '' },
  { addr: 'E208.5', label: 'EBOA', info: '' },
  { addr: 'E208.6', label: 'FBBA', info: '' },
  { addr: 'E208.7', label: 'APBA', info: '' },
  { addr: 'E209.0', label: 'EZA', info: '' },
  { addr: 'E209.1', label: 'EOA', info: '' },
  { addr: 'E209.2', label: 'FBA', info: '' },
  { addr: 'E209.3', label: 'APA', info: '' },
  { addr: 'E209.4', label: 'FPA', info: '' },
  { addr: 'E209.5', label: 'RXA', info: '' },
  { addr: 'E209.6', label: '', info: '' },
  { addr: 'E209.7', label: '', info: '' },
]
export const inputs4 = [
  { addr: 'E260.0', label: 'A', info: '' },
  { addr: 'E260.1', label: 'B', info: '' },
  { addr: 'E260.2', label: 'C', info: '' },
  { addr: 'E260.3', label: 'D', info: '' },
  { addr: 'E260.4', label: 'OK', info: '' },
  { addr: 'E260.5', label: 'S2', info: '' },
  { addr: 'E260.6', label: 'S2', info: '' },
  { addr: 'E260.7', label: 'S2', info: '' },
  { addr: 'E261.0', label: '', info: '' },
  { addr: 'E261.1', label: 'UC', info: '' },
  { addr: 'E261.2', label: 'FE1', info: '' },
  { addr: 'E261.3', label: '', info: '' },
  { addr: 'E261.4', label: 'FTV1', info: '' },
  { addr: 'E261.5', label: 'FTH1', info: '' },
  { addr: 'E261.6', label: 'FTXV', info: '' },
  { addr: 'E261.7', label: 'FTXH', info: '' },
  { addr: 'E262.0', label: 'AF8A', info: '' },
  { addr: 'E262.1', label: 'EMA', info: '' },
  { addr: 'E262.2', label: 'RESA', info: '' },
  { addr: 'E262.3', label: 'REHA', info: '' },
  { addr: 'E262.4', label: 'RBVA', info: '' },
  { addr: 'E262.5', label: 'RBHA', info: '' },
  { addr: 'E262.6', label: 'RCLA', info: '' },
  { addr: 'E262.7', label: 'RPLA', info: '' },
  { addr: 'E263.0', label: 'AF8B', info: '' },
  { addr: 'E263.1', label: 'EMB', info: '' },
  { addr: 'E263.2', label: 'RESB', info: '' },
  { addr: 'E263.3', label: 'REHB', info: '' },
  { addr: 'E263.4', label: 'RBVB', info: '' },
  { addr: 'E263.5', label: 'RBHB', info: '' },
  { addr: 'E263.6', label: 'RCLB', info: '' },
  { addr: 'E263.7', label: 'RPLB', info: '' },
  { addr: 'E264.0', label: '', info: '' },
  { addr: 'E264.1', label: '', info: '' },
  { addr: 'E264.2', label: '', info: '' },
  { addr: 'E264.3', label: '', info: '' },
  { addr: 'E264.4', label: 'FTH2', info: '' },
  { addr: 'E264.5', label: 'ASBK2', info: '' },
  { addr: 'E264.6', label: 'AH', info: '' },
  { addr: 'E264.7', label: 'MTCA', info: '' },
  { addr: 'E265.0', label: 'MTCB', info: '' },
  { addr: 'E265.1', label: '', info: '' },
  { addr: 'E265.2', label: 'SFT', info: '' },
  { addr: 'E265.3', label: 'RSI', info: '' },
  { addr: 'E265.4', label: 'DB32', info: '' },
  { addr: 'E265.5', label: 'DBHZ', info: '' },
  { addr: 'E265.6', label: 'FTAC', info: '' },
  { addr: 'E265.7', label: '', info: '' },
]
export const inputs5 = [
  { addr: 'E300.0', label: 'A', info: '' },
  { addr: 'E300.1', label: 'B', info: '' },
  { addr: 'E300.2', label: 'C', info: '' },
  { addr: 'E300.3', label: 'D', info: '' },
  { addr: 'E300.4', label: 'OK', info: '' },
  { addr: 'E300.5', label: 'S2', info: '' },
  { addr: 'E300.6', label: 'S2', info: '' },
  { addr: 'E300.7', label: 'S2', info: '' },
  { addr: 'E301.0', label: 'A', info: '' },
  { addr: 'E301.1', label: 'B', info: '' },
  { addr: 'E301.2', label: 'C', info: '' },
  { addr: 'E301.3', label: 'D', info: '' },
  { addr: 'E301.4', label: 'STR', info: '' },
  { addr: 'E301.5', label: 'OK', info: '' },
  { addr: 'E301.6', label: 'DAT', info: '' },
  { addr: 'E301.7', label: 'UC', info: '' },
  { addr: 'E302.0', label: 'ECA', info: '' },
  { addr: 'E302.1', label: 'ECB', info: '' },
  { addr: 'E302.2', label: 'AMC', info: '' },
  { addr: 'E302.3', label: 'FDBK', info: '' },
  { addr: 'E302.4', label: 'ASBK', info: '' },
  { addr: 'E302.5', label: 'RTA', info: '' },
  { addr: 'E302.6', label: 'SQA', info: '' },
  { addr: 'E302.7', label: '', info: '' },
  { addr: 'E303.0', label: 'EOM', info: '' },
  { addr: 'E303.1', label: 'EZM', info: '' },
  { addr: 'E303.2', label: 'AMM', info: '' },
  { addr: 'E303.3', label: 'FE1', info: '' },
  { addr: 'E303.4', label: 'RS3', info: '' },
  { addr: 'E303.5', label: 'RSI', info: '' },
  { addr: 'E303.6', label: 'IV1', info: '' },
  { addr: 'E303.7', label: '', info: '' },
  { addr: 'E304.0', label: 'EZE', info: '' },
  { addr: 'E304.1', label: 'EOE', info: '' },
  { addr: 'E304.2', label: 'FBE', info: '' },
  { addr: 'E304.3', label: 'APE', info: '' },
  { addr: 'E304.4', label: 'RXE', info: '' },
  { addr: 'E304.5', label: 'FRE', info: '' },
  { addr: 'E304.6', label: 'EPZV', info: '' },
  { addr: 'E304.7', label: 'EPZH', info: '' },
  { addr: 'E305.0', label: 'EXZE', info: '' },
  { addr: 'E305.1', label: 'EXZA', info: '' },
  { addr: 'E305.2', label: 'KEXPV', info: '' },
  { addr: 'E305.3', label: 'IV2', info: '' },
  { addr: 'E305.4', label: 'ASH', info: '' },
  { addr: 'E305.5', label: 'SFT1', info: '' },
  { addr: 'E305.6', label: '', info: '' },
  { addr: 'E305.7', label: '', info: '' },
  { addr: 'E306.0', label: 'FPE', info: '' },
  { addr: 'E306.1', label: 'FLA1', info: '' },
  { addr: 'E306.2', label: 'FLP2', info: '' },
  { addr: 'E306.3', label: 'FLP1', info: '' },
  { addr: 'E306.4', label: 'FDR1', info: '' },
  { addr: 'E306.5', label: 'FDL1', info: '' },
  { addr: 'E306.6', label: 'FTA1', info: '' },
  { addr: 'E306.7', label: 'FTA2', info: '' },
  { addr: 'E307.0', label: 'EXV', info: '' },
  { addr: 'E307.1', label: 'EXPV', info: '' },
  { addr: 'E307.2', label: 'EFB', info: '' },
  { addr: 'E307.3', label: 'AIVA', info: '' },
  { addr: 'E307.4', label: 'EMC', info: '' },
  { addr: 'E307.5', label: 'FDR2', info: '' },
  { addr: 'E307.6', label: 'FDL2', info: '' },
  { addr: 'E307.7', label: 'AIVB', info: '' },
  { addr: 'E308.0', label: 'EBZE', info: '' },
  { addr: 'E308.1', label: 'EBOE', info: '' },
  { addr: 'E308.2', label: 'FBBE', info: '' },
  { addr: 'E308.3', label: 'APBE', info: '' },
  { addr: 'E308.4', label: 'EBZA', info: '' },
  { addr: 'E308.5', label: 'EBOA', info: '' },
  { addr: 'E308.6', label: 'FBBA', info: '' },
  { addr: 'E308.7', label: 'APBA', info: '' },
  { addr: 'E309.0', label: 'EZA', info: '' },
  { addr: 'E309.1', label: 'EOA', info: '' },
  { addr: 'E309.2', label: 'FBA', info: '' },
  { addr: 'E309.3', label: 'APA', info: '' },
  { addr: 'E309.4', label: 'FPA', info: '' },
  { addr: 'E309.5', label: 'RXA', info: '' },
  { addr: 'E309.6', label: '', info: '' },
  { addr: 'E309.7', label: '', info: '' },
]
export const inputs6 = [
  { addr: 'E360.0', label: 'A', info: '' },
  { addr: 'E360.1', label: 'B', info: '' },
  { addr: 'E360.2', label: 'C', info: '' },
  { addr: 'E360.3', label: 'D', info: '' },
  { addr: 'E360.4', label: 'OK', info: '' },
  { addr: 'E360.5', label: 'S2', info: '' },
  { addr: 'E360.6', label: 'S2', info: '' },
  { addr: 'E360.7', label: 'S2', info: '' },
  { addr: 'E361.0', label: '', info: '' },
  { addr: 'E361.1', label: 'UC', info: '' },
  { addr: 'E361.2', label: 'FE1', info: '' },
  { addr: 'E361.3', label: '', info: '' },
  { addr: 'E361.4', label: 'FTV1', info: '' },
  { addr: 'E361.5', label: 'FTH1', info: '' },
  { addr: 'E361.6', label: 'FTXV', info: '' },
  { addr: 'E361.7', label: 'FTXH', info: '' },
  { addr: 'E362.0', label: 'AF8A', info: '' },
  { addr: 'E362.1', label: 'EMA', info: '' },
  { addr: 'E362.2', label: 'RESA', info: '' },
  { addr: 'E362.3', label: 'REHA', info: '' },
  { addr: 'E362.4', label: 'RBVA', info: '' },
  { addr: 'E362.5', label: 'RBHA', info: '' },
  { addr: 'E362.6', label: 'RCLA', info: '' },
  { addr: 'E362.7', label: 'RPLA', info: '' },
  { addr: 'E363.0', label: 'AF8B', info: '' },
  { addr: 'E363.1', label: 'EMB', info: '' },
  { addr: 'E363.2', label: 'RESB', info: '' },
  { addr: 'E363.3', label: 'REHB', info: '' },
  { addr: 'E363.4', label: 'RBVB', info: '' },
  { addr: 'E363.5', label: 'RBHB', info: '' },
  { addr: 'E363.6', label: 'RCLB', info: '' },
  { addr: 'E363.7', label: 'RPLB', info: '' },
  { addr: 'E364.0', label: '', info: '' },
  { addr: 'E364.1', label: '', info: '' },
  { addr: 'E364.2', label: '', info: '' },
  { addr: 'E364.3', label: '', info: '' },
  { addr: 'E364.4', label: 'FTH2', info: '' },
  { addr: 'E364.5', label: 'ASBK2', info: '' },
  { addr: 'E364.6', label: 'AH', info: '' },
  { addr: 'E364.7', label: 'MTCA', info: '' },
  { addr: 'E365.0', label: 'MTCB', info: '' },
  { addr: 'E365.1', label: '', info: '' },
  { addr: 'E365.2', label: 'SFT', info: '' },
  { addr: 'E365.3', label: 'RSI', info: '' },
  { addr: 'E365.4', label: 'DB32', info: '' },
  { addr: 'E365.5', label: 'DBHZ', info: '' },
  { addr: 'E365.6', label: 'FTAC', info: '' },
  { addr: 'E365.7', label: '', info: '' },
]
export const inputs7 = [
  { addr: 'E400.0', label: 'A', info: '' },
  { addr: 'E400.1', label: 'B', info: '' },
  { addr: 'E400.2', label: 'C', info: '' },
  { addr: 'E400.3', label: 'D', info: '' },
  { addr: 'E400.4', label: 'OK', info: '' },
  { addr: 'E400.5', label: 'S2', info: '' },
  { addr: 'E400.6', label: 'S2', info: '' },
  { addr: 'E400.7', label: 'S2', info: '' },
  { addr: 'E401.0', label: 'A', info: '' },
  { addr: 'E401.1', label: 'B', info: '' },
  { addr: 'E401.2', label: 'C', info: '' },
  { addr: 'E401.3', label: 'D', info: '' },
  { addr: 'E401.4', label: 'STR', info: '' },
  { addr: 'E401.5', label: 'OK', info: '' },
  { addr: 'E401.6', label: 'DAT', info: '' },
  { addr: 'E401.7', label: 'UC', info: '' },
  { addr: 'E402.0', label: 'ECA', info: '' },
  { addr: 'E402.1', label: 'ECB', info: '' },
  { addr: 'E402.2', label: 'AMC', info: '' },
  { addr: 'E402.3', label: 'FDBK', info: '' },
  { addr: 'E402.4', label: 'ASBK', info: '' },
  { addr: 'E402.5', label: 'RTA', info: '' },
  { addr: 'E402.6', label: 'SQA', info: '' },
  { addr: 'E402.7', label: '', info: '' },
  { addr: 'E403.0', label: 'EOM', info: '' },
  { addr: 'E403.1', label: 'EZM', info: '' },
  { addr: 'E403.2', label: 'AMM', info: '' },
  { addr: 'E403.3', label: 'FE1', info: '' },
  { addr: 'E403.4', label: 'RS3', info: '' },
  { addr: 'E403.5', label: 'RSI', info: '' },
  { addr: 'E403.6', label: 'IV1', info: '' },
  { addr: 'E403.7', label: '', info: '' },
  { addr: 'E404.0', label: 'EZE', info: '' },
  { addr: 'E404.1', label: 'EOE', info: '' },
  { addr: 'E404.2', label: 'FBE', info: '' },
  { addr: 'E404.3', label: 'APE', info: '' },
  { addr: 'E404.4', label: 'RXE', info: '' },
  { addr: 'E404.5', label: 'FRE', info: '' },
  { addr: 'E404.6', label: 'EPZV', info: '' },
  { addr: 'E404.7', label: 'EPZH', info: '' },
  { addr: 'E405.0', label: 'EXZE', info: '' },
  { addr: 'E405.1', label: 'EXZA', info: '' },
  { addr: 'E405.2', label: 'KEXPV', info: '' },
  { addr: 'E405.3', label: 'IV2', info: '' },
  { addr: 'E405.4', label: 'ASH', info: '' },
  { addr: 'E405.5', label: 'SFT1', info: '' },
  { addr: 'E405.6', label: '', info: '' },
  { addr: 'E405.7', label: '', info: '' },
  { addr: 'E406.0', label: 'FPE', info: '' },
  { addr: 'E406.1', label: 'FLA1', info: '' },
  { addr: 'E406.2', label: 'FLP2', info: '' },
  { addr: 'E406.3', label: 'FLP1', info: '' },
  { addr: 'E406.4', label: 'FDR1', info: '' },
  { addr: 'E406.5', label: 'FDL1', info: '' },
  { addr: 'E406.6', label: 'FTA1', info: '' },
  { addr: 'E406.7', label: 'FTA2', info: '' },
  { addr: 'E407.0', label: 'EXV', info: '' },
  { addr: 'E407.1', label: 'EXPV', info: '' },
  { addr: 'E407.2', label: 'EFB', info: '' },
  { addr: 'E407.3', label: 'AIVA', info: '' },
  { addr: 'E407.4', label: 'EMC', info: '' },
  { addr: 'E407.5', label: 'FDR2', info: '' },
  { addr: 'E407.6', label: 'FDL2', info: '' },
  { addr: 'E407.7', label: 'AIVB', info: '' },
  { addr: 'E408.0', label: 'EBZE', info: '' },
  { addr: 'E408.1', label: 'EBOE', info: '' },
  { addr: 'E408.2', label: 'FBBE', info: '' },
  { addr: 'E408.3', label: 'APBE', info: '' },
  { addr: 'E408.4', label: 'EBZA', info: '' },
  { addr: 'E408.5', label: 'EBOA', info: '' },
  { addr: 'E408.6', label: 'FBBA', info: '' },
  { addr: 'E408.7', label: 'APBA', info: '' },
  { addr: 'E409.0', label: 'EZA', info: '' },
  { addr: 'E409.1', label: 'EOA', info: '' },
  { addr: 'E409.2', label: 'FBA', info: '' },
  { addr: 'E409.3', label: 'APA', info: '' },
  { addr: 'E409.4', label: 'FPA', info: '' },
  { addr: 'E409.5', label: 'RXA', info: '' },
  { addr: 'E409.6', label: '', info: '' },
  { addr: 'E409.7', label: '', info: '' },
]
export const inputs8 = [
  { addr: 'E460.0', label: 'A', info: '' },
  { addr: 'E460.1', label: 'B', info: '' },
  { addr: 'E460.2', label: 'C', info: '' },
  { addr: 'E460.3', label: 'D', info: '' },
  { addr: 'E460.4', label: 'OK', info: '' },
  { addr: 'E460.5', label: 'S2', info: '' },
  { addr: 'E460.6', label: 'S2', info: '' },
  { addr: 'E460.7', label: 'S2', info: '' },
  { addr: 'E461.0', label: '', info: '' },
  { addr: 'E461.1', label: 'UC', info: '' },
  { addr: 'E461.2', label: 'FE1', info: '' },
  { addr: 'E461.3', label: '', info: '' },
  { addr: 'E461.4', label: 'FTV1', info: '' },
  { addr: 'E461.5', label: 'FTH1', info: '' },
  { addr: 'E461.6', label: 'FTXV', info: '' },
  { addr: 'E461.7', label: 'FTXH', info: '' },
  { addr: 'E462.0', label: 'AF8A', info: '' },
  { addr: 'E462.1', label: 'EMA', info: '' },
  { addr: 'E462.2', label: 'RESA', info: '' },
  { addr: 'E462.3', label: 'REHA', info: '' },
  { addr: 'E462.4', label: 'RBVA', info: '' },
  { addr: 'E462.5', label: 'RBHA', info: '' },
  { addr: 'E462.6', label: 'RCLA', info: '' },
  { addr: 'E462.7', label: 'RPLA', info: '' },
  { addr: 'E463.0', label: 'AF8B', info: '' },
  { addr: 'E463.1', label: 'EMB', info: '' },
  { addr: 'E463.2', label: 'RESB', info: '' },
  { addr: 'E463.3', label: 'REHB', info: '' },
  { addr: 'E463.4', label: 'RBVB', info: '' },
  { addr: 'E463.5', label: 'RBHB', info: '' },
  { addr: 'E463.6', label: 'RCLB', info: '' },
  { addr: 'E463.7', label: 'RPLB', info: '' },
  { addr: 'E464.0', label: '', info: '' },
  { addr: 'E464.1', label: '', info: '' },
  { addr: 'E464.2', label: '', info: '' },
  { addr: 'E464.3', label: '', info: '' },
  { addr: 'E464.4', label: 'FTH2', info: '' },
  { addr: 'E464.5', label: 'ASBK2', info: '' },
  { addr: 'E464.6', label: 'AH', info: '' },
  { addr: 'E464.7', label: 'MTCA', info: '' },
  { addr: 'E465.0', label: 'MTCB', info: '' },
  { addr: 'E465.1', label: '', info: '' },
  { addr: 'E465.2', label: 'SFT', info: '' },
  { addr: 'E465.3', label: 'RSI', info: '' },
  { addr: 'E465.4', label: 'DB32', info: '' },
  { addr: 'E465.5', label: 'DBHZ', info: '' },
  { addr: 'E465.6', label: 'FTAC', info: '' },
  { addr: 'E465.7', label: '', info: '' },
]
export const outputs0 = [
  { addr: 'A0.0', label: 'LKU', info: '' },
  { addr: 'A0.1', label: 'LEU', info: '' },
  { addr: 'A0.2', label: 'LBU', info: '' },
  { addr: 'A0.3', label: 'RDY', info: '' },
  { addr: 'A0.4', label: 'RST', info: '' },
  { addr: 'A0.5', label: '', info: '' },
  { addr: 'A0.6', label: 'LA', info: '' },
  { addr: 'A0.7', label: 'RBU', info: '' },
  { addr: 'A1.0', label: 'LKU', info: '' },
  { addr: 'A1.1', label: 'LEU', info: '' },
  { addr: 'A1.2', label: 'LBU', info: '' },
  { addr: 'A1.3', label: 'RDY', info: '' },
  { addr: 'A1.4', label: 'RST', info: '' },
  { addr: 'A1.5', label: '', info: '' },
  { addr: 'A1.6', label: '', info: '' },
  { addr: 'A1.7', label: '', info: '' },
  { addr: 'A2.0', label: 'LST1', info: '' },
  { addr: 'A2.1', label: 'LST2', info: '' },
  { addr: 'A2.2', label: 'LST3', info: '' },
  { addr: 'A2.3', label: 'LST4', info: '' },
  { addr: 'A2.4', label: '', info: '' },
  { addr: 'A2.5', label: '', info: '' },
  { addr: 'A2.6', label: '', info: '' },
  { addr: 'A2.7', label: '', info: '' },
  { addr: 'A3.0', label: '', info: '' },
  { addr: 'A3.1', label: '', info: '' },
  { addr: 'A3.2', label: '', info: '' },
  { addr: 'A3.3', label: '', info: '' },
  { addr: 'A3.4', label: '', info: '' },
  { addr: 'A3.5', label: '', info: '' },
  { addr: 'A3.6', label: '', info: '' },
  { addr: 'A3.7', label: '', info: '' },
]
export const outputs1 = [
  { addr: 'A100.0', label: 'SBK1', info: '' },
  { addr: 'A100.1', label: 'KBA11', info: '' },
  { addr: 'A100.2', label: 'SPE', info: '' },
  { addr: 'A100.3', label: 'SZE', info: '' },
  { addr: 'A100.4', label: 'SOE', info: '' },
  { addr: 'A100.5', label: 'SPA', info: '' },
  { addr: 'A100.6', label: 'SZA', info: '' },
  { addr: 'A100.7', label: 'SOA', info: '' },
  { addr: 'A101.0', label: 'L1', info: '' },
  { addr: 'A101.1', label: 'L2', info: '' },
  { addr: 'A101.2', label: 'L3', info: '' },
  { addr: 'A101.3', label: 'L4', info: '' },
  { addr: 'A101.4', label: 'L5', info: '' },
  { addr: 'A101.5', label: 'RFE', info: '' },
  { addr: 'A101.6', label: 'RFA', info: '' },
  { addr: 'A101.7', label: 'RLN', info: '' },
  { addr: 'A102.0', label: '', info: '' },
  { addr: 'A102.1', label: 'SBK2', info: '' },
  { addr: 'A102.2', label: 'SCA', info: '' },
  { addr: 'A102.3', label: 'SCB', info: '' },
  { addr: 'A102.4', label: 'SMA', info: '' },
  { addr: 'A102.5', label: 'SMB', info: '' },
  { addr: 'A102.6', label: 'LA', info: '' },
  { addr: 'A102.7', label: 'LC', info: '' },
  { addr: 'A103.0', label: 'SPBE', info: '' },
  { addr: 'A103.1', label: 'SBZE', info: '' },
  { addr: 'A103.2', label: 'SBOE', info: '' },
  { addr: 'A103.3', label: 'SPBA', info: '' },
  { addr: 'A103.4', label: 'SBZA', info: '' },
  { addr: 'A103.5', label: 'SBOA', info: '' },
  { addr: 'A103.6', label: '', info: '' },
  { addr: 'A103.7', label: '', info: '' },
  { addr: 'A104.0', label: 'TLIVA', info: '' },
  { addr: 'A104.1', label: 'KBA12', info: '' },
  { addr: 'A104.2', label: 'TLIVB', info: '' },
  { addr: 'A104.3', label: 'KBA2', info: '' },
  { addr: 'A104.4', label: 'SQA', info: '' },
  { addr: 'A104.5', label: '', info: '' },
  { addr: 'A104.6', label: '', info: '' },
  { addr: 'A104.7', label: '', info: '' },
  { addr: 'A105.0', label: '', info: '' },
  { addr: 'A105.1', label: '', info: '' },
  { addr: 'A105.2', label: '', info: '' },
  { addr: 'A105.3', label: '', info: '' },
  { addr: 'A105.4', label: '', info: '' },
  { addr: 'A105.5', label: '', info: '' },
  { addr: 'A105.6', label: '', info: '' },
  { addr: 'A105.7', label: '', info: '' },
  { addr: 'A106.0', label: 'A', info: '' },
  { addr: 'A106.1', label: 'B', info: '' },
  { addr: 'A106.2', label: 'C', info: '' },
  { addr: 'A106.3', label: 'D', info: '' },
  { addr: 'A106.4', label: 'AD1', info: '' },
  { addr: 'A106.5', label: 'AD2', info: '' },
  { addr: 'A106.6', label: 'AD3', info: '' },
  { addr: 'A106.7', label: 'STR', info: '' },
  { addr: 'A107.0', label: 'LKE', info: '' },
  { addr: 'A107.1', label: 'LEE', info: '' },
  { addr: 'A107.2', label: 'LBE', info: '' },
  { addr: 'A107.3', label: 'RDY', info: '' },
  { addr: 'A107.4', label: 'RST', info: '' },
  { addr: 'A107.5', label: '', info: '' },
  { addr: 'A107.6', label: '', info: '' },
  { addr: 'A107.7', label: 'RBE', info: '' },
]
export const outputs2 = [
  { addr: 'A160.0', label: 'A', info: '' },
  { addr: 'A160.1', label: 'B', info: '' },
  { addr: 'A160.2', label: 'C', info: '' },
  { addr: 'A160.3', label: 'D', info: '' },
  { addr: 'A160.4', label: 'AD1', info: '' },
  { addr: 'A160.5', label: 'AD2', info: '' },
  { addr: 'A160.6', label: 'AD3', info: '' },
  { addr: 'A160.7', label: 'STR', info: '' },
  { addr: 'A161.0', label: '', info: '' },
  { addr: 'A161.1', label: '', info: '' },
  { addr: 'A161.2', label: '', info: '' },
  { addr: 'A161.3', label: '', info: '' },
  { addr: 'A161.4', label: '', info: '' },
  { addr: 'A161.5', label: '', info: '' },
  { addr: 'A161.6', label: 'LA', info: '' },
  { addr: 'A161.7', label: 'LC', info: '' },
  { addr: 'A162.0', label: 'T10', info: '' },
  { addr: 'A162.1', label: 'TCA', info: '' },
  { addr: 'A162.2', label: 'TRA', info: '' },
  { addr: 'A162.3', label: 'TRB', info: '' },
  { addr: 'A162.4', label: 'TSA', info: '' },
  { addr: 'A162.5', label: 'TBVA', info: '' },
  { addr: 'A162.6', label: 'TBHA', info: '' },
  { addr: 'A162.7', label: 'T2A', info: '' },
  { addr: 'A163.0', label: '', info: '' },
  { addr: 'A163.1', label: 'TCB', info: '' },
  { addr: 'A163.2', label: 'TRA', info: '' },
  { addr: 'A163.3', label: 'TRB', info: '' },
  { addr: 'A163.4', label: 'TSB', info: '' },
  { addr: 'A163.5', label: 'TBVB', info: '' },
  { addr: 'A163.6', label: 'TBHB', info: '' },
  { addr: 'A163.7', label: 'T2B', info: '' },
]
export const outputs3 = [
  { addr: 'A200.0', label: 'SBK1', info: '' },
  { addr: 'A200.1', label: 'KBA11', info: '' },
  { addr: 'A200.2', label: 'SPE', info: '' },
  { addr: 'A200.3', label: 'SZE', info: '' },
  { addr: 'A200.4', label: 'SOE', info: '' },
  { addr: 'A200.5', label: 'SPA', info: '' },
  { addr: 'A200.6', label: 'SZA', info: '' },
  { addr: 'A200.7', label: 'SOA', info: '' },
  { addr: 'A201.0', label: 'L1', info: '' },
  { addr: 'A201.1', label: 'L2', info: '' },
  { addr: 'A201.2', label: 'L3', info: '' },
  { addr: 'A201.3', label: 'L4', info: '' },
  { addr: 'A201.4', label: 'L5', info: '' },
  { addr: 'A201.5', label: 'RFE', info: '' },
  { addr: 'A201.6', label: 'RFA', info: '' },
  { addr: 'A201.7', label: 'RLN', info: '' },
  { addr: 'A202.0', label: '', info: '' },
  { addr: 'A202.1', label: 'SBK2', info: '' },
  { addr: 'A202.2', label: 'SCA', info: '' },
  { addr: 'A202.3', label: 'SCB', info: '' },
  { addr: 'A202.4', label: 'SMA', info: '' },
  { addr: 'A202.5', label: 'SMB', info: '' },
  { addr: 'A202.6', label: 'LA', info: '' },
  { addr: 'A202.7', label: 'LC', info: '' },
  { addr: 'A203.0', label: 'SPBE', info: '' },
  { addr: 'A203.1', label: 'SBZE', info: '' },
  { addr: 'A203.2', label: 'SBOE', info: '' },
  { addr: 'A203.3', label: 'SPBA', info: '' },
  { addr: 'A203.4', label: 'SBZA', info: '' },
  { addr: 'A203.5', label: 'SBOA', info: '' },
  { addr: 'A203.6', label: '', info: '' },
  { addr: 'A203.7', label: '', info: '' },
  { addr: 'A204.0', label: 'TLIVA', info: '' },
  { addr: 'A204.1', label: 'KBA12', info: '' },
  { addr: 'A204.2', label: 'TLIVB', info: '' },
  { addr: 'A204.3', label: 'KBA2', info: '' },
  { addr: 'A204.4', label: 'SQA', info: '' },
  { addr: 'A204.5', label: '', info: '' },
  { addr: 'A204.6', label: '', info: '' },
  { addr: 'A204.7', label: '', info: '' },
  { addr: 'A205.0', label: '', info: '' },
  { addr: 'A205.1', label: '', info: '' },
  { addr: 'A205.2', label: '', info: '' },
  { addr: 'A205.3', label: '', info: '' },
  { addr: 'A205.4', label: '', info: '' },
  { addr: 'A205.5', label: '', info: '' },
  { addr: 'A205.6', label: '', info: '' },
  { addr: 'A205.7', label: '', info: '' },
  { addr: 'A206.0', label: 'A', info: '' },
  { addr: 'A206.1', label: 'B', info: '' },
  { addr: 'A206.2', label: 'C', info: '' },
  { addr: 'A206.3', label: 'D', info: '' },
  { addr: 'A206.4', label: 'AD1', info: '' },
  { addr: 'A206.5', label: 'AD2', info: '' },
  { addr: 'A206.6', label: 'AD3', info: '' },
  { addr: 'A206.7', label: 'STR', info: '' },
  { addr: 'A207.0', label: 'LKE', info: '' },
  { addr: 'A207.1', label: 'LEE', info: '' },
  { addr: 'A207.2', label: 'LBE', info: '' },
  { addr: 'A207.3', label: 'RDY', info: '' },
  { addr: 'A207.4', label: 'RST', info: '' },
  { addr: 'A207.5', label: '', info: '' },
  { addr: 'A207.6', label: '', info: '' },
  { addr: 'A207.7', label: 'RBE', info: '' },
]
export const outputs4 = [
  { addr: 'A260.0', label: 'A', info: '' },
  { addr: 'A260.1', label: 'B', info: '' },
  { addr: 'A260.2', label: 'C', info: '' },
  { addr: 'A260.3', label: 'D', info: '' },
  { addr: 'A260.4', label: 'AD1', info: '' },
  { addr: 'A260.5', label: 'AD2', info: '' },
  { addr: 'A260.6', label: 'AD3', info: '' },
  { addr: 'A260.7', label: 'STR', info: '' },
  { addr: 'A261.0', label: '', info: '' },
  { addr: 'A261.1', label: '', info: '' },
  { addr: 'A261.2', label: '', info: '' },
  { addr: 'A261.3', label: '', info: '' },
  { addr: 'A261.4', label: '', info: '' },
  { addr: 'A261.5', label: '', info: '' },
  { addr: 'A261.6', label: 'LA', info: '' },
  { addr: 'A261.7', label: 'LC', info: '' },
  { addr: 'A262.0', label: 'T10', info: '' },
  { addr: 'A262.1', label: 'TCA', info: '' },
  { addr: 'A262.2', label: 'TRA', info: '' },
  { addr: 'A262.3', label: 'TRB', info: '' },
  { addr: 'A262.4', label: 'TSA', info: '' },
  { addr: 'A262.5', label: 'TBVA', info: '' },
  { addr: 'A262.6', label: 'TBHA', info: '' },
  { addr: 'A262.7', label: 'T2A', info: '' },
  { addr: 'A263.0', label: '', info: '' },
  { addr: 'A263.1', label: 'TCB', info: '' },
  { addr: 'A263.2', label: 'TRA', info: '' },
  { addr: 'A263.3', label: 'TRB', info: '' },
  { addr: 'A263.4', label: 'TSB', info: '' },
  { addr: 'A263.5', label: 'TBVB', info: '' },
  { addr: 'A263.6', label: 'TBHB', info: '' },
  { addr: 'A263.7', label: 'T2B', info: '' },
]
export const outputs5 = [
  { addr: 'A300.0', label: 'SBK1', info: '' },
  { addr: 'A300.1', label: 'KBA11', info: '' },
  { addr: 'A300.2', label: 'SPE', info: '' },
  { addr: 'A300.3', label: 'SZE', info: '' },
  { addr: 'A300.4', label: 'SOE', info: '' },
  { addr: 'A300.5', label: 'SPA', info: '' },
  { addr: 'A300.6', label: 'SZA', info: '' },
  { addr: 'A300.7', label: 'SOA', info: '' },
  { addr: 'A301.0', label: 'L1', info: '' },
  { addr: 'A301.1', label: 'L2', info: '' },
  { addr: 'A301.2', label: 'L3', info: '' },
  { addr: 'A301.3', label: 'L4', info: '' },
  { addr: 'A301.4', label: 'L5', info: '' },
  { addr: 'A301.5', label: 'RFE', info: '' },
  { addr: 'A301.6', label: 'RFA', info: '' },
  { addr: 'A301.7', label: 'RLN', info: '' },
  { addr: 'A302.0', label: '', info: '' },
  { addr: 'A302.1', label: 'SBK2', info: '' },
  { addr: 'A302.2', label: 'SCA', info: '' },
  { addr: 'A302.3', label: 'SCB', info: '' },
  { addr: 'A302.4', label: 'SMA', info: '' },
  { addr: 'A302.5', label: 'SMB', info: '' },
  { addr: 'A302.6', label: 'LA', info: '' },
  { addr: 'A302.7', label: 'LC', info: '' },
  { addr: 'A303.0', label: 'SPBE', info: '' },
  { addr: 'A303.1', label: 'SBZE', info: '' },
  { addr: 'A303.2', label: 'SBOE', info: '' },
  { addr: 'A303.3', label: 'SPBA', info: '' },
  { addr: 'A303.4', label: 'SBZA', info: '' },
  { addr: 'A303.5', label: 'SBOA', info: '' },
  { addr: 'A303.6', label: '', info: '' },
  { addr: 'A303.7', label: '', info: '' },
  { addr: 'A304.0', label: 'TLIVA', info: '' },
  { addr: 'A304.1', label: 'KBA12', info: '' },
  { addr: 'A304.2', label: 'TLIVB', info: '' },
  { addr: 'A304.3', label: 'KBA2', info: '' },
  { addr: 'A304.4', label: 'SQA', info: '' },
  { addr: 'A304.5', label: '', info: '' },
  { addr: 'A304.6', label: '', info: '' },
  { addr: 'A304.7', label: '', info: '' },
  { addr: 'A305.0', label: '', info: '' },
  { addr: 'A305.1', label: '', info: '' },
  { addr: 'A305.2', label: '', info: '' },
  { addr: 'A305.3', label: '', info: '' },
  { addr: 'A305.4', label: '', info: '' },
  { addr: 'A305.5', label: '', info: '' },
  { addr: 'A305.6', label: '', info: '' },
  { addr: 'A305.7', label: '', info: '' },
  { addr: 'A306.0', label: 'A', info: '' },
  { addr: 'A306.1', label: 'B', info: '' },
  { addr: 'A306.2', label: 'C', info: '' },
  { addr: 'A306.3', label: 'D', info: '' },
  { addr: 'A306.4', label: 'AD1', info: '' },
  { addr: 'A306.5', label: 'AD2', info: '' },
  { addr: 'A306.6', label: 'AD3', info: '' },
  { addr: 'A306.7', label: 'STR', info: '' },
  { addr: 'A307.0', label: 'LKE', info: '' },
  { addr: 'A307.1', label: 'LEE', info: '' },
  { addr: 'A307.2', label: 'LBE', info: '' },
  { addr: 'A307.3', label: 'RDY', info: '' },
  { addr: 'A307.4', label: 'RST', info: '' },
  { addr: 'A307.5', label: '', info: '' },
  { addr: 'A307.6', label: '', info: '' },
  { addr: 'A307.7', label: 'RBE', info: '' },
]
export const outputs6 = [
  { addr: 'A360.0', label: 'A', info: '' },
  { addr: 'A360.1', label: 'B', info: '' },
  { addr: 'A360.2', label: 'C', info: '' },
  { addr: 'A360.3', label: 'D', info: '' },
  { addr: 'A360.4', label: 'AD1', info: '' },
  { addr: 'A360.5', label: 'AD2', info: '' },
  { addr: 'A360.6', label: 'AD3', info: '' },
  { addr: 'A360.7', label: 'STR', info: '' },
  { addr: 'A361.0', label: '', info: '' },
  { addr: 'A361.1', label: '', info: '' },
  { addr: 'A361.2', label: '', info: '' },
  { addr: 'A361.3', label: '', info: '' },
  { addr: 'A361.4', label: '', info: '' },
  { addr: 'A361.5', label: '', info: '' },
  { addr: 'A361.6', label: 'LA', info: '' },
  { addr: 'A361.7', label: 'LC', info: '' },
  { addr: 'A362.0', label: 'T10', info: '' },
  { addr: 'A362.1', label: 'TCA', info: '' },
  { addr: 'A362.2', label: 'TRA', info: '' },
  { addr: 'A362.3', label: 'TRB', info: '' },
  { addr: 'A362.4', label: 'TSA', info: '' },
  { addr: 'A362.5', label: 'TBVA', info: '' },
  { addr: 'A362.6', label: 'TBHA', info: '' },
  { addr: 'A362.7', label: 'T2A', info: '' },
  { addr: 'A363.0', label: '', info: '' },
  { addr: 'A363.1', label: 'TCB', info: '' },
  { addr: 'A363.2', label: 'TRA', info: '' },
  { addr: 'A363.3', label: 'TRB', info: '' },
  { addr: 'A363.4', label: 'TSB', info: '' },
  { addr: 'A363.5', label: 'TBVB', info: '' },
  { addr: 'A363.6', label: 'TBHB', info: '' },
  { addr: 'A363.7', label: 'T2B', info: '' },
]
export const outputs7 = [
  { addr: 'A400.0', label: 'SBK1', info: '' },
  { addr: 'A400.1', label: 'KBA11', info: '' },
  { addr: 'A400.2', label: 'SPE', info: '' },
  { addr: 'A400.3', label: 'SZE', info: '' },
  { addr: 'A400.4', label: 'SOE', info: '' },
  { addr: 'A400.5', label: 'SPA', info: '' },
  { addr: 'A400.6', label: 'SZA', info: '' },
  { addr: 'A400.7', label: 'SOA', info: '' },
  { addr: 'A401.0', label: 'L1', info: '' },
  { addr: 'A401.1', label: 'L2', info: '' },
  { addr: 'A401.2', label: 'L3', info: '' },
  { addr: 'A401.3', label: 'L4', info: '' },
  { addr: 'A401.4', label: 'L5', info: '' },
  { addr: 'A401.5', label: 'RFE', info: '' },
  { addr: 'A401.6', label: 'RFA', info: '' },
  { addr: 'A401.7', label: 'RLN', info: '' },
  { addr: 'A402.0', label: '', info: '' },
  { addr: 'A402.1', label: 'SBK2', info: '' },
  { addr: 'A402.2', label: 'SCA', info: '' },
  { addr: 'A402.3', label: 'SCB', info: '' },
  { addr: 'A402.4', label: 'SMA', info: '' },
  { addr: 'A402.5', label: 'SMB', info: '' },
  { addr: 'A402.6', label: 'LA', info: '' },
  { addr: 'A402.7', label: 'LC', info: '' },
  { addr: 'A403.0', label: 'SPBE', info: '' },
  { addr: 'A403.1', label: 'SBZE', info: '' },
  { addr: 'A403.2', label: 'SBOE', info: '' },
  { addr: 'A403.3', label: 'SPBA', info: '' },
  { addr: 'A403.4', label: 'SBZA', info: '' },
  { addr: 'A403.5', label: 'SBOA', info: '' },
  { addr: 'A403.6', label: '', info: '' },
  { addr: 'A403.7', label: '', info: '' },
  { addr: 'A404.0', label: 'TLIVA', info: '' },
  { addr: 'A404.1', label: 'KBA12', info: '' },
  { addr: 'A404.2', label: 'TLIVB', info: '' },
  { addr: 'A404.3', label: 'KBA2', info: '' },
  { addr: 'A404.4', label: 'SQA', info: '' },
  { addr: 'A404.5', label: '', info: '' },
  { addr: 'A404.6', label: '', info: '' },
  { addr: 'A404.7', label: '', info: '' },
  { addr: 'A405.0', label: '', info: '' },
  { addr: 'A405.1', label: '', info: '' },
  { addr: 'A405.2', label: '', info: '' },
  { addr: 'A405.3', label: '', info: '' },
  { addr: 'A405.4', label: '', info: '' },
  { addr: 'A405.5', label: '', info: '' },
  { addr: 'A405.6', label: '', info: '' },
  { addr: 'A405.7', label: '', info: '' },
  { addr: 'A406.0', label: 'A', info: '' },
  { addr: 'A406.1', label: 'B', info: '' },
  { addr: 'A406.2', label: 'C', info: '' },
  { addr: 'A406.3', label: 'D', info: '' },
  { addr: 'A406.4', label: 'AD1', info: '' },
  { addr: 'A406.5', label: 'AD2', info: '' },
  { addr: 'A406.6', label: 'AD3', info: '' },
  { addr: 'A406.7', label: 'STR', info: '' },
  { addr: 'A407.0', label: 'LKE', info: '' },
  { addr: 'A407.1', label: 'LEE', info: '' },
  { addr: 'A407.2', label: 'LBE', info: '' },
  { addr: 'A407.3', label: 'RDY', info: '' },
  { addr: 'A407.4', label: 'RST', info: '' },
  { addr: 'A407.5', label: '', info: '' },
  { addr: 'A407.6', label: '', info: '' },
  { addr: 'A407.7', label: 'RBE', info: '' },
]
export const outputs8 = [
  { addr: 'A460.0', label: 'A', info: '' },
  { addr: 'A460.1', label: 'B', info: '' },
  { addr: 'A460.2', label: 'C', info: '' },
  { addr: 'A460.3', label: 'D', info: '' },
  { addr: 'A460.4', label: 'AD1', info: '' },
  { addr: 'A460.5', label: 'AD2', info: '' },
  { addr: 'A460.6', label: 'AD3', info: '' },
  { addr: 'A460.7', label: 'STR', info: '' },
  { addr: 'A461.0', label: '', info: '' },
  { addr: 'A461.1', label: '', info: '' },
  { addr: 'A461.2', label: '', info: '' },
  { addr: 'A461.3', label: '', info: '' },
  { addr: 'A461.4', label: '', info: '' },
  { addr: 'A461.5', label: '', info: '' },
  { addr: 'A461.6', label: 'LA', info: '' },
  { addr: 'A461.7', label: 'LC', info: '' },
  { addr: 'A462.0', label: 'T10', info: '' },
  { addr: 'A462.1', label: 'TCA', info: '' },
  { addr: 'A462.2', label: 'TRA', info: '' },
  { addr: 'A462.3', label: 'TRB', info: '' },
  { addr: 'A462.4', label: 'TSA', info: '' },
  { addr: 'A462.5', label: 'TBVA', info: '' },
  { addr: 'A462.6', label: 'TBHA', info: '' },
  { addr: 'A462.7', label: 'T2A', info: '' },
  { addr: 'A463.0', label: '', info: '' },
  { addr: 'A463.1', label: 'TCB', info: '' },
  { addr: 'A463.2', label: 'TRA', info: '' },
  { addr: 'A463.3', label: 'TRB', info: '' },
  { addr: 'A463.4', label: 'TSB', info: '' },
  { addr: 'A463.5', label: 'TBVB', info: '' },
  { addr: 'A463.6', label: 'TBHB', info: '' },
  { addr: 'A463.7', label: 'T2B', info: '' },
]
export const merkers1 = [
  { addr: 'M0.0', label: '', info: '' },
  { addr: 'M0.1', label: '', info: '' },
  { addr: 'M0.2', label: '', info: '' },
  { addr: 'M0.3', label: '', info: '' },
  { addr: 'M0.4', label: '', info: '' },
  { addr: 'M0.5', label: '', info: '' },
  { addr: 'M0.6', label: '', info: '' },
  { addr: 'M0.7', label: '', info: '' },
  { addr: 'M1.0', label: '', info: '' },
  { addr: 'M1.1', label: '', info: '' },
  { addr: 'M1.2', label: '', info: '' },
  { addr: 'M1.3', label: '', info: '' },
  { addr: 'M1.4', label: '', info: '' },
  { addr: 'M1.5', label: '', info: '' },
  { addr: 'M1.6', label: '', info: '' },
  { addr: 'M1.7', label: '', info: '' },
  { addr: 'M2.0', label: '', info: '' },
  { addr: 'M2.1', label: '', info: '' },
  { addr: 'M2.2', label: '', info: '' },
  { addr: 'M2.3', label: '', info: '' },
  { addr: 'M2.4', label: '', info: '' },
  { addr: 'M2.5', label: '', info: '' },
  { addr: 'M2.6', label: '', info: '' },
  { addr: 'M2.7', label: '', info: '' },
  { addr: 'M3.0', label: '', info: '' },
  { addr: 'M3.1', label: '', info: '' },
  { addr: 'M3.2', label: '', info: '' },
  { addr: 'M3.3', label: '', info: '' },
  { addr: 'M3.4', label: '', info: '' },
  { addr: 'M3.5', label: '', info: '' },
  { addr: 'M3.6', label: '', info: '' },
  { addr: 'M3.7', label: '', info: '' },
  { addr: 'M4.0', label: '', info: '' },
  { addr: 'M4.1', label: '', info: '' },
  { addr: 'M4.2', label: '', info: '' },
  { addr: 'M4.3', label: '', info: '' },
  { addr: 'M4.4', label: '', info: '' },
  { addr: 'M4.5', label: '', info: '' },
  { addr: 'M4.6', label: '', info: '' },
  { addr: 'M4.7', label: '', info: '' },
  { addr: 'M5.0', label: '', info: '' },
  { addr: 'M5.1', label: '', info: '' },
  { addr: 'M5.2', label: '', info: '' },
  { addr: 'M5.3', label: '', info: '' },
  { addr: 'M5.4', label: '', info: '' },
  { addr: 'M5.5', label: '', info: '' },
  { addr: 'M5.6', label: '', info: '' },
  { addr: 'M5.7', label: '', info: '' },
  { addr: 'M6.0', label: '', info: '' },
  { addr: 'M6.1', label: '', info: '' },
  { addr: 'M6.2', label: '', info: '' },
  { addr: 'M6.3', label: '', info: '' },
  { addr: 'M6.4', label: '', info: '' },
  { addr: 'M6.5', label: '', info: '' },
  { addr: 'M6.6', label: '', info: '' },
  { addr: 'M6.7', label: '', info: '' },
  { addr: 'M7.0', label: '', info: '' },
  { addr: 'M7.1', label: '', info: '' },
  { addr: 'M7.2', label: '', info: '' },
  { addr: 'M7.3', label: '', info: '' },
  { addr: 'M7.4', label: '', info: '' },
  { addr: 'M7.5', label: '', info: '' },
  { addr: 'M7.6', label: '', info: '' },
  { addr: 'M7.7', label: '', info: '' },
]
export const alarms1 = [
  { class: 'EL1', label: 'AL1', info: 'Time out elevator hoisting' },
  { class: 'EL1', label: 'AL2', info: 'Time out shuttle travelling' },
  { class: 'EL1', label: 'AL3', info: 'Time out trolley centering opening' },
  { class: 'EL1', label: 'AL4', info: 'Time out trolley hoisting' },
  { class: 'EL1', label: 'AL5', info: 'Time out trolley forks opening' },
  { class: 'EL1', label: 'AL6', info: 'Time out trolley forks closing' },
  { class: 'EL1', label: 'AL7', info: 'AL7' },
  { class: 'EL1', label: 'AL8', info: 'Time out trolley centering closing' },
  { class: 'EL1', label: 'AL9', info: 'Time out flap' },
  { class: 'EL1', label: 'AL10', info: 'Hoisting feedback (1)' },
  { class: 'EL1', label: 'AL11', info: 'Hoisting feedback (2)' },
  { class: 'EL1', label: 'AL12', info: 'Time out elevator locking' },
  { class: 'EL1', label: 'AL13', info: 'Time out exit door' },
  { class: 'EL1', label: 'AL14', info: 'Time out entry door' },
  { class: 'EL1', label: 'AL15', info: 'Time out exit barrier' },
  { class: 'EL1', label: 'AL16', info: 'Time out entry barrier' },
  { class: 'EL1', label: 'AL17', info: 'Flap motor thermic (AMC)' },
  { class: 'EL1', label: 'AL18', info: 'Hoisting brake motor thermic (ASBK)' },
  { class: 'EL1', label: 'AL19', info: 'Hoisting motor thermic (RTA)' },
  { class: 'EL1', label: 'AL20', info: 'Locking motor thermic (AMM)' },
  { class: 'EL1', label: 'AL21', info: 'Inverter 2 not ready' },
  { class: 'EL1', label: 'AL22', info: 'Entry door motor thermic (APE)' },
  { class: 'EL1', label: 'AL23', info: 'Entry barrier motor thermic (APBE)' },
  { class: 'EL1', label: 'AL24', info: 'Exit barrier motor thermic (APBA)' },
  { class: 'EL1', label: 'AL25', info: 'Exit door motor thermic (APA)' },
  { class: 'EL1', label: 'AL26', info: 'Trolley A 220VAC thermic (AF8A)' },
  { class: 'EL1', label: 'AL27', info: 'Trolley B 220VAC thermic (AF8B)' },
  { class: 'EL1', label: 'AL28', info: 'ASBK2 thermic' },
  { class: 'EL1', label: 'AL29', info: 'Shuttle travelling thermic (AH)' },
  { class: 'EL1', label: 'AL30', info: 'Trolley A motors thermic (MTCA)' },
  { class: 'EL1', label: 'AL31', info: 'Trolley B motors thermic (MTCB)' },
  { class: 'EL1', label: 'AL32', info: 'AL32' },
  { class: 'EL1', label: 'AL33', info: 'Locking EOM/EZM sensors' },
  { class: 'EL1', label: 'AL34', info: 'Trolley A RES/REH sensors' },
  { class: 'EL1', label: 'AL35', info: 'Trolley B RES/REH sensors' },
  { class: 'EL1', label: 'AL36', info: 'Elevator EFA/EFB sensors' },
  { class: 'EL1', label: 'AL37', info: 'Trolley cycle to entry' },
  { class: 'EL1', label: 'AL38', info: 'Trolley cycle to exit' },
  { class: 'EL1', label: 'AL39', info: 'Trolley cycle FTXV/FTXH sensors' },
  { class: 'EL1', label: 'AL40', info: 'Trolley cycle centering' },
  { class: 'EL1', label: 'AL41', info: 'AL41' },
  { class: 'EL1', label: 'AL42', info: 'AL42' },
  { class: 'EL1', label: 'AL43', info: 'Entry door EZE/EOE sensors' },
  { class: 'EL1', label: 'AL44', info: 'Exit door EZA/EOA sensors' },
  { class: 'EL1', label: 'AL45', info: 'Entry barrier EBZE/EBOE sensors' },
  { class: 'EL1', label: 'AL46', info: 'Exit barrier EBZA/EBOA sensors' },
  { class: 'EL1', label: 'AL47', info: 'Flap ECA/ECB sensors' },
  { class: 'EL1', label: 'AL48', info: 'AL48' },
  { class: 'EL1', label: 'AL49', info: 'Vertical laser 1 out of range' },
  { class: 'EL1', label: 'AL50', info: 'Vertical laser 2 out of range' },
  { class: 'EL1', label: 'AL51', info: 'Horizontal laser 1 out of range' },
  { class: 'EL1', label: 'AL52', info: 'Horizontal laser 2 out of range' },
  { class: 'EL1', label: 'AL53', info: 'Vertical lasers tolerance check' },
  { class: 'EL1', label: 'AL54', info: 'Horizontal lasers tolerance check' },
  { class: 'EL1', label: 'AL55', info: 'AL55' },
  { class: 'EL1', label: 'AL56', info: 'AL56' },
  { class: 'EL1', label: 'AL57', info: 'AL57' },
  { class: 'EL1', label: 'AL58', info: 'Trolley encoder check' },
  { class: 'EL1', label: 'AL59', info: 'Time out trolley 1° row' },
  { class: 'EL1', label: 'AL60', info: 'Time out trolley 2° row' },
  { class: 'EL1', label: 'AL61', info: 'Time out trolley Entry/Exit' },
  { class: 'EL1', label: 'AL62', info: 'Time out trolley B find wheel side V' },
  { class: 'EL1', label: 'AL63', info: 'Time out trolley B find wheel side H' },
  { class: 'EL1', label: 'AL64', info: 'Time out trolley B find EM' },
]
export const alarms2 = [
  { class: 'EL2', label: 'AL1', info: 'Time out elevator hoisting' },
  { class: 'EL2', label: 'AL2', info: 'Time out shuttle travelling' },
  { class: 'EL2', label: 'AL3', info: 'Time out trolley centering opening' },
  { class: 'EL2', label: 'AL4', info: 'Time out trolley hoisting' },
  { class: 'EL2', label: 'AL5', info: 'Time out trolley forks opening' },
  { class: 'EL2', label: 'AL6', info: 'Time out trolley forks closing' },
  { class: 'EL2', label: 'AL7', info: 'AL7' },
  { class: 'EL2', label: 'AL8', info: 'Time out trolley centering closing' },
  { class: 'EL2', label: 'AL9', info: 'Time out flap' },
  { class: 'EL2', label: 'AL10', info: 'Hoisting feedback (1)' },
  { class: 'EL2', label: 'AL11', info: 'Hoisting feedback (2)' },
  { class: 'EL2', label: 'AL12', info: 'Time out elevator locking' },
  { class: 'EL2', label: 'AL13', info: 'Time out exit door' },
  { class: 'EL2', label: 'AL14', info: 'Time out entry door' },
  { class: 'EL2', label: 'AL15', info: 'Time out exit barrier' },
  { class: 'EL2', label: 'AL16', info: 'Time out entry barrier' },
  { class: 'EL2', label: 'AL17', info: 'Flap motor thermic (AMC)' },
  { class: 'EL2', label: 'AL18', info: 'Hoisting brake motor thermic (ASBK)' },
  { class: 'EL2', label: 'AL19', info: 'Hoisting motor thermic (RTA)' },
  { class: 'EL2', label: 'AL20', info: 'Locking motor thermic (AMM)' },
  { class: 'EL2', label: 'AL21', info: 'Inverter 2 not ready' },
  { class: 'EL2', label: 'AL22', info: 'Entry door motor thermic (APE)' },
  { class: 'EL2', label: 'AL23', info: 'Entry barrier motor thermic (APBE)' },
  { class: 'EL2', label: 'AL24', info: 'Exit barrier motor thermic (APBA)' },
  { class: 'EL2', label: 'AL25', info: 'Exit door motor thermic (APA)' },
  { class: 'EL2', label: 'AL26', info: 'Trolley A 220VAC thermic (AF8A)' },
  { class: 'EL2', label: 'AL27', info: 'Trolley B 220VAC thermic (AF8B)' },
  { class: 'EL2', label: 'AL28', info: 'ASBK2 thermic' },
  { class: 'EL2', label: 'AL29', info: 'Shuttle travelling thermic (AH)' },
  { class: 'EL2', label: 'AL30', info: 'Trolley A motors thermic (MTCA)' },
  { class: 'EL2', label: 'AL31', info: 'Trolley B motors thermic (MTCB)' },
  { class: 'EL2', label: 'AL32', info: 'AL32' },
  { class: 'EL2', label: 'AL33', info: 'Locking EOM/EZM sensors' },
  { class: 'EL2', label: 'AL34', info: 'Trolley A RES/REH sensors' },
  { class: 'EL2', label: 'AL35', info: 'Trolley B RES/REH sensors' },
  { class: 'EL2', label: 'AL36', info: 'Elevator EFA/EFB sensors' },
  { class: 'EL2', label: 'AL37', info: 'Trolley cycle to entry' },
  { class: 'EL2', label: 'AL38', info: 'Trolley cycle to exit' },
  { class: 'EL2', label: 'AL39', info: 'Trolley cycle FTXV/FTXH sensors' },
  { class: 'EL2', label: 'AL40', info: 'Trolley cycle centering' },
  { class: 'EL2', label: 'AL41', info: 'AL41' },
  { class: 'EL2', label: 'AL42', info: 'AL42' },
  { class: 'EL2', label: 'AL43', info: 'Entry door EZE/EOE sensors' },
  { class: 'EL2', label: 'AL44', info: 'Exit door EZA/EOA sensors' },
  { class: 'EL2', label: 'AL45', info: 'Entry barrier EBZE/EBOE sensors' },
  { class: 'EL2', label: 'AL46', info: 'Exit barrier EBZA/EBOA sensors' },
  { class: 'EL2', label: 'AL47', info: 'Flap ECA/ECB sensors' },
  { class: 'EL2', label: 'AL48', info: 'AL48' },
  { class: 'EL2', label: 'AL49', info: 'Vertical laser 1 out of range' },
  { class: 'EL2', label: 'AL50', info: 'Vertical laser 2 out of range' },
  { class: 'EL2', label: 'AL51', info: 'Horizontal laser 1 out of range' },
  { class: 'EL2', label: 'AL52', info: 'Horizontal laser 2 out of range' },
  { class: 'EL2', label: 'AL53', info: 'Vertical lasers tolerance check' },
  { class: 'EL2', label: 'AL54', info: 'Horizontal lasers tolerance check' },
  { class: 'EL2', label: 'AL55', info: 'AL55' },
  { class: 'EL2', label: 'AL56', info: 'AL56' },
  { class: 'EL2', label: 'AL57', info: 'AL57' },
  { class: 'EL2', label: 'AL58', info: 'Trolley encoder check' },
  { class: 'EL2', label: 'AL59', info: 'Time out trolley 1° row' },
  { class: 'EL2', label: 'AL60', info: 'Time out trolley 2° row' },
  { class: 'EL2', label: 'AL61', info: 'Time out trolley Entry/Exit' },
  { class: 'EL2', label: 'AL62', info: 'Time out trolley B find wheel side V' },
  { class: 'EL2', label: 'AL63', info: 'Time out trolley B find wheel side H' },
  { class: 'EL2', label: 'AL64', info: 'Time out trolley B find EM' },
]
export const alarms3 = [
  { class: 'EL3', label: 'AL1', info: 'Time out elevator hoisting' },
  { class: 'EL3', label: 'AL2', info: 'Time out shuttle travelling' },
  { class: 'EL3', label: 'AL3', info: 'Time out trolley centering opening' },
  { class: 'EL3', label: 'AL4', info: 'Time out trolley hoisting' },
  { class: 'EL3', label: 'AL5', info: 'Time out trolley forks opening' },
  { class: 'EL3', label: 'AL6', info: 'Time out trolley forks closing' },
  { class: 'EL3', label: 'AL7', info: 'AL7' },
  { class: 'EL3', label: 'AL8', info: 'Time out trolley centering closing' },
  { class: 'EL3', label: 'AL9', info: 'Time out flap' },
  { class: 'EL3', label: 'AL10', info: 'Hoisting feedback (1)' },
  { class: 'EL3', label: 'AL11', info: 'Hoisting feedback (2)' },
  { class: 'EL3', label: 'AL12', info: 'Time out elevator locking' },
  { class: 'EL3', label: 'AL13', info: 'Time out exit door' },
  { class: 'EL3', label: 'AL14', info: 'Time out entry door' },
  { class: 'EL3', label: 'AL15', info: 'Time out exit barrier' },
  { class: 'EL3', label: 'AL16', info: 'Time out entry barrier' },
  { class: 'EL3', label: 'AL17', info: 'Flap motor thermic (AMC)' },
  { class: 'EL3', label: 'AL18', info: 'Hoisting brake motor thermic (ASBK)' },
  { class: 'EL3', label: 'AL19', info: 'Hoisting motor thermic (RTA)' },
  { class: 'EL3', label: 'AL20', info: 'Locking motor thermic (AMM)' },
  { class: 'EL3', label: 'AL21', info: 'Inverter 2 not ready' },
  { class: 'EL3', label: 'AL22', info: 'Entry door motor thermic (APE)' },
  { class: 'EL3', label: 'AL23', info: 'Entry barrier motor thermic (APBE)' },
  { class: 'EL3', label: 'AL24', info: 'Exit barrier motor thermic (APBA)' },
  { class: 'EL3', label: 'AL25', info: 'Exit door motor thermic (APA)' },
  { class: 'EL3', label: 'AL26', info: 'Trolley A 220VAC thermic (AF8A)' },
  { class: 'EL3', label: 'AL27', info: 'Trolley B 220VAC thermic (AF8B)' },
  { class: 'EL3', label: 'AL28', info: 'ASBK2 thermic' },
  { class: 'EL3', label: 'AL29', info: 'Shuttle travelling thermic (AH)' },
  { class: 'EL3', label: 'AL30', info: 'Trolley A motors thermic (MTCA)' },
  { class: 'EL3', label: 'AL31', info: 'Trolley B motors thermic (MTCB)' },
  { class: 'EL3', label: 'AL32', info: 'AL32' },
  { class: 'EL3', label: 'AL33', info: 'Locking EOM/EZM sensors' },
  { class: 'EL3', label: 'AL34', info: 'Trolley A RES/REH sensors' },
  { class: 'EL3', label: 'AL35', info: 'Trolley B RES/REH sensors' },
  { class: 'EL3', label: 'AL36', info: 'Elevator EFA/EFB sensors' },
  { class: 'EL3', label: 'AL37', info: 'Trolley cycle to entry' },
  { class: 'EL3', label: 'AL38', info: 'Trolley cycle to exit' },
  { class: 'EL3', label: 'AL39', info: 'Trolley cycle FTXV/FTXH sensors' },
  { class: 'EL3', label: 'AL40', info: 'Trolley cycle centering' },
  { class: 'EL3', label: 'AL41', info: 'AL41' },
  { class: 'EL3', label: 'AL42', info: 'AL42' },
  { class: 'EL3', label: 'AL43', info: 'Entry door EZE/EOE sensors' },
  { class: 'EL3', label: 'AL44', info: 'Exit door EZA/EOA sensors' },
  { class: 'EL3', label: 'AL45', info: 'Entry barrier EBZE/EBOE sensors' },
  { class: 'EL3', label: 'AL46', info: 'Exit barrier EBZA/EBOA sensors' },
  { class: 'EL3', label: 'AL47', info: 'Flap ECA/ECB sensors' },
  { class: 'EL3', label: 'AL48', info: 'AL48' },
  { class: 'EL3', label: 'AL49', info: 'Vertical laser 1 out of range' },
  { class: 'EL3', label: 'AL50', info: 'Vertical laser 2 out of range' },
  { class: 'EL3', label: 'AL51', info: 'Horizontal laser 1 out of range' },
  { class: 'EL3', label: 'AL52', info: 'Horizontal laser 2 out of range' },
  { class: 'EL3', label: 'AL53', info: 'Vertical lasers tolerance check' },
  { class: 'EL3', label: 'AL54', info: 'Horizontal lasers tolerance check' },
  { class: 'EL3', label: 'AL55', info: 'AL55' },
  { class: 'EL3', label: 'AL56', info: 'AL56' },
  { class: 'EL3', label: 'AL57', info: 'AL57' },
  { class: 'EL3', label: 'AL58', info: 'Trolley encoder check' },
  { class: 'EL3', label: 'AL59', info: 'Time out trolley 1° row' },
  { class: 'EL3', label: 'AL60', info: 'Time out trolley 2° row' },
  { class: 'EL3', label: 'AL61', info: 'Time out trolley Entry/Exit' },
  { class: 'EL3', label: 'AL62', info: 'Time out trolley B find wheel side V' },
  { class: 'EL3', label: 'AL63', info: 'Time out trolley B find wheel side H' },
  { class: 'EL3', label: 'AL64', info: 'Time out trolley B find EM' },
]
export const alarms4 = [
  { class: 'EL4', label: 'AL1', info: 'Time out elevator hoisting' },
  { class: 'EL4', label: 'AL2', info: 'Time out shuttle travelling' },
  { class: 'EL4', label: 'AL3', info: 'Time out trolley centering opening' },
  { class: 'EL4', label: 'AL4', info: 'Time out trolley hoisting' },
  { class: 'EL4', label: 'AL5', info: 'Time out trolley forks opening' },
  { class: 'EL4', label: 'AL6', info: 'Time out trolley forks closing' },
  { class: 'EL4', label: 'AL7', info: 'AL7' },
  { class: 'EL4', label: 'AL8', info: 'Time out trolley centering closing' },
  { class: 'EL4', label: 'AL9', info: 'Time out flap' },
  { class: 'EL4', label: 'AL10', info: 'Hoisting feedback (1)' },
  { class: 'EL4', label: 'AL11', info: 'Hoisting feedback (2)' },
  { class: 'EL4', label: 'AL12', info: 'Time out elevator locking' },
  { class: 'EL4', label: 'AL13', info: 'Time out exit door' },
  { class: 'EL4', label: 'AL14', info: 'Time out entry door' },
  { class: 'EL4', label: 'AL15', info: 'Time out exit barrier' },
  { class: 'EL4', label: 'AL16', info: 'Time out entry barrier' },
  { class: 'EL4', label: 'AL17', info: 'Flap motor thermic (AMC)' },
  { class: 'EL4', label: 'AL18', info: 'Hoisting brake motor thermic (ASBK)' },
  { class: 'EL4', label: 'AL19', info: 'Hoisting motor thermic (RTA)' },
  { class: 'EL4', label: 'AL20', info: 'Locking motor thermic (AMM)' },
  { class: 'EL4', label: 'AL21', info: 'Inverter 2 not ready' },
  { class: 'EL4', label: 'AL22', info: 'Entry door motor thermic (APE)' },
  { class: 'EL4', label: 'AL23', info: 'Entry barrier motor thermic (APBE)' },
  { class: 'EL4', label: 'AL24', info: 'Exit barrier motor thermic (APBA)' },
  { class: 'EL4', label: 'AL25', info: 'Exit door motor thermic (APA)' },
  { class: 'EL4', label: 'AL26', info: 'Trolley A 220VAC thermic (AF8A)' },
  { class: 'EL4', label: 'AL27', info: 'Trolley B 220VAC thermic (AF8B)' },
  { class: 'EL4', label: 'AL28', info: 'ASBK2 thermic' },
  { class: 'EL4', label: 'AL29', info: 'Shuttle travelling thermic (AH)' },
  { class: 'EL4', label: 'AL30', info: 'Trolley A motors thermic (MTCA)' },
  { class: 'EL4', label: 'AL31', info: 'Trolley B motors thermic (MTCB)' },
  { class: 'EL4', label: 'AL32', info: 'AL32' },
  { class: 'EL4', label: 'AL33', info: 'Locking EOM/EZM sensors' },
  { class: 'EL4', label: 'AL34', info: 'Trolley A RES/REH sensors' },
  { class: 'EL4', label: 'AL35', info: 'Trolley B RES/REH sensors' },
  { class: 'EL4', label: 'AL36', info: 'Elevator EFA/EFB sensors' },
  { class: 'EL4', label: 'AL37', info: 'Trolley cycle to entry' },
  { class: 'EL4', label: 'AL38', info: 'Trolley cycle to exit' },
  { class: 'EL4', label: 'AL39', info: 'Trolley cycle FTXV/FTXH sensors' },
  { class: 'EL4', label: 'AL40', info: 'Trolley cycle centering' },
  { class: 'EL4', label: 'AL41', info: 'AL41' },
  { class: 'EL4', label: 'AL42', info: 'AL42' },
  { class: 'EL4', label: 'AL43', info: 'Entry door EZE/EOE sensors' },
  { class: 'EL4', label: 'AL44', info: 'Exit door EZA/EOA sensors' },
  { class: 'EL4', label: 'AL45', info: 'Entry barrier EBZE/EBOE sensors' },
  { class: 'EL4', label: 'AL46', info: 'Exit barrier EBZA/EBOA sensors' },
  { class: 'EL4', label: 'AL47', info: 'Flap ECA/ECB sensors' },
  { class: 'EL4', label: 'AL48', info: 'AL48' },
  { class: 'EL4', label: 'AL49', info: 'Vertical laser 1 out of range' },
  { class: 'EL4', label: 'AL50', info: 'Vertical laser 2 out of range' },
  { class: 'EL4', label: 'AL51', info: 'Horizontal laser 1 out of range' },
  { class: 'EL4', label: 'AL52', info: 'Horizontal laser 2 out of range' },
  { class: 'EL4', label: 'AL53', info: 'Vertical lasers tolerance check' },
  { class: 'EL4', label: 'AL54', info: 'Horizontal lasers tolerance check' },
  { class: 'EL4', label: 'AL55', info: 'AL55' },
  { class: 'EL4', label: 'AL56', info: 'AL56' },
  { class: 'EL4', label: 'AL57', info: 'AL57' },
  { class: 'EL4', label: 'AL58', info: 'Trolley encoder check' },
  { class: 'EL4', label: 'AL59', info: 'Time out trolley 1° row' },
  { class: 'EL4', label: 'AL60', info: 'Time out trolley 2° row' },
  { class: 'EL4', label: 'AL61', info: 'Time out trolley Entry/Exit' },
  { class: 'EL4', label: 'AL62', info: 'Time out trolley B find wheel side V' },
  { class: 'EL4', label: 'AL63', info: 'Time out trolley B find wheel side H' },
  { class: 'EL4', label: 'AL64', info: 'Time out trolley B find EM' },
]
