export const devices = [
  'Elevatore (A)',
  'Elevatore (B)',
  'Torre (T)'
]

export const modes = [
  '---',
  'Introduzione',
  'Lettura Dati',
  'Emergenza 1',
  'Emergenza 2',
  'Mappa',
  'Passo-Passo',
  'Preset',
  'Automatico'
]

export const operations = [
  '---',
  'Allarme on',
  'Allarme off',
  'Cambio Funzione',
  'Codice PIN tesera modificato',
  'Ciclo deposito',
  'Ciclo ritiro',
  'Ciclo scambio deposito',
  'Ciclo scambio ritiro',
  '---',
  'Richiesta entrata',
  'Richiesta uscita',
  '---',
  '---',
  '---',
  '---'
]

export const measures = [
  'Laser V1',
  'Laser V2',
  'Laser H1',
  'Laser H2'
]

export const inputs1 = [
  { addr: 'E0.0', label: 'A', info: 'Tastiera esadecimale - A' },
  { addr: 'E0.1', label: 'B', info: 'Tastiera esadecimale - B' },
  { addr: 'E0.2', label: 'C', info: 'Tastiera esadecimale - C' },
  { addr: 'E0.3', label: 'D', info: 'Tastiera esadecimale - D' },
  { addr: 'E0.4', label: 'OK', info: 'Tastiera esadecimale - OK' },
  { addr: 'E0.5', label: 'S2', info: 'Selettore cambio funzione' },
  { addr: 'E0.6', label: 'S2', info: 'Selettore cambio funzione' },
  { addr: 'E0.7', label: 'S2', info: 'Selettore cambio funzione' },
  { addr: 'E1.0', label: 'A', info: 'Lettore di uscita - Tastiera esadecimale - A' },
  { addr: 'E1.1', label: 'B', info: 'Lettore di uscita - Tastiera esadecimale - B' },
  { addr: 'E1.2', label: 'C', info: 'Lettore di uscita - Tastiera esadecimale - C' },
  { addr: 'E1.3', label: 'D', info: 'Lettore di uscita - Tastiera esadecimale - D' },
  { addr: 'E1.4', label: 'STR', info: 'Lettore di uscita' },
  { addr: 'E1.5', label: 'OK', info: 'Lettore di uscita - Tastiera esadecimale - OK' },
  { addr: 'E1.6', label: 'DAT', info: 'Lettore di uscita' },
  { addr: 'E1.7', label: 'UC', info: 'Pulsante conferma comando' },
  { addr: 'E2.0', label: 'FE1', info: 'Fusibile 24VDC' },
  { addr: 'E2.1', label: 'SA', info: 'Selettore Man / Aut' },
  { addr: 'E2.2', label: '', info: '' },
  { addr: 'E2.3', label: 'RSI', info: 'Sistema pronto' },
  { addr: 'E2.4', label: '', info: '' },
  { addr: 'E2.5', label: 'S1', info: 'Selettore cambio funzione' },
  { addr: 'E2.6', label: 'S1', info: 'Selettore cambio funzione' },
  { addr: 'E2.7', label: 'S1', info: 'Selettore cambio funzione' },
  { addr: 'E3.0', label: '', info: '' },
  { addr: 'E3.1', label: '', info: '' },
  { addr: 'E3.2', label: '', info: '' },
  { addr: 'E3.3', label: '', info: '' },
  { addr: 'E3.4', label: 'DB32', info: 'Abilitazione dati 1' },
  { addr: 'E3.5', label: 'DBHZ', info: 'Abilitazione dati 2' },
  { addr: 'E3.6', label: '', info: '' },
  { addr: 'E3.7', label: '', info: '' }
]
export const inputs2 = [
  { addr: 'E10.0', label: 'ECA', info: 'Finecorsa clappa alta' },
  { addr: 'E10.1', label: 'ECB', info: 'Finecorsa clappa bassa' },
  { addr: 'E10.2', label: 'AMC', info: 'Magnetotermico motore clappa' },
  { addr: 'E10.3', label: 'SPR', info: 'Spira presenza vettura' },
  { addr: 'E10.4', label: 'ADN', info: 'Magnetotermico motore rotazione' },
  { addr: 'E10.5', label: 'AD', info: 'Magnetotermico motore rotazione' },
  { addr: 'E10.6', label: 'ANV', info: 'Magnetotermico motore sollevamento' },
  { addr: 'E10.7', label: 'KEXPV', info: 'Elevatore posizione porta' },
  { addr: 'E11.0', label: 'EOM1', info: 'Finecorsa martinetto aperto' },
  { addr: 'E11.1', label: 'EZM1', info: 'Finecorsa martinetto chiuso' },
  { addr: 'E11.2', label: 'AMM1', info: 'Magnetotermico motore martinetto' },
  { addr: 'E11.3', label: 'EOM2', info: 'Finecorsa martinetto aperto' },
  { addr: 'E11.4', label: 'EZM2', info: 'Finecorsa martinetto chiuso' },
  { addr: 'E11.5', label: 'AMM2', info: 'Magnetotermico motore martinetto' },
  { addr: 'E11.6', label: 'IV1', info: 'Inverter 1 abilitato' },
  { addr: 'E11.7', label: 'FTC', info: 'Fotocellula controllo presenza carrello' },
  { addr: 'E12.0', label: 'MNA', info: 'Proximity sollevamento livellamento' },
  { addr: 'E12.1', label: 'MNB', info: 'Proximity sollevamento livellamento' },
  { addr: 'E12.2', label: 'EXPV', info: 'Proximity posizione piano alto' },
  { addr: 'E12.3', label: 'EFB', info: 'Proximity posizione piano basso' },
  { addr: 'E12.4', label: 'FRE', info: 'Fotocellula presenza ruota' },
  { addr: 'E12.5', label: 'KBA', info: 'Inverter abilitato' },
  { addr: 'E12.6', label: 'KEXP', info: 'Porta chiusa (safety' },
  { addr: 'E12.7', label: 'KEZ', info: 'Porta chiusa (safety)' },
  { addr: 'E13.0', label: 'A', info: 'Lettore di entrata - Tastiera esadecimale - A' },
  { addr: 'E13.1', label: 'B', info: 'Lettore di entrata - Tastiera esadecimale - B' },
  { addr: 'E13.2', label: 'C', info: 'Lettore di entrata - Tastiera esadecimale - C' },
  { addr: 'E13.3', label: 'D', info: 'Lettore di entrata - Tastiera esadecimale - D' },
  { addr: 'E13.4', label: 'STR', info: 'Lettore di entrata' },
  { addr: 'E13.5', label: 'OK', info: 'Lettore di entrata - Tastiera esadecimale - OK' },
  { addr: 'E13.6', label: 'DAT', info: 'Lettore di entrata' },
  { addr: 'E13.7', label: 'FE', info: 'Fusibile 24VDC' },
  { addr: 'E14.0', label: 'EZE', info: 'Finecorsa porta chiusa' },
  { addr: 'E14.1', label: 'EOE', info: 'Finecorsa porta aperta' },
  { addr: 'E14.2', label: 'FBE', info: 'Fotocellula porta' },
  { addr: 'E14.3', label: 'FPE', info: 'Fotocellula presenza vettura' },
  { addr: 'E14.4', label: 'FDR', info: 'Fotocellula largezza destra' },
  { addr: 'E14.5', label: 'FDL', info: 'Fotocellula larghezza sinistra' },
  { addr: 'E14.6', label: 'FTA1', info: 'Fotocellula altezza 1' },
  { addr: 'E14.7', label: 'FTA2', info: 'Fotocellula altezza 2' },
  { addr: 'E15.0', label: 'FLP', info: 'Fotocellula lunghezza posteriore' },
  { addr: 'E15.1', label: 'FLA', info: 'Fotocellula langhezza anteriore' },
  { addr: 'E15.2', label: 'RX', info: 'Radar' },
  { addr: 'E15.3', label: 'POD', info: 'Pulsante apertura porta' },
  { addr: 'E15.4', label: 'APE', info: 'Magnetotermico motore porta' },
  { addr: 'E15.5', label: 'PRST', info: 'Pulsante reset operazione' },
  { addr: 'E15.6', label: 'FTXV', info: 'Fotocellula interferenza elevatore' },
  { addr: 'E15.7', label: 'FTXH', info: 'Fotocellula interferenza elevatore' },
  { addr: 'E16.0', label: 'MDR', info: 'Proximity rotazione livellamento' },
  { addr: 'E16.1', label: 'MDL', info: 'Proximity rotazione livellamento' },
  { addr: 'E16.2', label: 'EDR', info: 'Proximity rotazione posizione 1' },
  { addr: 'E16.3', label: 'EDL', info: 'Proximity rotazione posizione 2' },
  { addr: 'E16.4', label: '', info: '' },
  { addr: 'E16.5', label: '', info: '' },
  { addr: 'E16.6', label: '', info: '' },
  { addr: 'E16.7', label: '', info: '' },
  { addr: 'E17.0', label: '', info: '' },
  { addr: 'E17.1', label: '', info: '' },
  { addr: 'E17.2', label: '', info: '' },
  { addr: 'E17.3', label: '', info: '' },
  { addr: 'E17.4', label: '', info: '' },
  { addr: 'E17.5', label: '', info: '' },
  { addr: 'E17.6', label: '', info: '' },
  { addr: 'E17.7', label: '', info: '' }
]
export const inputs3 = [
  { addr: 'E20.0', label: 'ECA', info: 'Finecorsa clappa alta' },
  { addr: 'E20.1', label: 'ECB', info: 'Finecorsa clappa bassa' },
  { addr: 'E20.2', label: 'AMC', info: 'Magnetotermico motore clappa' },
  { addr: 'E20.3', label: 'SPR', info: 'Spira presenza vettura' },
  { addr: 'E20.4', label: 'ADN', info: 'Magnetotermico motore rotazione' },
  { addr: 'E20.5', label: 'AD', info: 'Magnetotermico motore rotazione' },
  { addr: 'E20.6', label: 'ANV', info: 'Magnetotermico motore sollevamento' },
  { addr: 'E20.7', label: 'KEXPV', info: 'Elevatore posizione porta' },
  { addr: 'E21.0', label: 'EOM1', info: 'Finecorsa martinetto aperto' },
  { addr: 'E21.1', label: 'EZM1', info: 'Finecorsa martinetto chiuso' },
  { addr: 'E21.2', label: 'AMM1', info: 'Magnetotermico motore martinetto' },
  { addr: 'E21.3', label: 'EOM2', info: 'Finecorsa martinetto aperto' },
  { addr: 'E21.4', label: 'EZM2', info: 'Finecorsa martinetto chiuso' },
  { addr: 'E21.5', label: 'AMM2', info: 'Magnetotermico motore martinetto' },
  { addr: 'E21.6', label: 'IV1', info: 'Inverter 1 abilitato' },
  { addr: 'E21.7', label: 'FTC', info: 'Fotocellula controllo presenza carrello' },
  { addr: 'E22.0', label: 'MNA', info: 'Proximity sollevamento livellamento' },
  { addr: 'E22.1', label: 'MNB', info: 'Proximity sollevamento livellamento' },
  { addr: 'E22.2', label: 'EXPV', info: 'Proximity posizione piano alto' },
  { addr: 'E22.3', label: 'EFB', info: 'Proximity posizione piano basso' },
  { addr: 'E22.4', label: 'FRE', info: 'Fotocellula presenza ruota' },
  { addr: 'E22.5', label: 'KBA', info: 'Inverter abilitato' },
  { addr: 'E22.6', label: 'KEXP', info: 'Porta chiusa (safety' },
  { addr: 'E22.7', label: 'KEZ', info: 'Porta chiusa (safety)' },
  { addr: 'E23.0', label: 'A', info: 'Lettore di entrata - Tastiera esadecimale - A' },
  { addr: 'E23.1', label: 'B', info: 'Lettore di entrata - Tastiera esadecimale - B' },
  { addr: 'E23.2', label: 'C', info: 'Lettore di entrata - Tastiera esadecimale - C' },
  { addr: 'E23.3', label: 'D', info: 'Lettore di entrata - Tastiera esadecimale - D' },
  { addr: 'E23.4', label: 'STR', info: 'Lettore di entrata' },
  { addr: 'E23.5', label: 'OK', info: 'Lettore di entrata - Tastiera esadecimale - OK' },
  { addr: 'E23.6', label: 'DAT', info: 'Lettore di entrata' },
  { addr: 'E23.7', label: 'FE', info: 'Fusibile 24VDC' },
  { addr: 'E24.0', label: 'EZE', info: 'Finecorsa porta chiusa' },
  { addr: 'E24.1', label: 'EOE', info: 'Finecorsa porta aperta' },
  { addr: 'E24.2', label: 'FBE', info: 'Fotocellula porta' },
  { addr: 'E24.3', label: 'FPE', info: 'Fotocellula presenza vettura' },
  { addr: 'E24.4', label: 'FDR', info: 'Fotocellula largezza destra' },
  { addr: 'E24.5', label: 'FDL', info: 'Fotocellula larghezza sinistra' },
  { addr: 'E24.6', label: 'FTA1', info: 'Fotocellula altezza 1' },
  { addr: 'E24.7', label: 'FTA2', info: 'Fotocellula altezza 2' },
  { addr: 'E25.0', label: 'FLP', info: 'Fotocellula lunghezza posteriore' },
  { addr: 'E25.1', label: 'FLA', info: 'Fotocellula langhezza anteriore' },
  { addr: 'E25.2', label: 'RX', info: 'Radar' },
  { addr: 'E25.3', label: 'POD', info: 'Pulsante apertura porta' },
  { addr: 'E25.4', label: 'APE', info: 'Magnetotermico motore porta' },
  { addr: 'E25.5', label: 'PRST', info: 'Pulsante reset operazione' },
  { addr: 'E25.6', label: 'FTXV', info: 'Fotocellula interferenza elevatore' },
  { addr: 'E25.7', label: 'FTXH', info: 'Fotocellula interferenza elevatore' },
  { addr: 'E26.0', label: 'MDR', info: 'Proximity rotazione livellamento' },
  { addr: 'E26.1', label: 'MDL', info: 'Proximity rotazione livellamento' },
  { addr: 'E26.2', label: 'EDR', info: 'Proximity rotazione posizione 1' },
  { addr: 'E26.3', label: 'EDL', info: 'Proximity rotazione posizione 2' },
  { addr: 'E26.4', label: '', info: '' },
  { addr: 'E26.5', label: '', info: '' },
  { addr: 'E26.6', label: '', info: '' },
  { addr: 'E26.7', label: '', info: '' },
  { addr: 'E27.0', label: '', info: '' },
  { addr: 'E27.1', label: '', info: '' },
  { addr: 'E27.2', label: '', info: '' },
  { addr: 'E27.3', label: '', info: '' },
  { addr: 'E27.4', label: '', info: '' },
  { addr: 'E27.5', label: '', info: '' },
  { addr: 'E27.6', label: '', info: '' },
  { addr: 'E27.7', label: '', info: '' }
]
export const inputs4 = [
  { addr: 'E30.0', label: 'EHPA', info: 'Proximity posizione elevatore A' },
  { addr: 'E30.1', label: 'EHPB', info: 'Proximity posizione elevatore B' },
  { addr: 'E30.2', label: '', info: '' },
  { addr: 'E30.3', label: 'ASBK', info: 'Magnetotermico freno sollevamento' },
  { addr: 'E30.4', label: 'SBK', info: 'Feedback freno sollevameto' },
  { addr: 'E30.5', label: 'RTA', info: 'Termico motore sollevamento' },
  { addr: 'E30.6', label: 'FE1', info: 'Fusibile 24VDC' },
  { addr: 'E30.7', label: 'AF7', info: 'Linea 220V carrello' },
  { addr: 'E31.0', label: 'IV1', info: 'Inverter 1 abilitato' },
  { addr: 'E31.1', label: 'IV2', info: 'Inverter 2 abilitato' },
  { addr: 'E31.2', label: '', info: '' },
  { addr: 'E31.3', label: 'RSI', info: 'Sistema pronto' },
  { addr: 'E31.4', label: '', info: '' },
  { addr: 'E31.5', label: 'AH', info: 'Magnetotermico motori traslazione torre' },
  { addr: 'E31.6', label: 'AGF', info: 'Magnetotermico motori traslazione carrello' },
  { addr: 'E31.7', label: 'AKKP', info: 'Magnetotermico linea 380V' }
]
export const inputs5 = [
  { addr: 'E40.0', label: 'A', info: 'Tastiera esadecimale - A' },
  { addr: 'E40.1', label: 'B', info: 'Tastiera esadecimale - B' },
  { addr: 'E40.2', label: 'C', info: 'Tastiera esadecimale - C' },
  { addr: 'E40.3', label: 'D', info: 'Tastiera esadecimale - D' },
  { addr: 'E40.4', label: 'OK', info: 'Tastiera esadecimale - OK' },
  { addr: 'E40.5', label: 'S2', info: 'Selettore cambio funzione' },
  { addr: 'E40.6', label: 'S2', info: 'Selettore cambio funzione' },
  { addr: 'E40.7', label: 'S2', info: 'Selettore cambio funzione' },
  { addr: 'E41.0', label: 'EM', info: 'Carrello in centro' },
  { addr: 'E41.1', label: 'EXPV', info: 'Posizione piano alto' },
  { addr: 'E41.2', label: '', info: '' },
  { addr: 'E41.3', label: '', info: '' },
  { addr: 'E41.4', label: 'TCR', info: 'Feedback avvolgicavo' },
  { addr: 'E41.5', label: 'MTC', info: 'Magnetotermici carrello' },
  { addr: 'E41.6', label: 'FTXV', info: 'Fotocellula di interferenza' },
  { addr: 'E41.7', label: 'FTXH', info: 'Fotocellula di interferenza' },
  { addr: 'E42.0', label: 'RV', info: 'Fotocellula di interferenza' },
  { addr: 'E42.1', label: 'RH', info: 'Fotocellula di interferenza' },
  { addr: 'E42.2', label: 'RES', info: 'Finecorsa carrello alto' },
  { addr: 'E42.3', label: 'REH', info: 'Finecorsa carrello basso' },
  { addr: 'E42.4', label: 'RCV', info: 'Finecorsa carrello centratore chiuso' },
  { addr: 'E42.5', label: 'REAV', info: 'Finecorsa carrello arrivo centratura' },
  { addr: 'E42.6', label: 'REAH', info: 'Finecorsa carrello arrivo centratura' },
  { addr: 'E42.7', label: 'RCH', info: 'Finecorsa carrello centratore chiuso' },
  { addr: 'E43.0', label: '', info: '' },
  { addr: 'E43.1', label: '', info: '' },
  { addr: 'E43.2', label: 'SFA', info: 'Selettore Man / Aut' },
  { addr: 'E43.3', label: '', info: '' },
  { addr: 'E43.4', label: 'DB32', info: 'Abilitazione dati 1' },
  { addr: 'E43.5', label: 'DBHZ', info: 'Abilitazione dati 2' },
  { addr: 'E43.6', label: '', info: '' },
  { addr: 'E43.7', label: 'UC', info: 'Pulsante conferma comando' }
]
export const outputs1 = [
  { addr: 'A0.0', label: 'A', info: 'Display' },
  { addr: 'A0.1', label: 'B', info: 'Display' },
  { addr: 'A0.2', label: 'C', info: 'Display' },
  { addr: 'A0.3', label: 'D', info: 'Display' },
  { addr: 'A0.4', label: 'AD1', info: 'Display' },
  { addr: 'A0.5', label: 'AD2', info: 'Display' },
  { addr: 'A0.6', label: 'AD3', info: 'Display' },
  { addr: 'A0.7', label: 'STR', info: 'Display' },
  { addr: 'A1.0', label: 'LK', info: 'Lettore di uscita - Digitare codice' },
  { addr: 'A1.1', label: 'LE', info: 'Lettore di uscita - Errore' },
  { addr: 'A1.2', label: 'LB', info: 'Lettore di uscita - Operazione in corso' },
  { addr: 'A1.3', label: 'RDY', info: 'Lettore di uscita' },
  { addr: 'A1.4', label: 'RST', info: 'Lettore di uscita' },
  { addr: 'A1.5', label: 'RBU', info: 'Lettore di uscita 24VDC' },
  { addr: 'A1.6', label: 'LA', info: 'Allarme' },
  { addr: 'A1.7', label: 'LC', info: 'Sistema pronto' }
]
export const outputs2 = [
  { addr: 'A10.0', label: 'KEM', info: 'Modalità emergenza' },
  { addr: 'A10.1', label: 'KBA', info: 'Abilitazione inverter' },
  { addr: 'A10.2', label: 'KXPE', info: 'Abilitazione sollevamento' },
  { addr: 'A10.3', label: 'SQA', info: 'Motore sollevamento' },
  { addr: 'A10.4', label: 'TD', info: 'Motore rotazione' },
  { addr: 'A10.5', label: '', info: '' },
  { addr: 'A10.6', label: '', info: '' },
  { addr: 'A10.7', label: '', info: '' },
  { addr: 'A11.0', label: 'L1', info: 'Pannello luminoso (avanti)' },
  { addr: 'A11.1', label: 'L2', info: 'Pannello luminoso (stop)' },
  { addr: 'A11.2', label: 'L3', info: 'Pannello luminoso (indietro)' },
  { addr: 'A11.3', label: 'L4', info: 'Pannello luminoso (destra)' },
  { addr: 'A11.4', label: 'L5', info: 'Pannello luminoso (sinistra)' },
  { addr: 'A11.5', label: 'RFE', info: 'Semaforo' },
  { addr: 'A11.6', label: 'RLN', info: 'Luce di servizio' },
  { addr: 'A11.7', label: 'RBE', info: 'Lettore di entrata 24VDC' },
  { addr: 'A12.0', label: 'SCA', info: 'Motore clappa salita' },
  { addr: 'A12.1', label: 'SCB', info: 'Motore clappa discesa' },
  { addr: 'A12.2', label: 'SMA1', info: 'Motore martinetto blocca' },
  { addr: 'A12.3', label: 'SMB1', info: 'Motore martinetto libera' },
  { addr: 'A12.4', label: 'SMA2', info: 'Motore martinetto blocca' },
  { addr: 'A12.5', label: 'SMB2', info: 'Motore martinetto libera' },
  { addr: 'A12.6', label: '', info: '' },
  { addr: 'A12.7', label: 'LC', info: 'Sistema pronto' },
  { addr: 'A13.0', label: 'LK', info: 'Lettore di entrata - Digitare codice' },
  { addr: 'A13.1', label: 'LE', info: 'Lettore di entrata - Errore' },
  { addr: 'A13.2', label: 'LB', info: 'Lettore di entrata - Operazione in corso' },
  { addr: 'A13.3', label: 'RDY', info: 'Lettore di entrata' },
  { addr: 'A13.4', label: 'RST', info: 'Lettore di entrata' },
  { addr: 'A13.5', label: 'SDR', info: 'Motore rotazione livellamento (FWD)' },
  { addr: 'A13.6', label: 'SDL', info: 'Motore rotazione livellamento (BWD)' },
  { addr: 'A13.7', label: 'SDN', info: 'Motore rotazione livellamento' },
  { addr: 'A14.0', label: '', info: '' },
  { addr: 'A14.1', label: '', info: '' },
  { addr: 'A14.2', label: '', info: '' },
  { addr: 'A14.3', label: '', info: '' },
  { addr: 'A14.4', label: '', info: '' },
  { addr: 'A14.5', label: '', info: '' },
  { addr: 'A14.6', label: '', info: '' },
  { addr: 'A14.7', label: '', info: '' },
  { addr: 'A15.0', label: '', info: '' },
  { addr: 'A15.1', label: '', info: '' },
  { addr: 'A15.2', label: '', info: '' },
  { addr: 'A15.3', label: '', info: '' },
  { addr: 'A15.4', label: '', info: '' },
  { addr: 'A15.5', label: 'SNA', info: 'Motore sollevamento livellamento (FWD)' },
  { addr: 'A15.6', label: 'SNB', info: 'Motore sollevamento livellamento (BWD)' },
  { addr: 'A15.7', label: 'SNV', info: 'Motore sollevamento livellamento' }
]
export const outputs3 = [
  { addr: 'A20.0', label: 'KEM', info: 'Modalità emergenza' },
  { addr: 'A20.1', label: 'KBA', info: 'Abilitazione inverter' },
  { addr: 'A20.2', label: 'KXPE', info: 'Abilitazione sollevamento' },
  { addr: 'A20.3', label: 'SQA', info: 'Motore sollevamento' },
  { addr: 'A20.4', label: 'TD', info: 'Motore rotazione' },
  { addr: 'A20.5', label: '', info: '' },
  { addr: 'A20.6', label: '', info: '' },
  { addr: 'A20.7', label: '', info: '' },
  { addr: 'A21.0', label: 'L1', info: 'Pannello luminoso (avanti)' },
  { addr: 'A21.1', label: 'L2', info: 'Pannello luminoso (stop)' },
  { addr: 'A21.2', label: 'L3', info: 'Pannello luminoso (indietro)' },
  { addr: 'A21.3', label: 'L4', info: 'Pannello luminoso (destra)' },
  { addr: 'A21.4', label: 'L5', info: 'Pannello luminoso (sinistra)' },
  { addr: 'A21.5', label: 'RFE', info: 'Semaforo' },
  { addr: 'A21.6', label: 'RLN', info: 'Luce di servizio' },
  { addr: 'A21.7', label: 'RBE', info: 'Lettore di entrata 24VDC' },
  { addr: 'A22.0', label: 'SCA', info: 'Motore clappa salita' },
  { addr: 'A22.1', label: 'SCB', info: 'Motore clappa discesa' },
  { addr: 'A22.2', label: 'SMA1', info: 'Motore martinetto blocca' },
  { addr: 'A22.3', label: 'SMB1', info: 'Motore martinetto libera' },
  { addr: 'A22.4', label: 'SMA2', info: 'Motore martinetto blocca' },
  { addr: 'A22.5', label: 'SMB2', info: 'Motore martinetto libera' },
  { addr: 'A22.6', label: '', info: '' },
  { addr: 'A22.7', label: 'LC', info: 'Sistema pronto' },
  { addr: 'A23.0', label: 'LK', info: 'Lettore di entrata - Digitare codice' },
  { addr: 'A23.1', label: 'LE', info: 'Lettore di entrata - Errore' },
  { addr: 'A23.2', label: 'LB', info: 'Lettore di entrata - Operazione in corso' },
  { addr: 'A23.3', label: 'RDY', info: 'Lettore di entrata' },
  { addr: 'A23.4', label: 'RST', info: 'Lettore di entrata' },
  { addr: 'A23.5', label: 'SDR', info: 'Motore rotazione livellamento (FWD)' },
  { addr: 'A23.6', label: 'SDL', info: 'Motore rotazione livellamento (BWD)' },
  { addr: 'A23.7', label: 'SDN', info: 'Motore rotazione livellamento' },
  { addr: 'A24.0', label: '', info: '' },
  { addr: 'A24.1', label: '', info: '' },
  { addr: 'A24.2', label: '', info: '' },
  { addr: 'A24.3', label: '', info: '' },
  { addr: 'A24.4', label: '', info: '' },
  { addr: 'A24.5', label: '', info: '' },
  { addr: 'A24.6', label: '', info: '' },
  { addr: 'A24.7', label: '', info: '' },
  { addr: 'A25.0', label: '', info: '' },
  { addr: 'A25.1', label: '', info: '' },
  { addr: 'A25.2', label: '', info: '' },
  { addr: 'A25.3', label: '', info: '' },
  { addr: 'A25.4', label: '', info: '' },
  { addr: 'A25.5', label: 'SNA', info: 'Motore sollevamento livellamento (FWD)' },
  { addr: 'A25.6', label: 'SNB', info: 'Motore sollevamento livellamento (BWD)' },
  { addr: 'A25.7', label: 'SNV', info: 'Motore sollevamento livellamento' }
]
export const outputs4 = [
  { addr: 'A30.0', label: 'SBK1', info: 'Freno sollevamento' },
  { addr: 'A30.1', label: '', info: '' },
  { addr: 'A30.2', label: '', info: '' },
  { addr: 'A30.3', label: '', info: '' },
  { addr: 'A30.4', label: '', info: '' },
  { addr: 'A30.5', label: '', info: '' },
  { addr: 'A30.6', label: '', info: '' },
  { addr: 'A30.7', label: '', info: '' },
  { addr: 'A31.0', label: 'T10-1', info: 'Motore traslazione torre' },
  { addr: 'A31.1', label: 'T2', info: 'Motore traslazione carrello' },
  { addr: 'A31.2', label: 'T10-F', info: 'Freno traslazione torre' },
  { addr: 'A31.3', label: 'T10-2', info: 'Motore traslazione torre' },
  { addr: 'A31.4', label: 'KBA1', info: 'Abilitazione inverter 1' },
  { addr: 'A31.5', label: 'KBA2', info: 'Abilitazione incverter 2' },
  { addr: 'A31.6', label: 'SBK2', info: 'Freno sollevamento' },
  { addr: 'A31.7', label: '', info: '' }
]
export const outputs5 = [
  { addr: 'A40.0', label: 'A', info: 'Display' },
  { addr: 'A40.1', label: 'B', info: 'Display' },
  { addr: 'A40.2', label: 'C', info: 'Display' },
  { addr: 'A40.3', label: 'D', info: 'Display' },
  { addr: 'A40.4', label: 'AD1', info: 'Display' },
  { addr: 'A40.5', label: 'AD2', info: 'Display' },
  { addr: 'A40.6', label: 'AD3', info: 'Display' },
  { addr: 'A40.7', label: 'STR', info: 'Display' },
  { addr: 'A41.0', label: '', info: '' },
  { addr: 'A41.1', label: '', info: '' },
  { addr: 'A41.2', label: 'TRA', info: 'Motori carrello (FWD)' },
  { addr: 'A41.3', label: 'TRB', info: 'Motori carrello (BWD)' },
  { addr: 'A41.4', label: 'KCS', info: 'Motore sollevamento carrello' },
  { addr: 'A41.5', label: 'KCV', info: 'Motore centratore anteriore' },
  { addr: 'A41.6', label: 'KCH', info: 'Motore centratore posteriore' },
  { addr: 'A41.7', label: 'TCR', info: 'Avvolgicavo carrello' },
  { addr: 'A42.0', label: '', info: '' },
  { addr: 'A42.1', label: '', info: '' },
  { addr: 'A42.2', label: '', info: '' },
  { addr: 'A42.3', label: '', info: '' },
  { addr: 'A42.4', label: '', info: '' },
  { addr: 'A42.5', label: '', info: '' },
  { addr: 'A42.6', label: 'LA', info: 'Allarme' },
  { addr: 'A42.7', label: 'LC', info: 'Sistema pronto' }
]
export const merkers1 = [
  { addr: 'M0.0', label: '', info: '' },
  { addr: 'M0.1', label: '', info: '' },
  { addr: 'M0.2', label: '', info: '' },
  { addr: 'M0.3', label: '', info: '' },
  { addr: 'M0.4', label: '', info: '' },
  { addr: 'M0.5', label: '', info: '' },
  { addr: 'M0.6', label: '', info: '' },
  { addr: 'M0.7', label: '', info: '' },
  { addr: 'M1.0', label: '', info: '' },
  { addr: 'M1.1', label: '', info: '' },
  { addr: 'M1.2', label: '', info: '' },
  { addr: 'M1.3', label: '', info: '' },
  { addr: 'M1.4', label: '', info: '' },
  { addr: 'M1.5', label: '', info: '' },
  { addr: 'M1.6', label: '', info: '' },
  { addr: 'M1.7', label: '', info: '' },
  { addr: 'M2.0', label: '', info: '' },
  { addr: 'M2.1', label: '', info: '' },
  { addr: 'M2.2', label: '', info: '' },
  { addr: 'M2.3', label: '', info: '' },
  { addr: 'M2.4', label: '', info: '' },
  { addr: 'M2.5', label: '', info: '' },
  { addr: 'M2.6', label: '', info: '' },
  { addr: 'M2.7', label: '', info: '' },
  { addr: 'M3.0', label: '', info: '' },
  { addr: 'M3.1', label: '', info: '' },
  { addr: 'M3.2', label: '', info: '' },
  { addr: 'M3.3', label: '', info: '' },
  { addr: 'M3.4', label: '', info: '' },
  { addr: 'M3.5', label: '', info: '' },
  { addr: 'M3.6', label: '', info: '' },
  { addr: 'M3.7', label: '', info: '' },
  { addr: 'M4.0', label: '', info: '' },
  { addr: 'M4.1', label: '', info: '' },
  { addr: 'M4.2', label: '', info: '' },
  { addr: 'M4.3', label: '', info: '' },
  { addr: 'M4.4', label: '', info: '' },
  { addr: 'M4.5', label: '', info: '' },
  { addr: 'M4.6', label: '', info: '' },
  { addr: 'M4.7', label: '', info: '' },
  { addr: 'M5.0', label: '', info: '' },
  { addr: 'M5.1', label: '', info: '' },
  { addr: 'M5.2', label: '', info: '' },
  { addr: 'M5.3', label: '', info: '' },
  { addr: 'M5.4', label: '', info: '' },
  { addr: 'M5.5', label: '', info: '' },
  { addr: 'M5.6', label: '', info: '' },
  { addr: 'M5.7', label: '', info: '' },
  { addr: 'M6.0', label: '', info: '' },
  { addr: 'M6.1', label: '', info: '' },
  { addr: 'M6.2', label: '', info: '' },
  { addr: 'M6.3', label: '', info: '' },
  { addr: 'M6.4', label: '', info: '' },
  { addr: 'M6.5', label: '', info: '' },
  { addr: 'M6.6', label: '', info: '' },
  { addr: 'M6.7', label: '', info: '' },
  { addr: 'M7.0', label: '', info: '' },
  { addr: 'M7.1', label: '', info: '' },
  { addr: 'M7.2', label: '', info: '' },
  { addr: 'M7.3', label: '', info: '' },
  { addr: 'M7.4', label: '', info: '' },
  { addr: 'M7.5', label: '', info: '' },
  { addr: 'M7.6', label: '', info: '' },
  { addr: 'M7.7', label: '', info: '' }
]
export const alarms1 = [
  { class: 'A', label: 'AL1', info: 'Time out motore sollevamento' },
  { class: 'A', label: 'AL2', info: 'Time out motore porta' },
  { class: 'A', label: 'AL3', info: 'Time out motore clappa' },
  { class: 'A', label: 'AL4', info: 'Time out motore martinetto 1' },
  { class: 'A', label: 'AL5', info: 'Time out motore martinetto 2' },
  { class: 'A', label: 'AL6', info: 'Time out motore rotazione' },
  { class: 'A', label: 'AL7', info: 'Time out motore rotazione livellamento' },
  { class: 'A', label: 'AL8', info: 'Time out motore sollevamento livellamento' },
  { class: 'A', label: 'AL9', info: '' },
  { class: 'A', label: 'AL10', info: '' },
  { class: 'A', label: 'AL11', info: '' },
  { class: 'A', label: 'AL12', info: '' },
  { class: 'A', label: 'AL13', info: '' },
  { class: 'A', label: 'AL14', info: '' },
  { class: 'A', label: 'AL15', info: '' },
  { class: 'A', label: 'AL16', info: '' },
  { class: 'A', label: 'AL17', info: 'Magnetotermico AMC motore clappa' },
  { class: 'A', label: 'AL18', info: 'Magnetotermico ADN motore rotazione livellamento' },
  { class: 'A', label: 'AL19', info: 'Magnetotermico AD motore rotazione' },
  { class: 'A', label: 'AL20', info: 'Magnetotermico ANV motore sollevamento livellamento' },
  { class: 'A', label: 'AL21', info: 'Magnetotermico AMM1 motore martinetto 1' },
  { class: 'A', label: 'AL22', info: 'Magnetotermico AMM1 motore martinetto 2' },
  { class: 'A', label: 'AL23', info: 'Inverter non disponibile' },
  { class: 'A', label: 'AL24', info: '' },
  { class: 'A', label: 'AL25', info: 'Magnetotermico APE motore porta' },
  { class: 'A', label: 'AL26', info: '' },
  { class: 'A', label: 'AL27', info: '' },
  { class: 'A', label: 'AL28', info: '' },
  { class: 'A', label: 'AL29', info: '' },
  { class: 'A', label: 'AL30', info: '' },
  { class: 'A', label: 'AL31', info: '' },
  { class: 'A', label: 'AL32', info: '' },
  { class: 'A', label: 'AL33', info: 'Sensori ECA/ECB posizione clappa' },
  { class: 'A', label: 'AL34', info: 'Sensori EOM/EZM posizione martinetto 1' },
  { class: 'A', label: 'AL35', info: 'Sensori EOM/EZM posizione martinetto 2' },
  { class: 'A', label: 'AL36', info: 'Sensori EXPV/EFB posizione elevatore' },
  { class: 'A', label: 'AL37', info: 'Sensori EZE/EOE posizione porta' },
  { class: 'A', label: 'AL38', info: '' },
  { class: 'A', label: 'AL39', info: '' },
  { class: 'A', label: 'AL40', info: '' },
  { class: 'A', label: 'AL41', info: '' },
  { class: 'A', label: 'AL42', info: '' },
  { class: 'A', label: 'AL43', info: '' },
  { class: 'A', label: 'AL44', info: '' },
  { class: 'A', label: 'AL45', info: '' },
  { class: 'A', label: 'AL46', info: '' },
  { class: 'A', label: 'AL47', info: '' },
  { class: 'A', label: 'AL48', info: '' },
  { class: 'A', label: 'AL49', info: '' },
  { class: 'A', label: 'AL50', info: '' },
  { class: 'A', label: 'AL51', info: '' },
  { class: 'A', label: 'AL52', info: '' },
  { class: 'A', label: 'AL53', info: '' },
  { class: 'A', label: 'AL54', info: '' },
  { class: 'A', label: 'AL55', info: '' },
  { class: 'A', label: 'AL56', info: '' },
  { class: 'A', label: 'AL57', info: '' },
  { class: 'A', label: 'AL58', info: '' },
  { class: 'A', label: 'AL59', info: '' },
  { class: 'A', label: 'AL60', info: '' },
  { class: 'A', label: 'AL61', info: '' },
  { class: 'A', label: 'AL62', info: '' },
  { class: 'A', label: 'AL63', info: '' },
  { class: 'A', label: 'AL64', info: '' }
]
export const alarms2 = [
  { class: 'B', label: 'AL1', info: 'Time out motore sollevamento' },
  { class: 'B', label: 'AL2', info: 'Time out motore porta' },
  { class: 'B', label: 'AL3', info: 'Time out motore clappa' },
  { class: 'B', label: 'AL4', info: 'Time out motore martinetto 1' },
  { class: 'B', label: 'AL5', info: 'Time out motore martinetto 2' },
  { class: 'B', label: 'AL6', info: 'Time out motore rotazione' },
  { class: 'B', label: 'AL7', info: 'Time out motore rotazione livellamento' },
  { class: 'B', label: 'AL8', info: 'Time out motore sollevamento livellamento' },
  { class: 'B', label: 'AL9', info: '' },
  { class: 'B', label: 'AL10', info: '' },
  { class: 'B', label: 'AL11', info: '' },
  { class: 'B', label: 'AL12', info: '' },
  { class: 'B', label: 'AL13', info: '' },
  { class: 'B', label: 'AL14', info: '' },
  { class: 'B', label: 'AL15', info: '' },
  { class: 'B', label: 'AL16', info: '' },
  { class: 'B', label: 'AL17', info: 'Magnetotermico AMC motore clappa' },
  { class: 'B', label: 'AL18', info: 'Magnetotermico ADN motore rotazione livellamento' },
  { class: 'B', label: 'AL19', info: 'Magnetotermico AD motore rotazione' },
  { class: 'B', label: 'AL20', info: 'Magnetotermico ANV motore sollevamento livellamento' },
  { class: 'B', label: 'AL21', info: 'Magnetotermico AMM1 motore martinetto 1' },
  { class: 'B', label: 'AL22', info: 'Magnetotermico AMM1 motore martinetto 2' },
  { class: 'B', label: 'AL23', info: 'Inverter non disponibile' },
  { class: 'B', label: 'AL24', info: '' },
  { class: 'B', label: 'AL25', info: 'Magnetotermico APE motore porta' },
  { class: 'B', label: 'AL26', info: '' },
  { class: 'B', label: 'AL27', info: '' },
  { class: 'B', label: 'AL28', info: '' },
  { class: 'B', label: 'AL29', info: '' },
  { class: 'B', label: 'AL30', info: '' },
  { class: 'B', label: 'AL31', info: '' },
  { class: 'B', label: 'AL32', info: '' },
  { class: 'B', label: 'AL33', info: 'Sensori ECA/ECB posizione clappa' },
  { class: 'B', label: 'AL34', info: 'Sensori EOM/EZM posizione martinetto 1' },
  { class: 'B', label: 'AL35', info: 'Sensori EOM/EZM posizione martinetto 2' },
  { class: 'B', label: 'AL36', info: 'Sensori EXPV/EFB posizione elevatore' },
  { class: 'B', label: 'AL37', info: 'Sensori EZE/EOE posizione porta' },
  { class: 'B', label: 'AL38', info: '' },
  { class: 'B', label: 'AL39', info: '' },
  { class: 'B', label: 'AL40', info: '' },
  { class: 'B', label: 'AL41', info: '' },
  { class: 'B', label: 'AL42', info: '' },
  { class: 'B', label: 'AL43', info: '' },
  { class: 'B', label: 'AL44', info: '' },
  { class: 'B', label: 'AL45', info: '' },
  { class: 'B', label: 'AL46', info: '' },
  { class: 'B', label: 'AL47', info: '' },
  { class: 'B', label: 'AL48', info: '' },
  { class: 'B', label: 'AL49', info: '' },
  { class: 'B', label: 'AL50', info: '' },
  { class: 'B', label: 'AL51', info: '' },
  { class: 'B', label: 'AL52', info: '' },
  { class: 'B', label: 'AL53', info: '' },
  { class: 'B', label: 'AL54', info: '' },
  { class: 'B', label: 'AL55', info: '' },
  { class: 'B', label: 'AL56', info: '' },
  { class: 'B', label: 'AL57', info: '' },
  { class: 'B', label: 'AL58', info: '' },
  { class: 'B', label: 'AL59', info: '' },
  { class: 'B', label: 'AL60', info: '' },
  { class: 'B', label: 'AL61', info: '' },
  { class: 'B', label: 'AL62', info: '' },
  { class: 'B', label: 'AL63', info: '' },
  { class: 'B', label: 'AL64', info: '' }
]
export const alarms3 = [
  { class: 'T', label: 'AL1', info: 'Time out motore traslazione carrello 1° stallo' },
  { class: 'T', label: 'AL2', info: 'Time out motore traslazione carrello 2° stallo' },
  { class: 'T', label: 'AL3', info: 'Time out motore traslazione carrello 3° stallo' },
  { class: 'T', label: 'AL4', info: 'Time out motore sollevamento carrello' },
  { class: 'T', label: 'AL5', info: 'Time out motore centratore anteriore carrello' },
  { class: 'T', label: 'AL6', info: 'Time out motore centratore posteriore carrello' },
  { class: 'T', label: 'AL7', info: 'Time out motore sollevamento torre' },
  { class: 'T', label: 'AL8', info: 'Time out motore 1 traslazione torre' },
  { class: 'T', label: 'AL9', info: 'Time out motore 2 traslazione torre' },
  { class: 'T', label: 'AL10', info: '' },
  { class: 'T', label: 'AL11', info: '' },
  { class: 'T', label: 'AL12', info: '' },
  { class: 'T', label: 'AL13', info: '' },
  { class: 'T', label: 'AL14', info: '' },
  { class: 'T', label: 'AL15', info: '' },
  { class: 'T', label: 'AL16', info: '' },
  { class: 'T', label: 'AL17', info: 'Magnetotermico ASBK freno sollevamento' },
  { class: 'T', label: 'AL18', info: 'Magnetotermico RTA motore sollevamento' },
  { class: 'T', label: 'AL19', info: 'Fusibile FE1 24VDC' },
  { class: 'T', label: 'AL20', info: 'Magnetotermico AF7' },
  { class: 'T', label: 'AL21', info: 'Inverter 1 non disponibile' },
  { class: 'T', label: 'AL22', info: 'Inverter 2 non disponibile' },
  { class: 'T', label: 'AL23', info: 'Magnetotermico AH motori traslazione torre' },
  { class: 'T', label: 'AL24', info: 'Magnetotermico AGF motori traslazione carrello' },
  { class: 'T', label: 'AL25', info: 'Magnetotermico AKKP' },
  { class: 'T', label: 'AL26', info: 'Magnetotermico MTC motori carrello' },
  { class: 'T', label: 'AL27', info: '' },
  { class: 'T', label: 'AL28', info: '' },
  { class: 'T', label: 'AL29', info: '' },
  { class: 'T', label: 'AL30', info: '' },
  { class: 'T', label: 'AL31', info: '' },
  { class: 'T', label: 'AL32', info: '' },
  { class: 'T', label: 'AL33', info: 'Sensori RES/REH carrello' },
  { class: 'T', label: 'AL34', info: 'Sensori EHPA/EHPB posizione torre davanti elevatore' },
  { class: 'T', label: 'AL35', info: 'Carrello consensi ciclo su elevatore' },
  { class: 'T', label: 'AL36', info: 'Controllo sensori FTXV/FTXH durante ciclo carrello' },
  { class: 'T', label: 'AL37', info: 'Time out arrivo centratura durante ciclo elevatore' },
  { class: 'T', label: 'AL38', info: 'Laser verticale 1 fuori tolleranza' },
  { class: 'T', label: 'AL39', info: 'Laser verticale 2 fuori tolleranza' },
  { class: 'T', label: 'AL40', info: 'Laser orizzontale 1 fuori tolleranza' },
  { class: 'T', label: 'AL41', info: 'Laser orizzontale 2 fuori tolleranza' },
  { class: 'T', label: 'AL42', info: '' },
  { class: 'T', label: 'AL43', info: '' },
  { class: 'T', label: 'AL44', info: '' },
  { class: 'T', label: 'AL45', info: '' },
  { class: 'T', label: 'AL46', info: '' },
  { class: 'T', label: 'AL47', info: '' },
  { class: 'T', label: 'AL48', info: '' },
  { class: 'T', label: 'AL49', info: '' },
  { class: 'T', label: 'AL50', info: '' },
  { class: 'T', label: 'AL51', info: '' },
  { class: 'T', label: 'AL52', info: '' },
  { class: 'T', label: 'AL53', info: '' },
  { class: 'T', label: 'AL54', info: '' },
  { class: 'T', label: 'AL55', info: '' },
  { class: 'T', label: 'AL56', info: '' },
  { class: 'T', label: 'AL57', info: '' },
  { class: 'T', label: 'AL58', info: '' },
  { class: 'T', label: 'AL59', info: '' },
  { class: 'T', label: 'AL60', info: '' },
  { class: 'T', label: 'AL61', info: '' },
  { class: 'T', label: 'AL62', info: '' },
  { class: 'T', label: 'AL63', info: '' },
  { class: 'T', label: 'AL64', info: '' }
]
